### PR TITLE
Better logging

### PR DESCRIPTION
**Pull request by johnml1135**
Make it a bit cleaner and easier to parse.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/490)

### CODE REVIEW

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/490)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Shared/Controllers/ErrorResultFilter.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/serval/490#-O6aYzVFCc3t_2oEaNNC:-O6aYzVFCc3t_2oEaNND:bseno3o) ([raw file](https://github.com/sillsdev/serval/blob/cfb129aff14bcfaf9530f8be9b04d0d45760d801/src/Serval/src/Serval.Shared/Controllers/ErrorResultFilter.cs#L12)):*
> ```Smalltalk
>         if (context.HttpContext.Response.StatusCode >= 400)
>         {
>             string routeData = JsonSerializer.Serialize(
> ```

Is there no cleaner way to do this? It seems like there ought to be a specific property you can compare against. And did you confirm that this works? (I expect it would - just confirming).
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 708 at r1](https://reviewable.io/reviews/sillsdev/serval/490#-O6aZJFrEwWxyaBfw7uv:-O6aZJFrEwWxyaBfw7uw:b4ha8nm) ([raw file](https://github.com/sillsdev/serval/blob/cfb129aff14bcfaf9530f8be9b04d0d45760d801/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L708)):*
> ```Smalltalk
>             return NoContent();
>         _logger.LogInformation(
>             "Returning USFM for {TextId} in engine {EngineId} for corpus {corpusId}",
> ```

This should be helpful!

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/490)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Shared/Controllers/ErrorResultFilter.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/serval/490#-O6aYzVFCc3t_2oEaNNC:-O6ah8-U86GwOllySljA:bsans12) ([raw file](https://github.com/sillsdev/serval/blob/cfb129aff14bcfaf9530f8be9b04d0d45760d801/src/Serval/src/Serval.Shared/Controllers/ErrorResultFilter.cs#L12)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is there no cleaner way to do this? It seems like there ought to be a specific property you can compare against. And did you confirm that this works? (I expect it would - just confirming).
</blockquote></details>

Do we need to log every request that responds with a 4XX status code? Most 4XX codes are pretty normal. Is there a subset of 4XX codes that we are interested in? Logging 5XX codes makes sense.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Shared/Controllers/ErrorResultFilter.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/serval/490#-O6aYzVFCc3t_2oEaNNC:-O6b0LzH-j6csRedS4mL:b-rg4dyo) ([raw file](https://github.com/sillsdev/serval/blob/cfb129aff14bcfaf9530f8be9b04d0d45760d801/src/Serval/src/Serval.Shared/Controllers/ErrorResultFilter.cs#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do we need to log every request that responds with a 4XX status code? Most 4XX codes are pretty normal. Is there a subset of 4XX codes that we are interested in? Logging 5XX codes makes sense.
</blockquote></details>

I agree - let's just do 500 codes.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/490#-:-O6b79K96hvGPSx6lGHc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Pull request merged**
