### PR TITLE
Fix corpus e2e tests

### PR DESCRIPTION
**Pull request by johnml1135**
A few updates - this should resolve all issues.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/509)

### CODE REVIEW

**Review by Enkidu93 — APPROVED** [review]
Thank you for doing this, John! Seems like you got to familiarize yourself with the new code just like you wanted :laughing: 

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/509#-:-O8xH_zFCXdspArjQiBM:bjae2gq)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 469 at r1](https://reviewable.io/reviews/sillsdev/serval/509#-O8xGHNQCMHSdjeZg5Tk:-O8xGHNQCMHSdjeZg5Tl:b-lrd7ci) ([raw file](https://github.com/sillsdev/serval/blob/6fc1257453f2921f2f39e441805cb91a5c045cfc/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L469)):*
> ```Smalltalk
>     }
> 
>     private static IEnumerable<Row> GetPretranslateCorpusNoTarget(ITextCorpus[] srcCorpora)
> ```

Seems like this method and `AlignPretranslateRows` could be merged into a single method. That might allow the logic in `WriteDataFiles` to be simpler. Just a thought - not necessary.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 469 at r1](https://reviewable.io/reviews/sillsdev/serval/509#-O8xGHNQCMHSdjeZg5Tk:-O8xMpmy15qD2qHLgNjY:b6eljk7) ([raw file](https://github.com/sillsdev/serval/blob/6fc1257453f2921f2f39e441805cb91a5c045cfc/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L469)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Seems like this method and `AlignPretranslateRows` could be merged into a single method. That might allow the logic in `WriteDataFiles` to be simpler. Just a thought - not necessary.
</blockquote></details>

I wanted to, but the TextRow and ParallelTextRow are incompatible.  Slicing it up looked like a bit too much for me.  I could possibly make a another class, etc., but I think it is cleaner just to have two functions.  Check it out yourself - `row.SourceText.Length > 0` vs `row.Segment.Count > 0` and `!row.IsTargetRangeStart && row.IsTargetInRange` vs `!row.IsRangeStart && row.IsInRange`.

**Comment by johnml1135** [comment]
Also, Machine will need to be re-released to handle the infinite loop.  The E2E tests are failing because of it.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/509)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 469 at r1](https://reviewable.io/reviews/sillsdev/serval/509#-O8xGHNQCMHSdjeZg5Tk:-O9B-MNhBtNM-onwShVy:b-adrcdf) ([raw file](https://github.com/sillsdev/serval/blob/6fc1257453f2921f2f39e441805cb91a5c045cfc/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L469)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I wanted to, but the TextRow and ParallelTextRow are incompatible.  Slicing it up looked like a bit too much for me.  I could possibly make a another class, etc., but I think it is cleaner just to have two functions.  Check it out yourself - `row.SourceText.Length > 0` vs `row.Segment.Count > 0` and `!row.IsTargetRangeStart && row.IsTargetInRange` vs `!row.IsRangeStart && row.IsInRange`.
</blockquote></details>

I think that if you pass in an empty target text corpus to the `AlignPretranslateCorpus`, then it will work for this case.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationEngineServiceV1.cs` line 308 at r2](https://reviewable.io/reviews/sillsdev/serval/509#-O9Ayv8uCtmrkyt9MLW8:-O9Ayv8uCtmrkyt9MLW9:bn5bwlx) ([raw file](https://github.com/sillsdev/serval/blob/8c6ccd6118e7ed0faa6522c3ec529b1eaa4fd7b7/src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationEngineServiceV1.cs#L308)):*
> ```Smalltalk
>             PretranslateTextIds = pretranslateFilter == FilterChoice.TextIds ? pretranslateTextIds : null
>         };
>         if (source.PretranslateAll)
> ```

`GetFilterChoice` would be the appropriate place to perform this check. At least, that was where we use to perform this check.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 604 at r2](https://reviewable.io/reviews/sillsdev/serval/509#-O9AwigQ-YKe8xkMLItW:-O9AwigQ-YKe8xkMLItX:bbtqai8) ([raw file](https://github.com/sillsdev/serval/blob/8c6ccd6118e7ed0faa6522c3ec529b1eaa4fd7b7/src/Serval/src/Serval.Translation/Services/EngineService.cs#L604)):*
> ```Smalltalk
>             new() { Language = source.TargetLanguage, Files = { source.TargetFiles.Select(Map) } };
> 
>         if (trainingCorpus == null || (trainingCorpus.TextIds is null && trainingCorpus.ScriptureRange is null))
> ```

Might as well use `trainingCorpus is null` here to make it consistent.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 645 at r2](https://reviewable.io/reviews/sillsdev/serval/509#-O9Ax-gjAmNDDbfuYLW_:-O9Ax-gjAmNDDbfuYLWa:bn2ghot) ([raw file](https://github.com/sillsdev/serval/blob/8c6ccd6118e7ed0faa6522c3ec529b1eaa4fd7b7/src/Serval/src/Serval.Translation/Services/EngineService.cs#L645)):*
> ```Smalltalk
>         }
>         if (
>             pretranslateCorpus == null
> ```

See might comment above.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationEngineServiceV1.cs` line 308 at r2](https://reviewable.io/reviews/sillsdev/serval/509#-O9Ayv8uCtmrkyt9MLW8:-O9GI4Uu5ePSpO8O1oAL:b-8cqmje) ([raw file](https://github.com/sillsdev/serval/blob/8c6ccd6118e7ed0faa6522c3ec529b1eaa4fd7b7/src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationEngineServiceV1.cs#L308)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`GetFilterChoice` would be the appropriate place to perform this check. At least, that was where we use to perform this check.
</blockquote></details>

I see now - done.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 604 at r2](https://reviewable.io/reviews/sillsdev/serval/509#-O9AwigQ-YKe8xkMLItW:-O9GIy0dCMrETx6REB7-:bduxgpq) ([raw file](https://github.com/sillsdev/serval/blob/8c6ccd6118e7ed0faa6522c3ec529b1eaa4fd7b7/src/Serval/src/Serval.Translation/Services/EngineService.cs#L604)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Might as well use `trainingCorpus is null` here to make it consistent.
</blockquote></details>

done - trying to add IDE0041 to editorconfig, but it is not catching the errors.  Skipping for now.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 645 at r2](https://reviewable.io/reviews/sillsdev/serval/509#-O9Ax-gjAmNDDbfuYLW_:-O9GObMs8RLMMBbAGT0Q:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/8c6ccd6118e7ed0faa6522c3ec529b1eaa4fd7b7/src/Serval/src/Serval.Translation/Services/EngineService.cs#L645)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See might comment above.
</blockquote></details>

done

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 469 at r1](https://reviewable.io/reviews/sillsdev/serval/509#-O8xGHNQCMHSdjeZg5Tk:-O9GQ_GU1ieO7jVX4-GD:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/6fc1257453f2921f2f39e441805cb91a5c045cfc/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L469)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think that if you pass in an empty target text corpus to the `AlignPretranslateCorpus`, then it will work for this case.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/509)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 258 at r3](https://reviewable.io/reviews/sillsdev/serval/509#-O9GTMWhBgQH3fR_Iuha:-O9GTMWhBgQH3fR_Iuhb:b-dr5pun) ([raw file](https://github.com/sillsdev/serval/blob/6c955668eaf3e6bde13edec6bd8c69dfe0fdda5d/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L258)):*
> ```Smalltalk
>                 targetCorpora.Length > 0
>                     ? targetCorpora[0].TextCorpus
>                     : new DictionaryTextCorpus(new List<MemoryText>());
> ```

Passing in an empty list shouldn't be necessary.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 258 at r3](https://reviewable.io/reviews/sillsdev/serval/509#-O9GTMWhBgQH3fR_Iuha:-O9GU8X7D4C8rm_NbfmM:bjl5kdj) ([raw file](https://github.com/sillsdev/serval/blob/6c955668eaf3e6bde13edec6bd8c69dfe0fdda5d/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L258)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Passing in an empty list shouldn't be necessary.
</blockquote></details>

The fields are nullable in Machine - different version of dotnet...

**Review by ddaspit — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/509)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 258 at r3](https://reviewable.io/reviews/sillsdev/serval/509#-O9GTMWhBgQH3fR_Iuha:-O9GVP_v6YMQ4nWqqhqh:bwzo0p6) ([raw file](https://github.com/sillsdev/serval/blob/6c955668eaf3e6bde13edec6bd8c69dfe0fdda5d/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L258)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The fields are nullable in Machine - different version of dotnet...
</blockquote></details>

I meant that you don't need to pass an empty list into the `DictionaryTextCorpus` constructor. I think this change will break things.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 258 at r3](https://reviewable.io/reviews/sillsdev/serval/509#-O9GTMWhBgQH3fR_Iuha:-O9GZ8eN5jkwY3bcK6Hi:b6yf9h9) ([raw file](https://github.com/sillsdev/serval/blob/6c955668eaf3e6bde13edec6bd8c69dfe0fdda5d/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L258)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I meant that you don't need to pass an empty list into the `DictionaryTextCorpus` constructor. I think this change will break things.
</blockquote></details>

Yes, it does: System.NullReferenceException: Object reference not set to an instance of an object.
machine-job-cntr     |          at SIL.Machine.Corpora.ParallelTextCorpus.GetRows(IEnumerable`1 textIds)+MoveNext() in /home/johnml1135/repos/machine/src/SIL.Machine/Corpora/ParallelTextCorpus.cs:line 39
machine-job-cntr     |          at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
machine-job-cntr     |          at Serval.Machine.Shared.Services.PreprocessBuildJob.AlignPretranslateCorpus(ITextCorpus[] srcCorpora, ITextCorpus trgCorpus)+MoveNext() in /home/johnml1135/repos/serval/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs:line 424

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 258 at r3](https://reviewable.io/reviews/sillsdev/serval/509#-O9GTMWhBgQH3fR_Iuha:-O9GZZp6A4gpN-rlzanF:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/6c955668eaf3e6bde13edec6bd8c69dfe0fdda5d/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L258)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Yes, it does: System.NullReferenceException: Object reference not set to an instance of an object.
machine-job-cntr     |          at SIL.Machine.Corpora.ParallelTextCorpus.GetRows(IEnumerable`1 textIds)+MoveNext() in /home/johnml1135/repos/machine/src/SIL.Machine/Corpora/ParallelTextCorpus.cs:line 39
machine-job-cntr     |          at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
machine-job-cntr     |          at Serval.Machine.Shared.Services.PreprocessBuildJob.AlignPretranslateCorpus(ITextCorpus[] srcCorpora, ITextCorpus trgCorpus)+MoveNext() in /home/johnml1135/repos/serval/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs:line 424
</blockquote></details>

Done

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/509#-:-O9GZnGt0bi3sx_eVvCO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
