### PR TITLE
Fixes E2E tests failing in CI #109

### PR DESCRIPTION
**Pull request by Enkidu93**
* Fixes small typo in Echo pretranslation E2E test. 
* Adds workflow_dispatch option to ci-e2e.
* (Also, adds .history* to gitignore).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/110)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
As a part of this PR, could you move the `ServalClientHelper` class to the `Serval.E2ETests` assembly. That class is only being used for E2E tests and probably needs a little more work before it is released as part of the `Serval.Client` library.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110#-:-NdHiCfX-dXG-04e0VxH:b-krpjy8)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 71 at r1](https://reviewable.io/reviews/sillsdev/serval/110#-NdHhhPvB19gjVFzxFCI:-NdHhhPvB19gjVFzxFCJ:bfdlwe6) ([raw file](https://github.com/sillsdev/serval/blob/ab00a665101a69ee00bc7772112ec9792147724f/tests/Serval.E2ETests/ServalApiTests.cs#L71)):*
> ```Smalltalk
>     {
>         await _helperClient.ClearEngines();
>         string engineId = await _helperClient.CreateNewEngine("Echo", "es", "es", "Echo2");
> ```

I think the cause of this issue is that the `EnginePerUser` dictionary is not cleared in the `ClearEngines` method.

**Review by Enkidu93 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110#-:-NdahwzvDJybsEm9PlFu:bb6un1j)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 71 at r1](https://reviewable.io/reviews/sillsdev/serval/110#-NdHhhPvB19gjVFzxFCI:-NdahyZHAf5ymfMH_v5A:b16x7vy) ([raw file](https://github.com/sillsdev/serval/blob/ab00a665101a69ee00bc7772112ec9792147724f/tests/Serval.E2ETests/ServalApiTests.cs#L71)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think the cause of this issue is that the `EnginePerUser` dictionary is not cleared in the `ClearEngines` method.
</blockquote></details>

I added a call to `Clear()`. I also switched to using the `SetUp` function rather a constructor because I believe it's more stylistically sound, is more consistent with other tests, and because, as I understand it, it guarantees that each test is unaffected by the other tests if they're run concurrently.

**Review by ddaspit — COMMENTED** [review]
Everything looks good. You forgot to remove the `ServalClientHelper` class from the `Serval.Client` assembly.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110#-:-NdalzdDBIA4NSLB4_hx:b-6hkb9u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> Everything looks good. You forgot to remove the `ServalClientHelper` class from the `Serval.Client` assembly.
> 
> > Reviewed 2 of 2 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110#-:-NdalzdDBIA4NSLB4_hx:b-6hkb9u)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

Sorry, somehow it didn't commit even though I had changed it locally and hit the save/commit all and push button. It's done now (I think :laughing: ).

**Comment by johnml1135** [comment]
:lgtm:

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110#-:-NdatcRS6zOa7jlUoV6U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
