### PR TITLE
Deduplicate kbts

### LINKED ISSUE #538: Duplicated Key Terms
Michael reported that in an English-to-Indonesian project, the automatically added KBTs were duplicated:

"For instance, in the train.src.txt / train.trg.txt files that were constructed here from those default term renderings, there are many many duplicates:

4 mappings of Joseph --> Yusuf
4 mappings of Joram --> Yoram
4 mappings of Jezreel --> Yezreel
3 mappings of Jotham --> Yotam
and on and on ...

This duplication is probably not helpful for fine-tuning."

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes #538

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/551)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 105 at r1](https://reviewable.io/reviews/sillsdev/serval/551#-OD9AB6K0zBb0b6ecNfZ:-OD9AB6K0zBb0b6ecNf_:b-6rf4kb) ([raw file](https://github.com/sillsdev/serval/blob/7b9c4a8e87b6d8dce9c9b13ca160c41e3b6021c8/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L105)):*
> ```Smalltalk
>                         .AlignRows(targetTermCorpora.ChooseFirst());
>                     foreach (
>                         ParallelTextRow row in parallelKeyTermsCorpus.DistinctBy(row => row.SourceText + row.TargetText)
> ```

Should this be a tuple rather than a concatenated string?

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/551)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 105 at r1](https://reviewable.io/reviews/sillsdev/serval/551#-OD9AB6K0zBb0b6ecNfZ:-ODCO6yK33b7rQnX8LMu:b-wdybm4) ([raw file](https://github.com/sillsdev/serval/blob/7b9c4a8e87b6d8dce9c9b13ca160c41e3b6021c8/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L105)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Should this be a tuple rather than a concatenated string?
</blockquote></details>

I went ahead and switched it. I'm not sure what's most efficient under the hood.

**Comment by johnml1135** [comment]
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 105 at r1](https://reviewable.io/reviews/sillsdev/serval/551#-OD9AB6K0zBb0b6ecNfZ:-ODCcXeq8528YMuo3RNK:b-y5risc) ([raw file](https://github.com/sillsdev/serval/blob/7b9c4a8e87b6d8dce9c9b13ca160c41e3b6021c8/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L105)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I went ahead and switched it. I'm not sure what's most efficient under the hood.
</blockquote></details>

It was more about the off chance that there could be a conflict where there would be "hello world " + "day" and "hello " + "world day".  Not likely, but the tuple solution appears cleaner to me.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
