### PR TITLE
refactor E2E oauth usage - #333

### PR DESCRIPTION
**Pull request by johnml1135**
We are killing the auth0 development tenant.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/334)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/334)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 64 at r1](https://reviewable.io/reviews/sillsdev/serval/334#-NrfRBLy7hgX_dFhDBep:-NrfRBLzB9Dvs7AW3eOA:b-csl42s) ([raw file](https://github.com/sillsdev/serval/blob/8a7cc4eebcf0f27fdbfcd72d86c07bdcc19b5f09/tests/Serval.E2ETests/ServalClientHelper.cs#L64)):*
> ```Smalltalk
>     }
> 
>     public async Task SetupAsync()
> ```

Why did you create this `SetupAsync` method?

**Comment by johnml1135** [comment]
I was unaware of OneTimeSetup.  That is better.

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 64 at r1](https://reviewable.io/reviews/sillsdev/serval/334#-NrfRBLy7hgX_dFhDBep:-Nrfi_fEAnH9Sm9Qt7SB:b-9eqk18) ([raw file](https://github.com/sillsdev/serval/blob/8a7cc4eebcf0f27fdbfcd72d86c07bdcc19b5f09/tests/Serval.E2ETests/ServalClientHelper.cs#L64)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why did you create this `SetupAsync` method?
</blockquote></details>

Reverted - OneTimeSetup (as per conversation above) it a better strategy.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/334)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 10 at r2](https://reviewable.io/reviews/sillsdev/serval/334#-NrlDO4J3AAe6YVscfGx:-NrlDO4J3AAe6YVscfGy:beu3fd3) ([raw file](https://github.com/sillsdev/serval/blob/5af50ecef7a30011eb290322085427f648de5154/tests/Serval.E2ETests/ServalApiTests.cs#L10)):*
> ```Smalltalk
> 
>     [OneTimeSetUp]
>     public async Task OneTimeSetup()
> ```

We still want to clean up the engines between each test.

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 10 at r2](https://reviewable.io/reviews/sillsdev/serval/334#-NrlDO4J3AAe6YVscfGx:-NrpTp-77ET6ghY4Lfbe:b2yhi8f) ([raw file](https://github.com/sillsdev/serval/blob/5af50ecef7a30011eb290322085427f648de5154/tests/Serval.E2ETests/ServalApiTests.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We still want to clean up the engines between each test.
</blockquote></details>

yes- my mistake.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/334#-:-NrpoGs-6yLaMt3rYjNr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
