### PR TITLE
Added serval release version to translation build

### PR DESCRIPTION
**Pull request by mudiagaobrikisil**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 5 unresolved discussions (waiting on @mudiagaobrikisil)

___
*[`src/Serval/src/Serval.ApiServer/ServalSettings.cs` line 0 at r1](https://reviewable.io/reviews/sillsdev/serval/517#-O9WA2CK0EqvfQPS-Q-S:-O9WA2CK0EqvfQPS-Q-T:bv23yei) ([raw file](https://github.com/sillsdev/serval/blob/7b1172aab909608fda3dca984e1c8b59adf7fb1d/src/Serval/src/Serval.ApiServer/ServalSettings.cs#L0)):*
This looks like a duplicate class.
___
*[`src/Serval/src/Serval.Shared/Configuration/ServalSettings.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/517#-O9W8kKw7Hhfax7UJW1Q:-O9W8kKw7Hhfax7UJW1R:bocju1c) ([raw file](https://github.com/sillsdev/serval/blob/7b1172aab909608fda3dca984e1c8b59adf7fb1d/src/Serval/src/Serval.Shared/Configuration/ServalSettings.cs#L3)):*
> ```Smalltalk
> namespace Serval.Shared.Configuration;
> 
> public class ServalSettings
> ```

I don't think we need a separate class for this. We can just add the property to `ApiOptions`. Also, I would rename the property to `ServalVersion`.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationBuildDto.cs` line 30 at r1](https://reviewable.io/reviews/sillsdev/serval/517#-O9W9CyzBRlHNHMMMem2:-O9W9CyzBRlHNHMMMem3:bmfvbg9) ([raw file](https://github.com/sillsdev/serval/blob/7b1172aab909608fda3dca984e1c8b59adf7fb1d/src/Serval/src/Serval.Translation/Contracts/TranslationBuildDto.cs#L30)):*
> ```Smalltalk
>     /// </example>
>     public object? Options { get; init; }
>     public string? ServalReleaseVersion { get; init; }
> ```

I would name this `ServalVersion`.
___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/serval/517#-O9W85SQELhvHoY_j2kP:-O9W85SQELhvHoY_j2kQ:b-10ytq9) ([raw file](https://github.com/sillsdev/serval/blob/7b1172aab909608fda3dca984e1c8b59adf7fb1d/src/Serval/src/Serval.Translation/Models/Build.cs#L18)):*
> ```Smalltalk
>     public DateTime? DateFinished { get; init; }
>     public IReadOnlyDictionary<string, object>? Options { get; init; }
>     public string? ServalReleaseVersion { get; set; }
> ```

I would just name this `ServalVersion`.
___
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 50 at r1](https://reviewable.io/reviews/sillsdev/serval/517#-O9WADXK6ZcQ4ZlU2DZH:-O9WADXK6ZcQ4ZlU2DZI:b9ezhpk) ([raw file](https://github.com/sillsdev/serval/blob/7b1172aab909608fda3dca984e1c8b59adf7fb1d/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L50)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task GetServalReleaseVersion()
> ```

I don't think we need an E2E test for this. We could just add an extra check in the `TranslationEngineTests.StartBuildForEngineByIdAsync` integration test.

**Comment by mudiagaobrikisil** [comment]
Thank you Damien.

All noted and changes will be implemented.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 4 of 10 files at r2, 3 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 2 unresolved discussions (waiting on @mudiagaobrikisil)

___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 18 at r4](https://reviewable.io/reviews/sillsdev/serval/517#-O9uq8_mCMot1Pq0olVQ:-O9uq8_mCMot1Pq0olVR:b-d09y0v) ([raw file](https://github.com/sillsdev/serval/blob/3ca47ace0a4e75ed0672fd876c78cc4f069a0f57/src/Serval/src/Serval.Translation/Models/Build.cs#L18)):*
> ```Smalltalk
>     public DateTime? DateFinished { get; init; }
>     public IReadOnlyDictionary<string, object>? Options { get; init; }
>     public string? DeploymentVersion { get; set; } = "Unknown";
> ```

This doesn't need to have a default value. I would just make this `{ get; init; }`.
___
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 2000 at r4](https://reviewable.io/reviews/sillsdev/serval/517#-O9uuSa_9agT2QWW000o:-O9uuSa_9agT2QWW000p:b-qdi1sv) ([raw file](https://github.com/sillsdev/serval/blob/3ca47ace0a4e75ed0672fd876c78cc4f069a0f57/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L2000)):*
> ```Smalltalk
>         private readonly IServiceScope _scope;
>         private readonly MongoClient _mongoClient;
>         public readonly IOptionsMonitor<ApiOptions> ApiOptions;
> ```

Is this still needed?

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 1 unresolved discussion (waiting on @mudiagaobrikisil)

___
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 2000 at r4](https://reviewable.io/reviews/sillsdev/serval/517#-O9uuSa_9agT2QWW000o:-O9z9Bnk7e-MHPFqNbFA:b-n3e40c) ([raw file](https://github.com/sillsdev/serval/blob/3ca47ace0a4e75ed0672fd876c78cc4f069a0f57/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L2000)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

You can remove these commented lines.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1306 at r6](https://reviewable.io/reviews/sillsdev/serval/517#-O9zd2Y0EHfu6Mkn1lQY:-O9zd2Y0EHfu6Mkn1lQZ:b-m5pl3e) ([raw file](https://github.com/sillsdev/serval/blob/56bd93f9948fb797a78b2a574478e4cfe707e487/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1306)):*
> ```Smalltalk
>     private Build Map(Engine engine, TranslationBuildConfigDto source)
>     {
>         string deploymentVersion = configuration.GetValue<string>("DeploymentVersion") ?? "Unknown";
> ```

I think it is a little unclear pulling the Deployment version from within the map function.  I would like to see it in the main controller function  - either passing it as a parameter to the map function or adding to the Build it after it has been created.

**Comment by johnml1135** [comment]
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1996 at r6](https://reviewable.io/reviews/sillsdev/serval/517#-O9zdbSJ2PnnRwmq2mCp:-O9zdbSJ2PnnRwmq2mCq:b-uia2y4) ([raw file](https://github.com/sillsdev/serval/blob/56bd93f9948fb797a78b2a574478e4cfe707e487/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1996)):*
> ```Smalltalk
>     }
> 
>     public class TestEnvironment : DisposableBase
> ```

Does this need to be public?

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 4 of 10 files at r2, 2 of 6 files at r3, 2 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 4 unresolved discussions (waiting on @mudiagaobrikisil)

___
*[`src/Serval/src/Serval.ApiServer/appsettings.json` line 19 at r6](https://reviewable.io/reviews/sillsdev/serval/517#-O9zcj2N6Q2eRb6RQnY6:-O9zcj2N6Q2eRb6RQnY7:b-a6xbij) ([raw file](https://github.com/sillsdev/serval/blob/56bd93f9948fb797a78b2a574478e4cfe707e487/src/Serval/src/Serval.ApiServer/appsettings.json#L19)):*
> ```JSON
>   },
>   "ServalSettings": {
>     "ReleaseVersion": "1.0.0"
> ```

This should be removed - we are using DeploymentVersion.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 3 unresolved discussions (waiting on @mudiagaobrikisil)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 4 unresolved discussions (waiting on @mudiagaobrikisil)

___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 12 at r7](https://reviewable.io/reviews/sillsdev/serval/517#-OAItPJ93VPFfUmAfdNH:-OAItPJ93VPFfUmAfdNI:bmfenue) ([raw file](https://github.com/sillsdev/serval/blob/80682bab382a1779313dd9ffe7c89f4c954cdc87/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L12)):*
> ```Smalltalk
>     IPretranslationService pretranslationService,
>     IOptionsMonitor<ApiOptions> apiOptions,
>     IConfiguration configuration,
> ```

This should be assigned to a private readonly field.

**Review by ddaspit — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 3 unresolved discussions (waiting on @mudiagaobrikisil)

**Comment by Enkidu93** [comment]
Looks good! Congrats, Mudi! 🥳

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/517)* status: all files reviewed, 1 unresolved discussion (waiting on @mudiagaobrikisil)

**Pull request merged**
