### PR TITLE
Call 'GetAsksById' once per DoWork

### PR DESCRIPTION
**Pull request by Enkidu93**
Potential fix for https://github.com/sillsdev/serval/issues/492. @johnml1135, I'll leave potentially updating the polling interval in the deployments to you if you deem it necessary. 

Also, I think that there was a bug here where tasks would have been counted in both queues. There were no reports of this (to my knowledge) and there isn't testing that covers the logic in this class. In any case, I fixed that as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/504)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 65 at r1](https://reviewable.io/reviews/sillsdev/serval/504#-O8NExpJ1GGEDJ5XeERd:-O8NExpJ1GGEDJ5XeERe:bru841i) ([raw file](https://github.com/sillsdev/serval/blob/c8449c852d2c4a680742d3b483271e74e2ebe4f0/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L65)):*
> ```Smalltalk
>             {
>                 var tasksPerEngineType = tasks
>                     .Where(kvp =>
> ```

I'm a little confused what the extra "where" and "select" does...

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504)* status: all files reviewed, 6 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 149 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NOvuNCHzFTn9HiPHb:-O8NOvuNCHzFTn9HiPHc:b-97pm40) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L149)):*
> ```Smalltalk
>     )
>     {
>         await PopulateQueueNamesToIdsAsync(cancellationToken);
> ```

If we return the dictionary from this method call, then we know that it will never be null.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 151 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NPDdMD-E_ZGjP7teC:-O8NPDdMD-E_ZGjP7teD:bt1r0gx) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L151)):*
> ```Smalltalk
>         await PopulateQueueNamesToIdsAsync(cancellationToken);
> 
>         var body = new JsonObject { ["queue"] = _queueNamesToIds![queue] };
> ```

We should check if the queue name exists in the dictionary. If not, we should try repopulating the dictionary.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 160 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NQFZ17IC69oL1NCYu:-O8NQFZ17IC69oL1NCYv:b-1ndujo) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L160)):*
> ```Smalltalk
>     private async Task PopulateQueueNamesToIdsAsync(CancellationToken cancellationToken = default)
>     {
>         if (_queueNamesToIds != null)
> ```

We should synchronize access to `_queueNamesToIds`, since it is a mutable field in a singleton service.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 182 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NMyz4EwZ7vXx1ZgMQ:-O8NMyz4EwZ7vXx1ZgMR:b-4s0ler) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L182)):*
> ```Smalltalk
>     )
>     {
>         if (!ids.Any())
> ```

We should convert `ids` to an array before performing this check. Generally, you want to avoid iterating over an `IEnumerable` multiple times.

**Review by Enkidu93 — COMMENTED** [review]
I'll let you, @johnml1135, address the changes that @ddaspit  requested on your commit - unless you'd like me to go ahead and address them.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504#-:-O8Od0mY4c8SgIUGrV72:b-rggx37)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 55 at r1](https://reviewable.io/reviews/sillsdev/serval/504#-O8NE2ViASxYU7lpktgt:-O8Ocw2w0pluAWBzBMch:b-4029o1) ([raw file](https://github.com/sillsdev/serval/blob/c8449c852d2c4a680742d3b483271e74e2ebe4f0/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L55)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Getting tasks by ID only takes a few milliseconds.  It's the queue task that takes 3-5 seconds.  I pushed an update to bring down the time to < 100ms per queue call.
</blockquote></details>

OK, cool, that's great!
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 65 at r1](https://reviewable.io/reviews/sillsdev/serval/504#-O8NExpJ1GGEDJ5XeERd:-O8OcZ422Lj_7x7aBCzK:b-jfj63h) ([raw file](https://github.com/sillsdev/serval/blob/c8449c852d2c4a680742d3b483271e74e2ebe4f0/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L65)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I'm a little confused what the extra "where" and "select" does...
</blockquote></details>

Unless I'm mistaken (which is surely possible :laughing:), this variable was grabbing all tasks, not just the ones of that loop's engine type which would throw the numbers off.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 149 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NOvuNCHzFTn9HiPHb:-O8cmsdTBe0b6vKH93yC:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L149)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If we return the dictionary from this method call, then we know that it will never be null.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 151 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NPDdMD-E_ZGjP7teC:-O8cmtV26KAzRfu7QtvT:bu2q0tw) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L151)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should check if the queue name exists in the dictionary. If not, we should try repopulating the dictionary.
</blockquote></details>

Done. Do we want to throw an exception if it's still not in there after repopulating?
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 160 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NQFZ17IC69oL1NCYu:-O8cmzaI7pi49GpJZOHK:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L160)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should synchronize access to `_queueNamesToIds`, since it is a mutable field in a singleton service.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 182 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NMyz4EwZ7vXx1ZgMQ:-O8cn2Gw-8W_AjpF2b_T:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L182)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should convert `ids` to an array before performing this check. Generally, you want to avoid iterating over an `IEnumerable` multiple times.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 149 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NOvuNCHzFTn9HiPHb:-O8gkmbV3qfdyOahN55p:b-u8hlsg) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L149)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If `_queueNamesToIds` is no longer nullable, then we don't need to return it from `PopulateQueueNamesToIdsAsync` anymore.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 151 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NPDdMD-E_ZGjP7teC:-O8ghyF77k7HvY27VrxU:b-bz6jnu) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L151)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done. Do we want to throw an exception if it's still not in there after repopulating?
</blockquote></details>

Yes, we should throw if it is still not there after repopulating.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs` line 160 at r2](https://reviewable.io/reviews/sillsdev/serval/504#-O8NQFZ17IC69oL1NCYu:-O8giFDp0YzDJ8ieCGNz:b8v5n8z) ([raw file](https://github.com/sillsdev/serval/blob/b69baa8fd5b855982dd678d7b9980e850f5b3e13/src/Machine/src/Serval.Machine.Shared/Services/ClearMLService.cs#L160)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This code could result in the case where `_queueNamesToIds` contains queues that no longer exist. If we use an `AsyncLock` coupled with an `ImmutableDictionary`, then the code should be thread-safe.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504#-:-O8h6gY05yfTh2HDERHY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504#-:-O8h9qxG1fcE1oz0ull4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
