### PR TITLE
Add build log

### PR DESCRIPTION
**Pull request by johnml1135**
This is to support https://github.com/sillsdev/machine/issues/152, logging builds in Loki for metrics and aggregation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/263)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/263)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 242 at r1](https://reviewable.io/reviews/sillsdev/serval/263#-NnPRO6a9cGPrDNyJETM:-NnPRO6a9cGPrDNyJETN:bs593j6) ([raw file](https://github.com/sillsdev/serval/blob/ae9ce85f3b74e17f7f192c3ef79d72be06d0195a/src/Serval.Translation/Services/EngineService.cs#L242)):*
> ```Smalltalk
>                     buildRequestSummary.Add("Options", JsonNode.Parse(request.Options));
>                 }
>                 catch (Exception)
> ```

This should be `JsonException`.
___
*[`src/Serval.Translation/Services/EngineService.cs` line 251 at r1](https://reviewable.io/reviews/sillsdev/serval/263#-NnPS3hmCAzBah3M39AD:-NnPS3hmCAzBah3M39AE:be6ybu7) ([raw file](https://github.com/sillsdev/serval/blob/ae9ce85f3b74e17f7f192c3ef79d72be06d0195a/src/Serval.Translation/Services/EngineService.cs#L251)):*
> ```Smalltalk
>                 // get the number of previous builds for the engine
>                 int numPreviousBuilds =
>                     (await _builds.GetAllAsync(b => b.EngineRef == engine.Id, cancellationToken)).Count - 1;
> ```

This Mongo query could become inefficient in some cases. It might be useful to add a `CountAsync` method to the `IRepository` interface. I don't know if we need to do that right now, but it would make this query much more efficient.
___
*[`src/Serval.Translation/Services/EngineService.cs` line 256 at r1](https://reviewable.io/reviews/sillsdev/serval/263#-NnPRZLp5Pk_hZ2QvRLK:-NnPRZLp5Pk_hZ2QvRLL:bs593j6) ([raw file](https://github.com/sillsdev/serval/blob/ae9ce85f3b74e17f7f192c3ef79d72be06d0195a/src/Serval.Translation/Services/EngineService.cs#L256)):*
> ```Smalltalk
>                 _logger.LogInformation("{request}", buildRequestSummary.ToJsonString());
>             }
>             catch (Exception)
> ```

This should be `JsonException`.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/EngineService.cs` line 251 at r1](https://reviewable.io/reviews/sillsdev/serval/263#-NnPS3hmCAzBah3M39AD:-NnQ5nh1BiVJNDRBGv9e:bnlamz5) ([raw file](https://github.com/sillsdev/serval/blob/ae9ce85f3b74e17f7f192c3ef79d72be06d0195a/src/Serval.Translation/Services/EngineService.cs#L251)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This Mongo query could become inefficient in some cases. It might be useful to add a `CountAsync` method to the `IRepository` interface. I don't know if we need to do that right now, but it would make this query much more efficient.
</blockquote></details>

resolved.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/EngineService.cs` line 256 at r1](https://reviewable.io/reviews/sillsdev/serval/263#-NnPRZLp5Pk_hZ2QvRLK:-NnQ5uVEE3rJ851CuLx5:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ae9ce85f3b74e17f7f192c3ef79d72be06d0195a/src/Serval.Translation/Services/EngineService.cs#L256)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `JsonException`.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/EngineService.cs` line 242 at r1](https://reviewable.io/reviews/sillsdev/serval/263#-NnPRO6a9cGPrDNyJETM:-NnQ5mfqDvhkcicw2Vzd:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ae9ce85f3b74e17f7f192c3ef79d72be06d0195a/src/Serval.Translation/Services/EngineService.cs#L242)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `JsonException`.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/263#-:-NnQMhar8-MN_8kKcPYJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
