### PR TITLE
Create script to pull all Paratext projects for testing

### PR DESCRIPTION
**Pull request by Enkidu93**
Addresses https://github.com/sillsdev/serval/issues/429

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/432)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`scripts/pull_all_usfm.py` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/432#-O1wcY9Y3_YcrprWoTib:-O1wcY9Y3_YcrprWoTic:byx76dq) ([raw file](https://github.com/sillsdev/serval/blob/7415e8d00a6fa694ed7f57764aae4a2d24ccf136/scripts/pull_all_usfm.py#L40)):*
> ```Python
>         try:
>             file_data = client.data_files_download(file.id)
>             with open(output_dir / file.name, "wb") as f:
> ```

files may have the same name, but you don't know if they are the same file or not.  There probably is a magical way for accounting for this, such as, if the files are the same size, just ignore the new file, but if they have a different size, create a new file with a different name, etc.

**Comment by johnml1135** [comment]
*[`scripts/pull_all_usfm.py` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/432#-O1wcY9Y3_YcrprWoTib:-O1wcpwqBYgPXttqKwXA:be4mz7e) ([raw file](https://github.com/sillsdev/serval/blob/7415e8d00a6fa694ed7f57764aae4a2d24ccf136/scripts/pull_all_usfm.py#L40)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

files may have the same name, but you don't know if they are the same file or not.  There probably is a magical way for accounting for this, such as, if the files are the same size, just ignore the new file, but if they have a different size, create a new file with a different name, etc.
</blockquote></details>

I am afraid of 500 files being named Paratext.zip ...

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/432)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`scripts/pull_all_usfm.py` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/432#-O1wcY9Y3_YcrprWoTib:-O1wfpgZ1vxN3jEJt-hG:bx5789m) ([raw file](https://github.com/sillsdev/serval/blob/7415e8d00a6fa694ed7f57764aae4a2d24ccf136/scripts/pull_all_usfm.py#L40)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I am afraid of 500 files being named Paratext.zip ...
</blockquote></details>

That's a good catch. I think the SF procedure uses unique ids, so it shouldn't matter, but better to generalize it. Done: I did `<name>_<id>` in order to preserve alphabetic ordering and readability.

**Comment by johnml1135** [comment]
*[`scripts/pull_all_usfm.py` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/432#-O1wcY9Y3_YcrprWoTib:-O1wsGRvAtr9rVT-MSMK:bfpvlvl) ([raw file](https://github.com/sillsdev/serval/blob/7415e8d00a6fa694ed7f57764aae4a2d24ccf136/scripts/pull_all_usfm.py#L40)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

That's a good catch. I think the SF procedure uses unique ids, so it shouldn't matter, but better to generalize it. Done: I did `<name>_<id>` in order to preserve alphabetic ordering and readability.
</blockquote></details>

Will the files still be usable by the machine "parse everything" script?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/432)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/432)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`scripts/pull_all_usfm.py` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/432#-O1wcY9Y3_YcrprWoTib:-O1wsdMg1T5TvVxPRnzM:bwpkdlc) ([raw file](https://github.com/sillsdev/serval/blob/7415e8d00a6fa694ed7f57764aae4a2d24ccf136/scripts/pull_all_usfm.py#L40)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Will the files still be usable by the machine "parse everything" script?
</blockquote></details>

Yep, it doesn't care what they're named.

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/432)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
