### PR TITLE
A better fix for #516.

### PR DESCRIPTION
**Pull request by johnml1135**
#516 - this should be applied independently for pretranslate and trainOn.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/521)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 632 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ2zrk8l43JN_L8qDP:-OAJ2zrk8l43JN_L8qDQ:bdifddg) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/src/Serval.Translation/Services/EngineService.cs#L632)):*
> ```Smalltalk
>         TrainingCorpus? trainingCorpus,
>         PretranslateCorpus? pretranslateCorpus,
>         bool noTrainingCorpusDefined,
> ```

Could we rename these parameters to `trainOnAll` and `pretranslateAll` (or `trainOnAllCorpora` and `pretranslateAllCorpora`)? That helps the readability of the code.

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
Thanks, John! I'm fine with this as long as it's the behavior we want. It depends on how interdependent you'd like `trainOn` and `pretranslate` to be and what kinds of filters you want to make easier to compose and which more difficult - i.e., something is implicit now which wasn't implicit before and something would have to be made explicit which was previously implicit. 

I apologize if I did this logic last week differently than you expected; I thought you were expecting it to work differently. This underscores the issue I've mentioned before which is that we need to have a clearer definition of intended behavior across all filtering arrangements. There are so many fields that can be null, empty, or set or situations in which corpora can specified multiple times in different places. It might be good to work on a document to describe this more fully & then make sure our tests cover that.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521#-:-OAJ8O1Q1e1sqr0wr3k8:b-a9z706)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ87sDC-OGttfWGpUz:-OAJ87sDC-OGttfWGpV-:b-prbcog) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs#L470)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task StartBuildAsync_OneEachOfMultipleCorpora()
> ```

There's already a test named `StartBuildAsync_ParallelCorpus_OneOfMultipleCorpora`, I believe. I think a more descriptive name for each of them is in order to differentiate the two (or merge them into one).

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 632 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ2zrk8l43JN_L8qDP:-OAJKfof41J9JQ0SfGh-:bnt9ilo) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/src/Serval.Translation/Services/EngineService.cs#L632)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Could we rename these parameters to `trainOnAll` and `pretranslateAll` (or `trainOnAllCorpora` and `pretranslateAllCorpora`)? That helps the readability of the code.
</blockquote></details>

How about noTrainingFilter and noPretranslationFilter?  That allowed the logic that it is used within to be clearer - either there is "noTrainingFilter" or "the source filter is null" .  It is used to combine the logic for when to "trainOnAll."

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 632 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ2zrk8l43JN_L8qDP:-OAJLR4h3ztxJhXRI4GH:bgsc7ox) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/src/Serval.Translation/Services/EngineService.cs#L632)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

How about noTrainingFilter and noPretranslationFilter?  That allowed the logic that it is used within to be clearer - either there is "noTrainingFilter" or "the source filter is null" .  It is used to combine the logic for when to "trainOnAll."
</blockquote></details>

or "noTrainingCorpusFilter".

**Comment by johnml1135** [comment]
*[`src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ87sDC-OGttfWGpUz:-OAJLqydASFUVWr3AmCN:b-xp72c3) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs#L470)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

There's already a test named `StartBuildAsync_ParallelCorpus_OneOfMultipleCorpora`, I believe. I think a more descriptive name for each of them is in order to differentiate the two (or merge them into one).
</blockquote></details>

TrainOnOnePretranslateOnTheOther

**Comment by johnml1135** [comment]
Updated documentation.

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
Where?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521#-:-OAJR5CjCqdvJeXoAVJD:b-xxcdwj)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ87sDC-OGttfWGpUz:-OAJR9fj2Esyiy8hxxXq:bbadjtc) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs#L470)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

TrainOnOnePretranslateOnTheOther
</blockquote></details>

Or `TrainOnOnePretranslateTheOther`?

**Comment by johnml1135** [comment]
Coming...

**Comment by johnml1135** [comment]
Updated.

**Comment by johnml1135** [comment]
*[`src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ87sDC-OGttfWGpUz:-OAJV2Ek4IThs7w-eVWo:bvyb82h) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/test/Serval.Translation.Tests/Services/EngineServiceTests.cs#L470)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Or `TrainOnOnePretranslateTheOther`?
</blockquote></details>

better.

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 994 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANNdw50BZFypXaWH4Q:-OANNdw66RaN4E8_IHv4:bqdfjy6) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L994)):*
> ```Smalltalk
>     /// <remarks>
>     /// Specify the corpora and textIds/scriptureRanges within those corpora to train on. Only one type of corpus may be used: either (legacy) corpora (see /translation/engines/{id}/corpora) or parallel corpora (see /translation/engines/{id}/parallel-corpora).
>     /// A (legacy) corpus is selected by specifying CorpusId and a parallel corpus is selected for training by specifying the appropriate CorpusId in SourceFilters or TargetFilters.
> ```

I would make the language consistent across the legacy corpus and the parallel corpus. I'd also mention the fact that the parallel corpus id does need to be specified. Something like: "A (legacy) corpus is selected by specifying CorpusId and a parallel corpus is selected by specifying ParallelCorpusId, A parallel corpus can be further filtered by specifying particular CorpusIds in SourceFilters or TargetFilters"
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 998 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANPOXc8GYd14JV5ogh:-OANPOXc8GYd14JV5ogi:b96hiqi) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L998)):*
> ```Smalltalk
>     /// Filters can also be supplied via scriptureRange parameter as ranges of biblical text. See [here](https://github.com/sillsdev/serval/wiki/Filtering-Paratext-Project-Data-with-a-Scripture-Range)
>     /// All Paratext project filtering follows original versification. See [here](https://github.com/sillsdev/serval/wiki/Versification-in-Serval) for more information.
>     /// If `trainOn` or `pretranslate` is not provided, all corpora will be used for the respective task.
> ```

It might be more clear to say  "...provided, all corpora will be used for training or pretranslation respectively", but this is fine too
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 999 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANQ2w33syAh1emLJxc:-OANQ2w33syAh1emLJxd:b4kcxe8) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L999)):*
> ```Smalltalk
>     /// All Paratext project filtering follows original versification. See [here](https://github.com/sillsdev/serval/wiki/Versification-in-Serval) for more information.
>     /// If `trainOn` or `pretranslate` is not provided, all corpora will be used for the respective task.
>     /// If a corpus is selected for training or pretranslation and neither scriptureRange or textIds are defined, all of the selected corpus will be used.
> ```

Not necessary but I'd suggest: "...neither...nor..."
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1001 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANQJgy55dyhhh4IFmg:-OANQJgy55dyhhh4IFmh:b1ikwht) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1001)):*
> ```Smalltalk
>     /// If a corpus is selected for training or pretranslation and neither scriptureRange or textIds are defined, all of the selected corpus will be used.
>     /// If a corpus is selected for training or pretranslation and an empty scriptureRange or textIds is defined, none of the selected corpus will be used.
>     /// If a corpus is selected for training or pretranslation, all corpora that are not selected will not be used for the respective task.
> ```

I might further qualify it; something like: "If a corpus is selected for training or pretranslation but no further filters are provided, all selected corpora will be used for training or pretranslation respectively"

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 994 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANNdw50BZFypXaWH4Q:-OANWaM26IRRLVz9JtWp:b-bw8e14) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L994)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I would make the language consistent across the legacy corpus and the parallel corpus. I'd also mention the fact that the parallel corpus id does need to be specified. Something like: "A (legacy) corpus is selected by specifying CorpusId and a parallel corpus is selected by specifying ParallelCorpusId, A parallel corpus can be further filtered by specifying particular CorpusIds in SourceFilters or TargetFilters"
</blockquote></details>

Updated.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 998 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANPOXc8GYd14JV5ogh:-OANWqGw3tCwvdjKEz3b:bvnrpcm) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L998)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

It might be more clear to say  "...provided, all corpora will be used for training or pretranslation respectively", but this is fine too
</blockquote></details>

updated

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 999 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANQ2w33syAh1emLJxc:-OANWy7NEuC35vBBV5qg:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L999)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Not necessary but I'd suggest: "...neither...nor..."
</blockquote></details>

done

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1001 at r2](https://reviewable.io/reviews/sillsdev/serval/521#-OANQJgy55dyhhh4IFmg:-OANXvhpAh6Qsl9CkJ59:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/c905b174fa7d479ae06f7a731c6d91e99a6fd60c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1001)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I might further qualify it; something like: "If a corpus is selected for training or pretranslation but no further filters are provided, all selected corpora will be used for training or pretranslation respectively"
</blockquote></details>

Done.

**Review by Enkidu93 — APPROVED** [review]
I'd still like to see Damien's approval too, but it looks good to me. Thank you for doing this, John!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521#-:-OANmp9f4yUSF85NWdA6:b-rpj4qs)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

**Review by ddaspit — CHANGES_REQUESTED** [review]
Peter asked us to mark the deprecated endpoints and properties. Should we do that in this PR or a separate PR? We just need to add the `Obsolete` attribute to the appropriate controller methods and DTO properties.

> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521#-:-OANnWcwAKXZDhHCQBCl:b-6kj2ad)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 632 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ2zrk8l43JN_L8qDP:-OANiy3eCXla-44acK-_:b-m27qfi) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/src/Serval.Translation/Services/EngineService.cs#L632)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

or "noTrainingCorpusFilter".
</blockquote></details>

Although `noTrainingCorpusFilter` and `noPretranslateCorpusFilter` accurately describe the state of the data model, I would prefer to use names that represent what those states actually mean. When no training corpora is defined, it means that we want to train on all corpora. This makes the code clearer and more readable.

**Review by Enkidu93 — APPROVED** [review]
I attempted to do that in my original mixed source PR, and it yelled at me, so it might be more complicated than it seems and worth separating into a different PR.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521#-:-OANodqyEqXhGyEespwv:bkojw8)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

**Comment by johnml1135** [comment]
I agree, let's make it a separate PR.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 632 at r1](https://reviewable.io/reviews/sillsdev/serval/521#-OAJ2zrk8l43JN_L8qDP:-OANpGQVE5samhv6vyqI:bi6sv3w) ([raw file](https://github.com/sillsdev/serval/blob/b270eb5dae8e68b3e6da3c326a0dff397b1c0570/src/Serval/src/Serval.Translation/Services/EngineService.cs#L632)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Although `noTrainingCorpusFilter` and `noPretranslateCorpusFilter` accurately describe the state of the data model, I would prefer to use names that represent what those states actually mean. When no training corpora is defined, it means that we want to train on all corpora. This makes the code clearer and more readable.
</blockquote></details>

Updated naming.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/521#-:-OANvTTo0Lnqu9yT0Cn0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Pull request merged**
