### PR TITLE
Build options is an arbitrary json object rather than a string

### LINKED ISSUE #180: The build options passed to the start build endpoint should be arbitrary JSON
Currently, the build options in `TranslationBuildConfigDto` is a string. This should hold arbitrary JSON and not a string.

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes #180. I've verified that arbitrary JSON can be passed without error and parsed properly. It can also continue to be passed as a string.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/183)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
You forgot to update the `Options` property on `TranslationBuildDto`.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/183#-:-NgtGEzN6QqgZ2LxVvLI:b67pffg)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/183#-NgtF9CO0JRaI_0ZZlMD:-NgtF9CO0JRaI_0ZZlME:b-7buzi0) ([raw file](https://github.com/sillsdev/serval/blob/2cadf9dd2148b1c7ee778fdfe5d6ba1e108befa3/src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs#L8)):*
> ```Smalltalk
>     public IList<PretranslateCorpusConfigDto>? Pretranslate { get; set; }
> 
>     public object? Options { get; set; }
> ```

The Swagger docs show an invalid example for this property. Specifically, it shows a string value, which will result in a 400 status code. We should specify a valid example using code documentation. For example:
```
/// <example>
/// {
///   "property": "value"
/// }
/// </example>
```

**Comment by Enkidu93** [comment]
I had intentionally not done that, but I suppose there's no good reason not to. It would make the presentation cleaner and more consistent to the user when they request an existing builds information.

**Review by ddaspit — COMMENTED** [review]
Yeah, we want it to be consistent.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/183#-:-NgtI9qTBex4E52lAf6J:bvgfdeh)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/183#-NgtF9CO0JRaI_0ZZlMD:-NgtHaaPAFE84D4xKACo:b-pu8uqn) ([raw file](https://github.com/sillsdev/serval/blob/2cadf9dd2148b1c7ee778fdfe5d6ba1e108befa3/src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The Swagger docs show an invalid example for this property. Specifically, it shows a string value, which will result in a 400 status code. We should specify a valid example using code documentation. For example:
```
/// <example>
/// {
///   "property": "value"
/// }
/// </example>
```
</blockquote></details>

OK, good call: I wasn't familiar with how to do that properly, but I wondered the same thing.

**Review by Enkidu93 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/183#-:-NgtKJZy0LlcOmqWxIBX:b-896fix)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/183#-NgtF9CO0JRaI_0ZZlMD:-NgtKMzOCplLWthSqXyV:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2cadf9dd2148b1c7ee778fdfe5d6ba1e108befa3/src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs#L8)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, good call: I wasn't familiar with how to do that properly, but I wondered the same thing.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/183)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationBuildDto.cs` line 22 at r2](https://reviewable.io/reviews/sillsdev/serval/183#-NgtTkpICIaUyNultX1u:-NgtTkpICIaUyNultX1v:b-ylvmp5) ([raw file](https://github.com/sillsdev/serval/blob/bac3f570bee3dd25b1febe77c047a8541d8e9021/src/Serval.Translation/Contracts/TranslationBuildDto.cs#L22)):*
> ```Smalltalk
>     public JobState State { get; set; }
>     public DateTime? DateFinished { get; set; }
>     public object? Options { get; set; }
> ```

You should add the example here as well.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/183#-:-Ngto28yDVeF7f0vFK0v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
