### PR TITLE
Integration testing

### PR DESCRIPTION
**Pull request by johnml1135**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/38)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`.github/workflows/ci.yml` line 35 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-NalW6qM6Tg3rNND5aDO:-NalW6qM6Tg3rNND5aDP:b5zt750) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/.github/workflows/ci.yml#L35)):*
> ```YAML
>         run: sudo mkdir -p /var/lib/serval && sudo chmod 777 /var/lib/serval
>       - name: Test
>         run: dotnet test --no-build --verbosity normal --filter "TestCategory=Integration" -c Release
> ```

I am assuming that we should run all tests - including unit tests - and E2E tests with docker-compose.  How is this done here?

**Comment by johnml1135** [comment]
*[`.github/workflows/missing-services-e2e-tests.yml` line 3 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-NalXIRF5Lvr_sBbjwC9:-NalXIRF5Lvr_sBbjwCA:b-zawiuc) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/.github/workflows/missing-services-e2e-tests.yml#L3)):*
> ```YAML
> name: "Missing services E2E tests"
> 
> on:
> ```

This file looks like it was for debugging and can be deleted now.  Is that correct?

**Comment by Enkidu93** [comment]
> _[`.github/workflows/ci.yml` line 35 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-NalW6qM6Tg3rNND5aDO:-NalW6qM6Tg3rNND5aDP:b5zt750) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/.github/workflows/ci.yml#L35)):_
> 
> > ```yaml
> >         run: sudo mkdir -p /var/lib/serval && sudo chmod 777 /var/lib/serval
> >       - name: Test
> >         run: dotnet test --no-build --verbosity normal --filter "TestCategory=Integration" -c Release
> > ```
> 
> I am assuming that we should run all tests - including unit tests - and E2E tests with docker-compose. How is this done here?

The E2E tests are run in a separate workflow - ci-e2e.yml - but yes, I do need to change the filters so the unit tests will run. I changed it to accommodate the missing services E2E tests which are also E2E tests.

**Comment by johnml1135** [comment]
*[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 20 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-Nam15A29mDgFyF6jHzH:-Nam15A29mDgFyF6jHzI:b-w7olew) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L20)):*
> ```Smalltalk
>             _logger.Log(
>                 LogLevel.Error,
>                 "A user tried to accesss an unavailable service. See health-check logs for more details."
> ```

access - not accesss

**Comment by johnml1135** [comment]
*[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-Nam1xGp9V5bYdURyp7e:-Nam1xGp9V5bYdURyp7f:bo8zeef) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L16)):*
> ```Smalltalk
>     public override void OnException(ExceptionContext context)
>     {
>         if (context.Exception is System.TimeoutException or Grpc.Core.RpcException)
> ```

Why these two exceptions?  Instead, could there be a try/catch around connecting to grpc and then throw a custom exception?  I am concerned that other things that are not ServiceUnavailable could actually trigger this, such as a locked process, etc.

**Comment by Enkidu93** [comment]
> _[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-Nam1xGp9V5bYdURyp7e:-Nam1xGp9V5bYdURyp7f:bo8zeef) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L16)):_
> 
> > ```smalltalk
> >     public override void OnException(ExceptionContext context)
> >     {
> >         if (context.Exception is System.TimeoutException or Grpc.Core.RpcException)
> > ```
> 
> Why these two exceptions? Instead, could there be a try/catch around connecting to grpc and then throw a custom exception? I am concerned that other things that are not ServiceUnavailable could actually trigger this, such as a locked process, etc.

I added some logic (mimicking what we have elsewhere in the NotSupportedExceptionFilter) to verify that it is the 'Unavailable' gRPC error specifically. As for the System.Timeout, I can't say precisely if another service might cause an issue. Partly, I chose this strategy because there were many places (as I recall) that the service could could disappear and cause a function to throw this error - and honestly, I'm not sure how you'd even identify all of those possible places because of the extremely accurate timing that would be needed to test a failure throughout the pipeline across the entire service. On the flip side, as you say, it's difficult to know what other functions might throw this same exception under some circumstances. I am comforted that all tests are passing which means that, minimally, under normal conditions, this filter does not unintentionally intercept any exceptions that would cause a malfunction in the code. But I may be misremembering the amount of effort that would be required to address this properly, and I'm happy to re-devote time to a deeper dive here if you'd like! It would certainly be cleaner if a custom exception were thrown.

**Comment by johnml1135** [comment]
*[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-Nam1xGp9V5bYdURyp7e:-NaqHomE8ujGqzbWA2Th:b1rnc7o) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L16)):*
<details><summary><i>Previously, Enkidu93 wrote…</i></summary><blockquote>

I added some logic (mimicking what we have elsewhere in the NotSupportedExceptionFilter) to verify that it is the 'Unavailable' gRPC error specifically. As for the System.Timeout, I can't say precisely if another service might cause an issue. Partly, I chose this strategy because there were many places (as I recall) that the service could could disappear and cause a function to throw this error - and honestly, I'm not sure how you'd even identify all of those possible places because of the extremely accurate timing that would be needed to test a failure throughout the pipeline across the entire service. On the flip side, as you say, it's difficult to know what other functions might throw this same exception under some circumstances. I am comforted that all tests are passing which means that, minimally, under normal conditions, this filter does not unintentionally intercept any exceptions that would cause a malfunction in the code. But I may be misremembering the amount of effort that would be required to address this properly, and I'm happy to re-devote time to a deeper dive here if you'd like! It would certainly be cleaner if a custom exception were thrown. 
</blockquote></details>

Let's at least log the exception too.  That would help us debug the logs better.

**Comment by johnml1135** [comment]
*[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 20 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-Nam15A29mDgFyF6jHzH:-NaqIM5c5gUDVF6QyIHX:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L20)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

access - not accesss
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`.github/workflows/ci.yml` line 35 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-NalW6qM6Tg3rNND5aDO:-NaqLPT0ALiHyqOHWBSx:b34uwz4) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/.github/workflows/ci.yml#L35)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I'll make a "Unit" test category.
</blockquote></details>

Your change is better.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 143 at r6](https://reviewable.io/reviews/sillsdev/serval/38#-NaqJ0Y0-JBwQpQkm4ql:-NaqLjNm72efBc8nipHM:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2fa3893dcddef8280ba7985c2ab7e5ed1a17404b/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L143)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Added documentation around this.
</blockquote></details>

Done.

**Comment by Enkidu93** [comment]
> _[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/serval/38#-Nam1xGp9V5bYdURyp7e:-NaqHomE8ujGqzbWA2Th:b1rnc7o) ([raw file](https://github.com/sillsdev/serval/blob/485cf0eac1515ad7e48827952234f80bca7e3876/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L16)):_
> Previously, Enkidu93 wrote…
> 
> Let's at least log the exception too. That would help us debug the logs better.

Would you still like me to make this change? Just directly to main?

**Comment by ddaspit** [comment]
I really wanted to review this PR, since it makes major changes to the design of many components. Please do not merge any more major changes without my review.

**Comment by Enkidu93** [comment]
> I really wanted to review this PR, since it makes major changes to the design of many components. Please do not merge any more major changes without my review.

I'm so sorry, Damien. I didn't mean to step on any toes if I did. Hope you've settled in well! Please do criticize retrospectively.

**Review by ddaspit — COMMENTED** [review]
No problem. I know I haven't been very available.

> Reviewed 31 of 43 files at r1, 5 of 16 files at r2, 34 of 38 files at r3, 7 of 13 files at r4, 3 of 6 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/38#-:-NawXNEw1EmopcwDpcVH:bly6l2e)* status: all files reviewed, 9 unresolved discussions

___
*[`src/Serval.Client/ServalClientHelper.cs` line 108 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawQCN95fjHdx6IyqRq:-NawQCN95fjHdx6IyqRr:b4u2op4) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Client/ServalClientHelper.cs#L108)):*
> ```Smalltalk
>     }
> 
>     public async Task<string> PostTextCorpusToEngine(
> ```

This method name should be more readable and not include implementation details, such as the HTTP method used.
___
*[`src/Serval.Client/ServalClientHelper.cs` line 160 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawQQOV-Q1jB5VzCL1v:-NawQQOV-Q1jB5VzCL1w:b4u2op4) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Client/ServalClientHelper.cs#L160)):*
> ```Smalltalk
>     }
> 
>     public async Task<List<DataFile>> PostFiles(IEnumerable<string> filesToAdd, FileFormat fileFormat, string language)
> ```

This method name should be more readable and not include implementation details, such as the HTTP method used.
___
*[`src/Serval.DataFiles/Models/DataFile.cs` line 5 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawQYjg0QpQRiln-kTv:-NawQYjg0QpQRiln-kTw:b-l9zd2d) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.DataFiles/Models/DataFile.cs#L5)):*
> ```Smalltalk
> public class DataFile : IOwnedEntity
> {
>     [BsonId]
> ```

This is a leaky encapsulation and ties the entities to a particular implementation. These attributes should be applied using a [convention](https://mongodb.github.io/mongo-csharp-driver/2.11/apidocs/html/T_MongoDB_Bson_Serialization_Conventions_StringIdStoredAsObjectIdConvention.htm).
___
*[`src/Serval.Shared/Utils/AutoToString.cs` line 3 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawXIfA-oSVV1Z6rLP2:-NawXIfA-oSVV1Z6rLP3:b5sc13u) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Shared/Utils/AutoToString.cs#L3)):*
> ```Smalltalk
> namespace Serval.Shared.Utils;
> 
> public static class AutoToString
> ```

Is this class used anywhere?
___
*[`src/Serval.Translation/Services/EngineService.cs` line 285 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawSLOK5LlvsUUZpPqQ:-NawSLOK5LlvsUUZpPqR:b7i2tvo) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Translation/Services/EngineService.cs#L285)):*
> ```Smalltalk
>             && original_engine.Corpora is not null
>             && original_engine.Corpora
>                 .FindAll(c =>
> ```

The `Any()` method would be more appropriate and efficient.
___
*[`src/SIL.DataAccess/IRepository.cs` line 15 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawT5af-Z-FBd4iouV2:-NawT5af-Z-FBd4iouV3:bfjd0h9) ([raw file](https://github.com/sillsdev/serval/blob/981cf06589ebd035f3b4000d32bdafbe16fc38de/src/SIL.DataAccess/IRepository.cs#L15)):*
> ```Smalltalk
>         Expression<Func<T, bool>> filter,
>         Action<IUpdateBuilder<T>> update,
>         bool upsert = false,
> ```

Why did you remove the ability to upsert?
___
*[`src/SIL.DataAccess/IServiceCollectionExtensions.cs` line 35 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawTBvc6l5W-zqniB4S:-NawTBvc6l5W-zqniB4T:bdhf0e) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/SIL.DataAccess/IServiceCollectionExtensions.cs#L35)):*
> ```Smalltalk
>         services.AddTransient<SIL.DataAccess.IIdGenerator, ObjectIdGenerator>();
>         var clientSettings = MongoClientSettings.FromConnectionString(connectionString);
>         clientSettings.LinqProvider = LinqProvider.V2;
> ```

Why was this necessary?
___
*[`src/SIL.DataAccess/MemoryRepository.cs` line 120 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawTsv_3K4hDgXDx9H3:-NawTsv_3K4hDgXDx9H4:b-ldhelw) ([raw file](https://github.com/sillsdev/serval/blob/981cf06589ebd035f3b4000d32bdafbe16fc38de/src/SIL.DataAccess/MemoryRepository.cs#L120)):*
> ```Smalltalk
>         entity.Revision = 1;
>         if (string.IsNullOrEmpty(entity.Id))
>             entity.Id = ObjectId.GenerateNewId().ToString();
> ```

Why was this behavior removed? This diverges the behavior from the MongoRepository implementation.
___
*[`src/SIL.DataAccess/MongoRepository.cs` line 224 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawUSyL711dNqIHys5D:-NawUSyL711dNqIHys5E:bqr0yzq) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/SIL.DataAccess/MongoRepository.cs#L224)):*
> ```Smalltalk
>     }
> 
>     private async Task<TR> TryCatchDuplicate<TR>(Func<Task<TR>> func)
> ```

`Action` would be appropriate, since we never need to return anything when we use this function.

**Comment by Enkidu93** [comment]
> _[`src/Serval.Shared/Utils/AutoToString.cs` line 3 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawXIfA-oSVV1Z6rLP2:-NawXIfA-oSVV1Z6rLP3:b5sc13u) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Shared/Utils/AutoToString.cs#L3)):_
> 
> > ```smalltalk
> > namespace Serval.Shared.Utils;
> > 
> > public static class AutoToString
> > ```
> 
> Is this class used anywhere?

Yes, it is - only a couple times in the tests though in error messages. As in Machine, I was mainly using it for debugging because none of the classes had ToString() methods. I can remove it if you'd prefer and do something more tailored in those particular error messages. I'm sure I'll use it again, but I can always reinject it as needed or just tell git to ignore it.

I think the other questions you mentioned regard John's code.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/38)* status: all files reviewed, 9 unresolved discussions

___
*[`src/Serval.Shared/Utils/AutoToString.cs` line 3 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawXIfA-oSVV1Z6rLP2:-NawaOnE1Kd-GD8X0xLl:b-fqpydd) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Shared/Utils/AutoToString.cs#L3)):*
<details><summary><i>Previously, Enkidu93 wrote…</i></summary><blockquote>

Yes, it is - only a couple times in the tests though in error messages. As in Machine, I was mainly using it for debugging because none of the classes had ToString() methods. I can remove it if you'd prefer and do something more tailored in those particular error messages. I'm sure I'll use it again, but I can always reinject it as needed or just tell git to ignore it.

I think the other questions you mentioned regard John's code.

</blockquote></details>

I would rather not have debugging code checked in to the repo, especially code that is this complicated.

**Comment by johnml1135** [comment]
*[`src/Serval.Client/ServalClientHelper.cs` line 108 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawQCN95fjHdx6IyqRq:-Nb0sbGD2IQ8dBiNfxvb:b-o9p8dc) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Client/ServalClientHelper.cs#L108)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This method name should be more readable and not include implementation details, such as the HTTP method used.
</blockquote></details>

AddTextCorpusToEngine.

**Comment by johnml1135** [comment]
*[`src/Serval.Client/ServalClientHelper.cs` line 160 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawQQOV-Q1jB5VzCL1v:-Nb0sofbDDW1PMwUIqg0:b-2n6x5v) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.Client/ServalClientHelper.cs#L160)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This method name should be more readable and not include implementation details, such as the HTTP method used.
</blockquote></details>

UploadFiles.

**Comment by johnml1135** [comment]
*[`src/Serval.DataFiles/Models/DataFile.cs` line 5 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawQYjg0QpQRiln-kTv:-Nb0tTcb6wYFsQkZPqM9:b-mwl54z) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.DataFiles/Models/DataFile.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is a leaky encapsulation and ties the entities to a particular implementation. These attributes should be applied using a [convention](https://mongodb.github.io/mongo-csharp-driver/2.11/apidocs/html/T_MongoDB_Bson_Serialization_Conventions_StringIdStoredAsObjectIdConvention.htm).
</blockquote></details>

https://github.com/sillsdev/serval/issues/42 - and https://stackoverflow.com/questions/38871416/difference-between-decorating-a-property-in-c-sharp-with-bsonrepresentationbson.

These were to address specific issues in the casting of different string comparisons to not work correctly.  Specifically the filtering by ID was working incorrectly.  This also was addressed by using LinqProvider.V2.

**Comment by johnml1135** [comment]
*[`src/SIL.DataAccess/IRepository.cs` line 15 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawT5af-Z-FBd4iouV2:-Nb0vfGq2OeNEROMmZmu:b-l43f9s) ([raw file](https://github.com/sillsdev/serval/blob/981cf06589ebd035f3b4000d32bdafbe16fc38de/src/SIL.DataAccess/IRepository.cs#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why did you remove the ability to upsert?
</blockquote></details>

It was causing numerous errors - related to: https://github.com/sillsdev/serval/issues/36

**Comment by johnml1135** [comment]
*[`src/SIL.DataAccess/IServiceCollectionExtensions.cs` line 35 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawTBvc6l5W-zqniB4S:-Nb0vyKiAiR4aKy5E91C:b-akxzfj) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/SIL.DataAccess/IServiceCollectionExtensions.cs#L35)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this necessary?
</blockquote></details>

Because of this: https://github.com/sillsdev/serval/issues/41.  It was the only solution that worked after a lot of debugging.

**Comment by johnml1135** [comment]
*[`src/SIL.DataAccess/MemoryRepository.cs` line 120 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawTsv_3K4hDgXDx9H3:-Nb0wHwN0f_IQP-VvR7i:b-18bcf2) ([raw file](https://github.com/sillsdev/serval/blob/981cf06589ebd035f3b4000d32bdafbe16fc38de/src/SIL.DataAccess/MemoryRepository.cs#L120)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this behavior removed? This diverges the behavior from the MongoRepository implementation.
</blockquote></details>

All Id's are created at the controller level now.  That makes it more consistent and cleaner.  It is related to the upsert issue.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/38)* status: all files reviewed, 6 unresolved discussions

___
*[`src/Serval.DataFiles/Models/DataFile.cs` line 5 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawQYjg0QpQRiln-kTv:-Nb15Z9TBcZoQ2d6KAfj:b2dpc7d) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/Serval.DataFiles/Models/DataFile.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

https://github.com/sillsdev/serval/issues/42 - and https://stackoverflow.com/questions/38871416/difference-between-decorating-a-property-in-c-sharp-with-bsonrepresentationbson.

These were to address specific issues in the casting of different string comparisons to not work correctly.  Specifically the filtering by ID was working incorrectly.  This also was addressed by using LinqProvider.V2. 
</blockquote></details>

Adding these attributes are redundant, since they are already specified by convention. I am guessing that this had nothing to do with the original issue. It was most liking changing the LinqProvider that fixed this issue. I plan on removing these attributes, since they are unnecessary.
___
*[`src/SIL.DataAccess/IRepository.cs` line 15 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawT5af-Z-FBd4iouV2:-Nb15ywv4u5eYNso99LW:br9211r) ([raw file](https://github.com/sillsdev/serval/blob/981cf06589ebd035f3b4000d32bdafbe16fc38de/src/SIL.DataAccess/IRepository.cs#L15)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It was causing numerous errors - related to: https://github.com/sillsdev/serval/issues/36
</blockquote></details>

We don't need to use the upsert functionality for RWLock creation. Upserts are an important operation for document DBs, and since this is intended to be a general-purpose library, I will plan on adding it back in.
___
*[`src/SIL.DataAccess/IServiceCollectionExtensions.cs` line 35 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawTBvc6l5W-zqniB4S:-Nb16M45ESiwiVBf8VQd:b-i85jlk) ([raw file](https://github.com/sillsdev/serval/blob/1a7993966e5509046da8b8f3e79a7e382d6425fb/src/SIL.DataAccess/IServiceCollectionExtensions.cs#L35)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Because of this: https://github.com/sillsdev/serval/issues/41.  It was the only solution that worked after a lot of debugging.
</blockquote></details>

That's fine. I did see various bug reports in the Mongo Driver issue tracker for the LINQ V3 provider.
___
*[`src/SIL.DataAccess/MemoryRepository.cs` line 120 at r7](https://reviewable.io/reviews/sillsdev/serval/38#-NawTsv_3K4hDgXDx9H3:-Nb16ZS_2YcDGnV2ySwb:b8nnjkz) ([raw file](https://github.com/sillsdev/serval/blob/981cf06589ebd035f3b4000d32bdafbe16fc38de/src/SIL.DataAccess/MemoryRepository.cs#L120)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

All Id's are created at the controller level now.  That makes it more consistent and cleaner.  It is related to the upsert issue.
</blockquote></details>

That's fine, but I would still like to keep the behavior the same as the `MongoRepository` class, so it is consistent. I plan on adding this code back in.

**Pull request merged**
