### PR TITLE
Change to MongoDB Callback API for better error handling - #314

### PR DESCRIPTION
**Pull request by johnml1135**
#314 - this should help fix transaction errors the right way.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)

### CODE REVIEW

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/PretranslationService.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvIaGHV9EqGPdvhNMjA:-NvIaGHW4lZH_D3VxkN1:b41eg5i) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/PretranslationService.cs#L62)):*
> ```Smalltalk
>             .Select(p =>
>                 (
>                     (IReadOnlyList<ScriptureRef>)
> ```

Are these changes from a separate PR that have leaked in?
___
*[`src/SIL.DataAccess/MongoDataAccessContext.cs` line 30 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvIeAYsCfCi_msBWKE2:-NvIeAYsCfCi_msBWKE3:b-l9ufgc) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/SIL.DataAccess/MongoDataAccessContext.cs#L30)):*
> ```Smalltalk
>     )
>     {
>         _ = await WithTransactionAsync(
> ```

Why include `_ =`?  I understand the `return new object()`, but why this? Is this avoiding another warning message or is there some kind of disposal magic or something tied to this?

**Review by Enkidu93 — COMMENTED** [review]
Good find! I had trouble finding documentation on this new transaction syntax. The built-in retries could be very helpful!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360#-:-NvIeksg3LT5UNJDGjTL:b-svb6jc)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)* status: all files reviewed, 10 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 188 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXNamuBHKgYwo4W2m_:-NvXNamuBHKgYwo4W2ma:b-ny6g3b) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/EngineService.cs#L188)):*
> ```Smalltalk
>                 await _pretranslations.DeleteAllAsync(pt => pt.EngineRef == engineId, CancellationToken.None);
>             },
>             cancellationToken
> ```

`CancellationToken.None` should be passed here.
___
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 25 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXO2jSAg6k08nKu2qB:-NvXO2jSAg6k08nKu2qC:btrryhu) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L25)):*
> ```Smalltalk
>     public override async Task<Empty> BuildStarted(BuildStartedRequest request, ServerCallContext context)
>     {
>         await _dataAccessContext.WithTransactionAsync(
> ```

You forgot to pass the cancellation token.
___
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXO77wCTb77JQLUUv5:-NvXO77wCTb77JQLUUv6:btrryhu) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L60)):*
> ```Smalltalk
>     public override async Task<Empty> BuildCompleted(BuildCompletedRequest request, ServerCallContext context)
>     {
>         await _dataAccessContext.WithTransactionAsync(
> ```

You forgot to pass the cancellation token.
___
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 112 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXOAex3xPdmRlekUOB:-NvXOAex3xPdmRlekUOC:btrryhu) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L112)):*
> ```Smalltalk
>     public override async Task<Empty> BuildCanceled(BuildCanceledRequest request, ServerCallContext context)
>     {
>         await _dataAccessContext.WithTransactionAsync(
> ```

You forgot to pass the cancellation token.
___
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 160 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXODtd22J8GNtWCCnt:-NvXODtd22J8GNtWCCnu:btrryhu) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L160)):*
> ```Smalltalk
>     public override async Task<Empty> BuildFaulted(BuildFaultedRequest request, ServerCallContext context)
>     {
>         await _dataAccessContext.WithTransactionAsync(
> ```

You forgot to pass the cancellation token.
___
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 208 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXOF0GDgjzXLDO5Sw5:-NvXOF0GDgjzXLDO5Sw6:btrryhu) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L208)):*
> ```Smalltalk
>     public override async Task<Empty> BuildRestarting(BuildRestartingRequest request, ServerCallContext context)
>     {
>         await _dataAccessContext.WithTransactionAsync(
> ```

You forgot to pass the cancellation token.
___
*[`src/SIL.DataAccess/MemoryDataAccessContext.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXOU-52oeHiO6Lz55d:-NvXOU-52oeHiO6Lz55e:b-xxiuam) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/SIL.DataAccess/MemoryDataAccessContext.cs#L10)):*
> ```Smalltalk
>     )
>     {
>         return await callbackAsync(cancellationToken).ConfigureAwait(false);
> ```

You actually don't need to use async/await. You can just pass the task from the `callbackAsync` call.
___
*[`src/SIL.DataAccess/MongoDataAccessContext.cs` line 35 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXMp8L3_yR6O3DLNvy:-NvXMp8L3_yR6O3DLNvz:b-81alpu) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/SIL.DataAccess/MongoDataAccessContext.cs#L35)):*
> ```Smalltalk
>                     await callbackAsync(ct).ConfigureAwait(false);
>                     // Assign dummy value to avoid warning about not returning a value
>                     return new object();
> ```

It would be better to return a boolean here, so you aren't unnecessarily creating an object.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/EngineService.cs` line 188 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXNamuBHKgYwo4W2m_:-NvXpSUZEo2N2OGMsPHB:b-81ehix) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/EngineService.cs#L188)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`CancellationToken.None` should be passed here.
</blockquote></details>

That's fine - but why?

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/PretranslationService.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvIaGHV9EqGPdvhNMjA:-NvXpY_54UVFfhWfc-Ub:boi22c5) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/PretranslationService.cs#L62)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Are these changes from a separate PR that have leaked in?
</blockquote></details>

Nice catch - reverted.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 25 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXO2jSAg6k08nKu2qB:-NvXqSfI1YolUDIuxR9F:b-73m6vj) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to pass the cancellation token.
</blockquote></details>

Nice catch.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXO77wCTb77JQLUUv5:-NvXq_6gAA0JJSGCseY_:b-jg6ewz) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to pass the cancellation token.
</blockquote></details>

nice catch

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 112 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXOAex3xPdmRlekUOB:-NvXrI0-4OBJwrviLCNX:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L112)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to pass the cancellation token.
</blockquote></details>

done

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 160 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXODtd22J8GNtWCCnt:-NvXrzzJCpMrMWjgig2d:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L160)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to pass the cancellation token.
</blockquote></details>

done

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 208 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXOF0GDgjzXLDO5Sw5:-NvXs0bK-LHUFWJS_mWn:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L208)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to pass the cancellation token.
</blockquote></details>

done

**Comment by johnml1135** [comment]
*[`src/SIL.DataAccess/MemoryDataAccessContext.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXOU-52oeHiO6Lz55d:-NvXsOyH0NJZ8bpc5oeu:b-vyhp1b) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/SIL.DataAccess/MemoryDataAccessContext.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You actually don't need to use async/await. You can just pass the task from the `callbackAsync` call.
</blockquote></details>

I think I updated it right...

**Comment by johnml1135** [comment]
*[`src/SIL.DataAccess/MongoDataAccessContext.cs` line 30 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvIeAYsCfCi_msBWKE2:-NvXspGrAP-l8nCE4wxu:bqkycr6) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/SIL.DataAccess/MongoDataAccessContext.cs#L30)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why include `_ =`?  I understand the `return new object()`, but why this? Is this avoiding another warning message or is there some kind of disposal magic or something tied to this?
</blockquote></details>

I updated it to be a bit clearer.

**Comment by johnml1135** [comment]
*[`src/SIL.DataAccess/MongoDataAccessContext.cs` line 35 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXMp8L3_yR6O3DLNvy:-NvXssAI691Yrs683EZ8:bpsr3vd) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/SIL.DataAccess/MongoDataAccessContext.cs#L35)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would be better to return a boolean here, so you aren't unnecessarily creating an object.
</blockquote></details>

return true

**Review by ddaspit — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 188 at r1](https://reviewable.io/reviews/sillsdev/serval/360#-NvXNamuBHKgYwo4W2m_:-NvYVjvXCXqVzbCBFbEx:b-t1jgod) ([raw file](https://github.com/sillsdev/serval/blob/837d2a31a02ca771edb77e39aa609f62efd1f0a9/src/Serval.Translation/Services/EngineService.cs#L188)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

That's fine - but why?
</blockquote></details>

We have already told the engine server to delete the engine, so we want to ignore a cancellation request from the client app to avoid an inconsistent state.
___
*[`src/Serval.Translation/Services/EngineService.cs` line 434 at r2](https://reviewable.io/reviews/sillsdev/serval/360#-NvYWUEO2jcDZOOtpU0-:-NvYWUEO2jcDZOOtpU00:b-4hmar9) ([raw file](https://github.com/sillsdev/serval/blob/a440168697851514f9e1f58ab2ac31a239ee1c74/src/Serval.Translation/Services/EngineService.cs#L434)):*
> ```Smalltalk
>                 await _pretranslations.DeleteAllAsync(pt => pt.CorpusRef == corpusId, ct);
>             },
>             cancellationToken: CancellationToken.None
> ```

We don't want to disable cancellation here.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/EngineService.cs` line 434 at r2](https://reviewable.io/reviews/sillsdev/serval/360#-NvYWUEO2jcDZOOtpU0-:-NvYXYaV4FvwC5_GxHUf:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/a440168697851514f9e1f58ab2ac31a239ee1c74/src/Serval.Translation/Services/EngineService.cs#L434)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't want to disable cancellation here.
</blockquote></details>

done

**Review by ddaspit — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by johnml1135 — COMMENTED** [review]
> Dismissed @Enkidu93 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by Enkidu93 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/360)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
