### PR TITLE
Echo engine endpoint coverage

### PR DESCRIPTION
**Pull request by Enkidu93**
Slightly more detailed Echo documentation as well as added endpoints (train-segment and get-word-graph).  Also, fixed the error checking so that matching target and source languages for echo engines and their corpora is allowed as per Damien's concern.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/Serval.Client/Client.g.cs` line 811 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWBduNCmZK4iCB4Dna:-NbWBduNCmZK4iCB4Dnb:b-rl8o7l) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/src/Serval.Client/Client.g.cs#L811)):*
> ```Smalltalk
>         /// <br/>return empty responses. Endpoints like translate and get-word-graph echo the sent content back to the user
>         /// <br/>in a format that mocks Nmt or Smt. For example, translating a segment "test" with the Echo engine would
>         /// <br/>yield a translation response with translation "test". This engine is useful for debugging and testing purposes.
> ```

We probably should add a comment that Echo engines allow the same language for source and target, unlike other translation engines.  Or inversely, for NMT and SMT engines that the languages need to be different.

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Enkidu93)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 110 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWZDf5Au7O38El4TtQ:-NbWZDf5Au7O38El4TtR:bgqr8xq) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L110)):*
> ```Smalltalk
>                                     string[] targetLines = await File.ReadAllLinesAsync(targetPath, cancellationToken);
>                                     bool isTabSeparated =
>                                         (sourceLines.Length > 0) && (sourceLines[0].Split('\t').Length > 1);
> ```

It would be better to use `Contains()`.
___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 120 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWYrdc7l2gHdiqHHLT:-NbWYrdc7l2gHdiqHHLU:b-t7ssgu) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L120)):*
> ```Smalltalk
>                                         )
>                                         {
>                                             if (sourceLine.Length > 0)
> ```

Pretranslations should only be generated for verses that do not have a target translation.
___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 265 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWZrFv0-NIz9Z_JZCn:-NbWZrFv0-NIz9Z_JZCo:b-ftg1bn) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L265)):*
> ```Smalltalk
>                     Arcs =
>                     {
>                         from index in Enumerable.Range(0, tokens.Length - 1)
> ```

To make the codebase consistent, we do not use the query syntax for LINQ. We always use the functional syntax, i.e. chained function calls.
___
*[`src/Serval.Client/Client.g.cs` line 811 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWBduNCmZK4iCB4Dna:-NbWYPAwE-17bV5r1UKS:b-ncicfw) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/src/Serval.Client/Client.g.cs#L811)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

We probably should add a comment that Echo engines allow the same language for source and target, unlike other translation engines.  Or inversely, for NMT and SMT engines that the languages need to be different.
</blockquote></details>

In fact, the echo engine requires that the source and target language are the same.

**Review by ddaspit — COMMENTED** [review]
In the future, please try to avoid merging the main branch into feature branches. This can make it a lot harder to review the changes. Also, rebasing is preferred, since it results in a more straightforward history.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80#-:-NbWa7eoD3082vdc_TEF:bk6ejxm)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

**Comment by Enkidu93** [comment]
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 120 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWYrdc7l2gHdiqHHLT:-NbZXvjz1CwK-Ng1KGbT:b4uwr5t) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L120)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Pretranslations should only be generated for verses that do not have a target translation.
</blockquote></details>

Is this the behavior of NMT? Notice too that coupled with `targetLine.Length > 0 ? ...", non-empty lines are just getting the targetLine as a pretranslation. The only reason I altered this was because Peter Chapman told me about/showed me output from NMT, and he wanted Echo to be consistent with it: https://github.com/sillsdev/serval/issues/66#issuecomment-1659232561. Let me know.

**Comment by Enkidu93** [comment]
*[`src/Serval.Client/Client.g.cs` line 811 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWBduNCmZK4iCB4Dna:-NbZZ47Q9KxdVkhNcQWh:basams6) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/src/Serval.Client/Client.g.cs#L811)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

In fact, the echo engine requires that the source and target language are the same.
</blockquote></details>

Do you want this to be a "requires" that has the force of a validation check and an error thrown? As it is, I've had to add specific "is it Echo?" checks to get around this rule on the positive (i.e., yes, you may have the same source and target language) side which seems semantically out of place in the Serval code. I'm happy to do so, but if we think that long-term there may be many different kinds of engines with different behaviors, it may be worth rethinking how this is done and maybe make some-kind of engine-specific call to check validity or push the error-checking elsewhere. (I could think of something that's maybe a 'stylistic' translation that translates from one register to another within the same language that would require the same source and target languages...maybe that's a bad example, but you get the point).

**Review by ddaspit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 120 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWYrdc7l2gHdiqHHLT:-NbpEYM0-nF4HXaEaThR:b-8z8bao) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L120)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is this the behavior of NMT? Notice too that coupled with `targetLine.Length > 0 ? ...", non-empty lines are just getting the targetLine as a pretranslation. The only reason I altered this was because Peter Chapman told me about/showed me output from NMT, and he wanted Echo to be consistent with it: https://github.com/sillsdev/serval/issues/66#issuecomment-1659232561. Let me know. 
</blockquote></details>

I checked the NMT code and you are correct. I wasn't aware that the behavior of NMT was changed. It doesn't really make sense to generate a pretranslation for a verse that already has one, so we should change the NMT behavior back to the way it was. Go ahead and revert this back to the original behavior.
___
*[`src/Serval.Client/Client.g.cs` line 811 at r2](https://reviewable.io/reviews/sillsdev/serval/80#-NbWBduNCmZK4iCB4Dna:-NbpFyiZ4r6m65EA-cyS:bxp12an) ([raw file](https://github.com/sillsdev/serval/blob/6609b3bf63874c234b528c4af0039d099c5269a2/src/Serval.Client/Client.g.cs#L811)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Do you want this to be a "requires" that has the force of a validation check and an error thrown? As it is, I've had to add specific "is it Echo?" checks to get around this rule on the positive (i.e., yes, you may have the same source and target language) side which seems semantically out of place in the Serval code. I'm happy to do so, but if we think that long-term there may be many different kinds of engines with different behaviors, it may be worth rethinking how this is done and maybe make some-kind of engine-specific call to check validity or push the error-checking elsewhere. (I could think of something that's maybe a 'stylistic' translation that translates from one register to another within the same language that would require the same source and target languages...maybe that's a bad example, but you get the point).
</blockquote></details>

We don't need a validation check, since it is only used for testing purposes. I would say that engine-specific validation like this should be done by the Grpc `Create` request, so in the case of the echo engine, we could validate that the source and target language are the same in the `TranslationEngineServiceV1.Create()` method. Serval shouldn't do any specific validation for the engines, since we want to keep Serval and the engines loosely coupled.

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
@ddaspit I think everything you mentioned has been fixed.

**Review by ddaspit — DISMISSED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 16 at r3](https://reviewable.io/reviews/sillsdev/serval/80#-Nc4Oww691R_atBxuDFL:-Nc4Oww691R_atBxuDFM:b-kd43l9) ([raw file](https://github.com/sillsdev/serval/blob/adcf428d9a0986cfa3f82435845cb002de1af496/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L16)):*
> ```Smalltalk
>     {
>         if (request.SourceLanguage != request.TargetLanguage)
>             throw new ArgumentException("Source and target languages must be the same");
> ```

I believe that you have to throw a `RpcException` in a gRPC service.
___
*[`src/Serval.Client/ServalClientHelper.cs` line 104 at r3](https://reviewable.io/reviews/sillsdev/serval/80#-Nc4NgUTAt8RT-rRJ6NV:-Nc4NgUTAt8RT-rRJ6NW:b-2aagjj) ([raw file](https://github.com/sillsdev/serval/blob/adcf428d9a0986cfa3f82435845cb002de1af496/src/Serval.Client/ServalClientHelper.cs#L104)):*
> ```Smalltalk
>             // Throttle requests to only 2 x second
>             await Task.Delay(500);
>             // cRevision = result.Revision + 1;
> ```

Why was this commented out?

**Comment by Enkidu93** [comment]
*[`src/Serval.Client/ServalClientHelper.cs` line 104 at r3](https://reviewable.io/reviews/sillsdev/serval/80#-Nc4NgUTAt8RT-rRJ6NV:-NcFNPTNAyNshDLyYliJ:b-78yw48) ([raw file](https://github.com/sillsdev/serval/blob/adcf428d9a0986cfa3f82435845cb002de1af496/src/Serval.Client/ServalClientHelper.cs#L104)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this commented out?
</blockquote></details>

I didn't mean to check that in. I apologize. It was a quick fix to get around a timeout problem that John fixed elsewhere but I'm not sure has been merged??? I'll investigate. I'll remove that; thank you.

**Comment by Enkidu93** [comment]
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 16 at r3](https://reviewable.io/reviews/sillsdev/serval/80#-Nc4Oww691R_atBxuDFL:-NcFNifR4NkVzgpAd-Py:b-zi4dhz) ([raw file](https://github.com/sillsdev/serval/blob/adcf428d9a0986cfa3f82435845cb002de1af496/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I believe that you have to throw a `RpcException` in a gRPC service.
</blockquote></details>

OK, I'll go ahead and fix that.

**Comment by johnml1135** [comment]
*[`src/Serval.Client/ServalClientHelper.cs` line 104 at r3](https://reviewable.io/reviews/sillsdev/serval/80#-Nc4NgUTAt8RT-rRJ6NV:-NcN-X6G63xGF0eXY9YG:b-w0fpwh) ([raw file](https://github.com/sillsdev/serval/blob/adcf428d9a0986cfa3f82435845cb002de1af496/src/Serval.Client/ServalClientHelper.cs#L104)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I didn't mean to check that in. I apologize. It was a quick fix to get around a timeout problem that John fixed elsewhere but I'm not sure has been merged??? I'll investigate. I'll remove that; thank you.
</blockquote></details>

It is a hack solution - I ripped out all of cRevision and told Eli that by not incrementing revision, it would pass the tests (it was failing).  
Here is an idea - I wouldn't want SF and other Clients pinging Serval every 500 ms but we could do this:
* Have cRevision be default not used (with a new parameter called "incrementRequestedRevisionPerCall"
* Make a new parameter ""requestInterval" and default it to 5 seconds.  Override it when calling from a test environment.
@ddaspit , what do you think?

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

**Comment by Enkidu93** [comment]
@ddaspit @johnml1135 Let me know if there are any other outstanding issues.

**Comment by johnml1135** [comment]
*[`src/Serval.Client/ServalClientHelper.cs` line 104 at r3](https://reviewable.io/reviews/sillsdev/serval/80#-Nc4NgUTAt8RT-rRJ6NV:-NcOkRaH9yJ4Bwu1gSKj:bwd7cpw) ([raw file](https://github.com/sillsdev/serval/blob/adcf428d9a0986cfa3f82435845cb002de1af496/src/Serval.Client/ServalClientHelper.cs#L104)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It is a hack solution - I ripped out all of cRevision and told Eli that by not incrementing revision, it would pass the tests (it was failing).  
Here is an idea - I wouldn't want SF and other Clients pinging Serval every 500 ms but we could do this:
* Have cRevision be default not used (with a new parameter called "incrementRequestedRevisionPerCall"
* Make a new parameter ""requestInterval" and default it to 5 seconds.  Override it when calling from a test environment.
@ddaspit , what do you think?
</blockquote></details>

Reverting for now is ok.

**Review by johnml1135 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80#-:-NcOkXo597zCzLYTsCeE:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

**Comment by johnml1135** [comment]
*[`docker-compose.yml` line 140 at r4](https://reviewable.io/reviews/sillsdev/serval/80#-NcSRvC97fAE8qIpwtkb:-NcSRvC97fAE8qIpwtkc:b706kd3) ([raw file](https://github.com/sillsdev/serval/blob/f4c7d9466d7b64b8deb19171e9b523ec806a74c1/docker-compose.yml#L140)):*
> ```YAML
>       - ClearMLNmtEngine__ApiServer=https://api.sil.hosted.allegro.ai
>       - ClearMLNmtEngine__Queue=lambert_24gb
>       - ClearMLNmtEngine__DockerImage=mpy.local
> ```

This is a fine change.  The use of mpy.local was for local development (a locally made image) and can still be manually modified when doing development.  However for E2E tests, it would be better to use the standard production queue and github images.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 5 files at r3.
> Dismissed @ddaspit from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Comment by johnml1135** [comment]
*[`src/Serval.Client/ServalClientHelper.cs` line 104 at r3](https://reviewable.io/reviews/sillsdev/serval/80#-Nc4NgUTAt8RT-rRJ6NV:-NcS_yym1xUmutS95wN7:b-crtfqp) ([raw file](https://github.com/sillsdev/serval/blob/adcf428d9a0986cfa3f82435845cb002de1af496/src/Serval.Client/ServalClientHelper.cs#L104)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Reverting for now is ok.
</blockquote></details>

It fixes the test.  It's not good for production, but no one is using it now. https://github.com/sillsdev/serval/issues/98

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/80)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
