### PR TITLE
Mongo atlas

### PR DESCRIPTION
**Pull request by johnml1135**
A few updates including:
* Fix MongoDB Atlas for k8s (needed Google DNS server and parameterization)
* Fix E2E tests by:
  * Resolving TrainOn issue
  * Enabling all build artifacts to remain until a new E2E test is initiated to enable for better debugging.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/348)

### CODE REVIEW

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/348)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`.vscode/settings.json` line 2 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtShJtp20NNKKGfmNZL:-NtShJtp20NNKKGfmNZM:bcgjvre) ([raw file](https://github.com/sillsdev/serval/blob/45626b3fbe00546fbac09a34bc4d94fd616b3ce4/.vscode/settings.json#L2)):*
> ```JSON
> {
>   "dotnet-test-explorer.testProjectPath": "**/*Tests.csproj",
> ```

Why this change?
___
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtSi6e36_LQSG5jWe3n:-NtSi6e36_LQSG5jWe3o:b45y2n1) ([raw file](https://github.com/sillsdev/serval/blob/45626b3fbe00546fbac09a34bc4d94fd616b3ce4/tests/Serval.E2ETests/ServalClientHelper.cs#L7)):*
> ```Smalltalk
>     private string _authToken = "";
>     private readonly HttpClient _httpClient;
>     private readonly Dictionary<string, string> _enginePerUser = [];
> ```

Why this change (and accompanying)? 
___
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 45 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtShqQf9oY5X_-J0Yob:-NtShqQf9oY5X_-J0Yoc:bjtvor5) ([raw file](https://github.com/sillsdev/serval/blob/1f3103f1f6349ab3656f013c00af6cd4fcfefa39/tests/Serval.E2ETests/ServalClientHelper.cs#L45)):*
> ```Smalltalk
>         string? authUrl = Environment.GetEnvironmentVariable("SERVAL_AUTH_URL");
>         if (authUrl is null)
>             throw new InvalidOperationException("The environment variable SERVAL_AUTH_URL is not set.");
> ```

How had we never caught that? :laughing:

**Comment by johnml1135** [comment]
*[`.vscode/settings.json` line 2 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtShJtp20NNKKGfmNZL:-NtTUzgu7ZTnKbqs5Bfe:b-ixrdlx) ([raw file](https://github.com/sillsdev/serval/blob/45626b3fbe00546fbac09a34bc4d94fd616b3ce4/.vscode/settings.json#L2)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

it is not needed anymore - old configuration.

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtSi6e36_LQSG5jWe3n:-NtTVDDL0k_tMU8DvfJO:b-qs5gdo) ([raw file](https://github.com/sillsdev/serval/blob/45626b3fbe00546fbac09a34bc4d94fd616b3ce4/tests/Serval.E2ETests/ServalClientHelper.cs#L7)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why this change (and accompanying)?
</blockquote></details>

I really like all of the parameters at the top of the class.

**Comment by Enkidu93** [comment]
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtSi6e36_LQSG5jWe3n:-NtTbrRQ84-rZwGJV9x8:b-igvp1s) ([raw file](https://github.com/sillsdev/serval/blob/45626b3fbe00546fbac09a34bc4d94fd616b3ce4/tests/Serval.E2ETests/ServalClientHelper.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I really like all of the parameters at the top of the class.
</blockquote></details>

Sorry, I was asking about deleting the engines per user attribute

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/348)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/348)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`deploy/serval/templates/secrets.yaml` line 22 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtXgyWL1Cq4_rADhbZY:-NtXgyWL1Cq4_rADhbZZ:bc0qe3h) ([raw file](https://github.com/sillsdev/serval/blob/1f3103f1f6349ab3656f013c00af6cd4fcfefa39/deploy/serval/templates/secrets.yaml#L22)):*
> ```YAML
> {{- end }}
> {{- define "secrets.mongodb" }}
>             - name: mongodb_connection_part
> ```

Where is the Mongo connection URL coming from? Is it not the same for every environment?
___
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 68 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtXgWF1E-awrYIJQ0su:-NtXgWF1E-awrYIJQ0sv:b-hpqpwn) ([raw file](https://github.com/sillsdev/serval/blob/1f3103f1f6349ab3656f013c00af6cd4fcfefa39/tests/Serval.E2ETests/ServalClientHelper.cs#L68)):*
> ```Smalltalk
>     public TranslationBuildConfig InitTranslationBuildConfig()
>     {
>         TranslationBuildConfig = new TranslationBuildConfig
> ```

This should be configured in the test fixture for each test. We should avoid keeping state across different tests as much as possible.

**Comment by johnml1135** [comment]
*[`deploy/serval/templates/secrets.yaml` line 22 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtXgyWL1Cq4_rADhbZY:-Ntb8LcuC-MGEgvw5jsK:b4htzoz) ([raw file](https://github.com/sillsdev/serval/blob/1f3103f1f6349ab3656f013c00af6cd4fcfefa39/deploy/serval/templates/secrets.yaml#L22)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Where is the Mongo connection URL coming from? Is it not the same for every environment?
</blockquote></details>

No - it is not Atlas and comes from a secret that also includes a database prefix.  This is only for k8s - docker compose and local deployment can still use localhost, etc.

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtSi6e36_LQSG5jWe3n:-Ntb8eR98CZV5C2rqcCf:bkxh6n6) ([raw file](https://github.com/sillsdev/serval/blob/45626b3fbe00546fbac09a34bc4d94fd616b3ce4/tests/Serval.E2ETests/ServalClientHelper.cs#L7)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sorry, I was asking about deleting the engines per user attribute
</blockquote></details>

It was unused - it was populated but never called.

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 68 at r1](https://reviewable.io/reviews/sillsdev/serval/348#-NtXgWF1E-awrYIJQ0su:-Ntb9GBh4nvQ_OH57P_6:b-rmj6a9) ([raw file](https://github.com/sillsdev/serval/blob/1f3103f1f6349ab3656f013c00af6cd4fcfefa39/tests/Serval.E2ETests/ServalClientHelper.cs#L68)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be configured in the test fixture for each test. We should avoid keeping state across different tests as much as possible.
</blockquote></details>

It is re-initialized every test (as you can see in Setup).  It can be easily overridden if the default is not right.  Am I missing something?

**Comment by johnml1135** [comment]
Resolves https://github.com/sillsdev/serval/issues/273.

**Pull request merged**
