### PR TITLE
environment types 

### PR DESCRIPTION
**Pull request by johnml1135**
addresses https://github.com/sillsdev/serval/issues/178

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/179)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
Do we want to take this opportunity to do https://github.com/sillsdev/serval/issues/157?

> Reviewed 9 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/179#-:-Ng_KJ6N3DO0BuFNYEJV:bqxooql)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`deploy/qa-ext-values.yaml` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/179#-Ng_Jq_F6M9FqXAKYxFh:-Ng_Jq_F6M9FqXAKYxFi:b-wlb7g5) ([raw file](https://github.com/sillsdev/serval/blob/aa0a7e118f6667e4bca983a2f332dc89b31ce057/deploy/qa-ext-values.yaml#L9)):*
> ```YAML
> servalImage: ghcr.io/sillsdev/serval:0.7.1
> machineImage: ghcr.io/sillsdev/machine:3.3.2
> machineEnvironment: DummyBuild
> ```

ASP.NET Core has three deployment environments built-in: Production, Staging, and Development. This looks like it should be Staging.
___
*[`deploy/qa-int-values.yaml` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/179#-Ng_JtEU5Q1xkZtHQugC:-Ng_JtEU5Q1xkZtHQugD:b-oi3ew) ([raw file](https://github.com/sillsdev/serval/blob/aa0a7e118f6667e4bca983a2f332dc89b31ce057/deploy/qa-int-values.yaml#L9)):*
> ```YAML
> servalImage: ghcr.io/sillsdev/serval:0.7.1
> machineImage: ghcr.io/sillsdev/machine:3.3.2
> machineEnvironment: DummyBuild
> ```

This looks like it should be Staging.

**Comment by johnml1135** [comment]
I did - it was just that there wasn't as much to pull away - 80% is networking config.

**Comment by johnml1135** [comment]
*[`deploy/qa-ext-values.yaml` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/179#-Ng_Jq_F6M9FqXAKYxFh:-Ng_UwQR3r9lvDl04Tc_:b-mqp0cj) ([raw file](https://github.com/sillsdev/serval/blob/aa0a7e118f6667e4bca983a2f332dc89b31ce057/deploy/qa-ext-values.yaml#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

ASP.NET Core has three deployment environments built-in: Production, Staging, and Development. This looks like it should be Staging.
</blockquote></details>

Ok - then I will make sure that on the Serval Readme that "Staging" does "dummy builds" that don't produce helpful output.

**Comment by johnml1135** [comment]
*[`deploy/qa-int-values.yaml` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/179#-Ng_JtEU5Q1xkZtHQugC:-Ng_V9Qs7pgGnVDl1ySo:b32wtd) ([raw file](https://github.com/sillsdev/serval/blob/aa0a7e118f6667e4bca983a2f332dc89b31ce057/deploy/qa-int-values.yaml#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This looks like it should be Staging.
</blockquote></details>

ok

**Review by ddaspit — COMMENTED** [review]
I was really hoping to move everything that isn't a connection string or secret to the appsettings. What about `ClearML__Queue`, `ClearML__DockerImage`, `ClearML__Project`, `TranslationEngines` in Machine?

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/179#-:-Ngdm3qh9R5KOMzvXecl:b-cljtt4)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`deploy/values.yaml` line 11 at r3](https://reviewable.io/reviews/sillsdev/serval/179#-Ngdn6gdA7bCcqw0xPdA:-Ngdn6gdA7bCcqw0xPdB:bcsdjpm) ([raw file](https://github.com/sillsdev/serval/blob/c53e70a7aead9aacab535e27b89f8dc42db78af0/deploy/values.yaml#L11)):*
> ```YAML
> machineImage: ghcr.io/sillsdev/machine:3.3.2
> ClearMLDockerImage: ghcr.io/sillsdev/machine.py:0.9.5
> ClearMLMaxSteps: 20000
> ```

I don't think this is needed anymore.

**Comment by johnml1135** [comment]
I don't want to have to release a new docker image for Machine just because there is an update to Machine.py - nor would I want the Machine and Machine.py images embedded with deployment parameters, such as the URL that it is deployed at.  Those params belong in the helm charts.    If I want to make a local deployment to minikube, I would want to choose between production, staging and development, potentially using a different ClearML instance and S3 bucket, etc.

**Comment by johnml1135** [comment]
*[`deploy/values.yaml` line 11 at r3](https://reviewable.io/reviews/sillsdev/serval/179#-Ngdn6gdA7bCcqw0xPdA:-NgdvMKSCxVwQiMH5uBW:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/c53e70a7aead9aacab535e27b89f8dc42db78af0/deploy/values.yaml#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this is needed anymore.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
Ok, so we can leave `ClearML__DockerImage` out of the appsettings, but what about the other config options: `ClearML__Queue`, `ClearML__Project`, and `TranslationEngines`?

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/179#-:-NgdwhM02wBNbQyyY0-c:b-o4upio)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
Queue and project are dependent on the deployment.  Translation engines - I could go either way, but as of now, these "deployments" should have both Nmt and SmtTransfer engines.  Why not put them in the generic appsettings then?

**Review by ddaspit — COMMENTED** [review]
Actually, I don't think we even need to specify `TranslationEngines`. By default, it uses both `SmtTransfer` and `Nmt`. If we want to make it explicit, I think it would make sense to set `TranslationEngines` to `appsettings.json`. For now, we can just remove it from here.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/179#-:-Nge4Ear3ahP6mK7-ARN:brveiyi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
Ok, I'll remove them.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/179#-:-Nge9_YQ-Or4iknAtCr6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
