### PR TITLE
Update documentation; fixes #134

### LINKED ISSUE #134: Swagger documentation is incorrect for NMT engine source/target language property
The documentation currently states that NLLB-style language codes should be used for the NMT engine. This is incorrect. [IETF language tags](https://en.wikipedia.org/wiki/IETF_language_tag) should be used for all engines. For NMT engines, the IETF language tag will be automatically converted to an NLLB language code.

### PR DESCRIPTION
**Pull request by Enkidu93**
Is this right?

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/135)

### CODE REVIEW

**Comment by johnml1135** [comment]
I believe so...

**Review by ddaspit — CHANGES_REQUESTED** [review]
[ClearMLService.ConvertLanguageTag](https://github.com/sillsdev/machine/blob/2340e829725d7d52769bf0ccf4281c27b18486d9/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L226) is the method that converts the language tag to a NLLB code.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/135#-:-NenXRMt50uERrRxjEMa:b-g622ev)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/Serval.Client/Client.g.cs` line 796 at r1](https://reviewable.io/reviews/sillsdev/serval/135#-NenXwfT2flpv1Nq0_24:-NenXwfT2flpv1Nq0_25:b-6232wx) ([raw file](https://github.com/sillsdev/serval/blob/eeb4290c198c1934054fad2388e3fc9dac90d961/src/Serval.Client/Client.g.cs#L796)):*
> ```Smalltalk
>         /// <br/>  * Recommendation: Create a multi-part name to distinguish between projects, uses, etc.
>         /// <br/>  * The name does not have to be unique, as the engine is uniquely identified by the auto-generated id
>         /// <br/>* **sourceLanguage**: The source language code
> ```

Maybe we should change the description to "The source IETF language tag". For consistency, we should strongly recommend that a valid IETF language tag is provided.

**Comment by johnml1135** [comment]
Ah - from writing systems.  I see now.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/135)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
Wait, @johnml1135, didn't Damien want the docs to be changed further: https://github.com/sillsdev/serval/pull/135#pullrequestreview-1636135856 ?

**Comment by Enkidu93** [comment]
> Sorry, I didn’t see that and I thought all issues were resolved. Feel free to open up a new Pull request. Sorry.

No problem.

**Pull request merged**
