### PR TITLE
Add ability to use localizations for key terms

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes https://github.com/sillsdev/serval/issues/240

Parallel PR: https://github.com/sillsdev/machine/pull/233

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/454)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/454)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 171 at r1](https://reviewable.io/reviews/sillsdev/serval/454#-O4MbNJh63xFC3y4-obM:-O4MbNJh63xFC3y4-obN:bezgpt4) ([raw file](https://github.com/sillsdev/serval/blob/0601c9661e20e23a9265af09f5459e979aa8a172/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L171)):*
> ```Smalltalk
>                 (string sourceLanguageCode, string targetLanguageCode) = languageCodes;
>                 ITextCorpus? sourceTermCorpus = _corpusService
>                     .CreateTermCorpora(corpus.SourceFiles, sourceLanguageCode)
> ```

I thought we decided to use the language code from the PT project settings.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/454)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 171 at r1](https://reviewable.io/reviews/sillsdev/serval/454#-O4MbNJh63xFC3y4-obM:-O4QTH-C2mvfUsnXegHi:b-a3cy5s) ([raw file](https://github.com/sillsdev/serval/blob/0601c9661e20e23a9265af09f5459e979aa8a172/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L171)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I thought we decided to use the language code from the PT project settings.
</blockquote></details>

Sorry, yes, done. I had put that together in my mind with the later issue of adding the Chinese localizations, but better just to do it now anyways.

**Review by Enkidu93 — COMMENTED** [review]
@ddaspit, assuming you're OK with the changes in Machine, should I use the Serval IZipContainer here instead of ZipArchive?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/454#-:-O4Rr1d8-QjuXKqxoiBf:b-k64juh)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/CorpusService.cs` line 48 at r3](https://reviewable.io/reviews/sillsdev/serval/454#-O4fyhku0vOdENw7T44G:-O4fyhku0vOdENw7T44H:bb5yeu9) ([raw file](https://github.com/sillsdev/serval/blob/c5841b61f0f3b582fa15e7be6eed0adf52e853d8/src/Machine/src/Serval.Machine.Shared/Services/CorpusService.cs#L48)):*
> ```Smalltalk
>                     using (var archive = ZipFile.OpenRead(file.Location))
>                     {
>                         yield return new ZipParatextProjectTermsCorpus(archive, ["PN"]);
> ```

This will need a new version of Machine released (and included) before it can be approved.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/454)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/CorpusService.cs` line 48 at r3](https://reviewable.io/reviews/sillsdev/serval/454#-O4fyhku0vOdENw7T44G:-O4v8PwW66XscWHLWV2k:b-rzq7i3) ([raw file](https://github.com/sillsdev/serval/blob/c5841b61f0f3b582fa15e7be6eed0adf52e853d8/src/Machine/src/Serval.Machine.Shared/Services/CorpusService.cs#L48)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This will need a new version of Machine released (and included) before it can be approved.
</blockquote></details>

This has been resolved.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/454)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/454#-:-O4vFkUm4MIS0Ik7hEQX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
