### PR TITLE
Fix for new Machine, update documentation

### PR DESCRIPTION
**Pull request by johnml1135**
https://github.com/sillsdev/serval/issues/356

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/359)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
Have we update the Swagger documentation for the mixed source changes? If not, we might to include those changes as well.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/359#-:-Nv7YOUo94cQ8EheT5TR:b5ya0xh)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/PretranslationService.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/serval/359#-Nv7WmlK0FtKxWRkehix:-Nv7WmlK0FtKxWRkehiy:b6fgv7o) ([raw file](https://github.com/sillsdev/serval/blob/941b64c3fc12c34eaae90ef8b27f23fcdba41cf1/src/Serval.Translation/Services/PretranslationService.cs#L63)):*
> ```Smalltalk
>                 (
>                     (IReadOnlyList<ScriptureRef>)
>                         p.Refs.Select(r => new ScriptureRef(new VerseRef(r, targetSettings.Versification))).ToList(),
> ```

The `ScriptureRef` should be created using `ScriptureRef.Parse()`.
___
*[`src/Serval.Translation/Services/PretranslationService.cs` line 73 at r1](https://reviewable.io/reviews/sillsdev/serval/359#-Nv7XutC29OZV27_3Qqj:-Nv7XutC29OZV27_3Qqk:bths0mk) ([raw file](https://github.com/sillsdev/serval/blob/941b64c3fc12c34eaae90ef8b27f23fcdba41cf1/src/Serval.Translation/Services/PretranslationService.cs#L73)):*
> ```Smalltalk
>         string? usfm = await _scriptureDataFileService.ReadParatextProjectBookAsync(targetFile.Filename, textId);
>         if (usfm is not null)
>             return UpdateUsfm(targetSettings, usfm, pretranslations);
> ```

I think we want to consider turning off `strictComparison` when we update the target book. This will allow us to update non-Scripture segments even if the structure doesn't match exactly.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/PretranslationService.cs` line 73 at r1](https://reviewable.io/reviews/sillsdev/serval/359#-Nv7XutC29OZV27_3Qqj:-Nv8AgU23XQHcjXz2Ics:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/941b64c3fc12c34eaae90ef8b27f23fcdba41cf1/src/Serval.Translation/Services/PretranslationService.cs#L73)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think we want to consider turning off `strictComparison` when we update the target book. This will allow us to update non-Scripture segments even if the structure doesn't match exactly.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
We did - check out the production swagger and see if you like it.

**Comment by ddaspit** [comment]
@johnml1135  You never committed fixes for my requested changes.

**Pull request merged**
