### PR TITLE
Use chapter-filtering for terms

### PR DESCRIPTION
**Pull request by Enkidu93**
Reworking of https://github.com/sillsdev/serval/pull/508

Fixes https://github.com/sillsdev/serval/issues/476

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/545)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/545)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 87 at r1](https://reviewable.io/reviews/sillsdev/serval/545#-OCeE8jNBueLAa52ZUF7:-OCeE8jNBueLAa52ZUF8:b-cm4ule) ([raw file](https://github.com/sillsdev/serval/blob/e5ead88a02d16b4792e22ab5525a42280402f19a/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L87)):*
> ```Smalltalk
>                 ITextCorpus[]? sourceTermCorpora = _corpusService
>                     .CreateTermCorpora(
>                         corpus.SourceCorpora.SelectMany(sc => sc.Files.Select(f => (f, sc.TrainOnChapters))).ToArray()
> ```

What about textIds?

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/545)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 87 at r1](https://reviewable.io/reviews/sillsdev/serval/545#-OCeE8jNBueLAa52ZUF7:-OCeekS461Ar78yFHvgJ:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e5ead88a02d16b4792e22ab5525a42280402f19a/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L87)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What about textIds?
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/545#-:-OCefSID-W95FIRE7r_R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
Still fixing a bug

**Comment by johnml1135** [comment]
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 95 at r3](https://reviewable.io/reviews/sillsdev/serval/545#-OCi4vWY3QlaAD0CByAi:-OCi4vWY3QlaAD0CByAj:b-185iu2) ([raw file](https://github.com/sillsdev/serval/blob/069dc402d482bb9bde26bea8053b426aa144b137/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L95)):*
> ```Smalltalk
>                     IParallelTextCorpus parallelKeyTermsCorpus = sourceTermCorpora
>                         .ChooseRandom(Seed)
>                         .AlignRows(targetTermCorpora.ChooseFirst());
> ```

Does this also address https://github.com/sillsdev/serval/issues/538?  Can we unique these - or do we want to do it in a separate PR?

**Comment by johnml1135** [comment]
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 95 at r3](https://reviewable.io/reviews/sillsdev/serval/545#-OCi4vWY3QlaAD0CByAi:-OCi7a7NCsQp0acJAU0R:b-c7xvdp) ([raw file](https://github.com/sillsdev/serval/blob/069dc402d482bb9bde26bea8053b426aa144b137/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L95)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Does this also address https://github.com/sillsdev/serval/issues/538?  Can we unique these - or do we want to do it in a separate PR?
</blockquote></details>

A separate PR is fine.

**Comment by johnml1135** [comment]
Is it all ready?  Do we need to re-release Machine?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/545)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
Alright, the last issue has been addressed. We'll need 

> Is it all ready? Do we need to re-release Machine?

https://github.com/sillsdev/machine/pull/278

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 6 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/545)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/CorpusService.cs` line 43 at r5](https://reviewable.io/reviews/sillsdev/serval/545#-OCismmO1MQ2WV_ObWNU:-OCismmO1MQ2WV_ObWNV:b-edbvir) ([raw file](https://github.com/sillsdev/serval/blob/dd7f62038c1cf7955532facd2481809b0370bfa6/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/CorpusService.cs#L43)):*
> ```Smalltalk
>     )
>     {
>         foreach ((CorpusFile file, Dictionary<string, HashSet<int>>? chapters) in corpora)
> ```

Why was this added?

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/545)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/CorpusService.cs` line 43 at r5](https://reviewable.io/reviews/sillsdev/serval/545#-OCismmO1MQ2WV_ObWNU:-OCit_cN3rd2qQAU93kc:bi2hesg) ([raw file](https://github.com/sillsdev/serval/blob/dd7f62038c1cf7955532facd2481809b0370bfa6/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/CorpusService.cs#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this added?
</blockquote></details>

Sorry, it was there before; I added it back in temporarily while I was rethinking what the right behavior should be when no filters are supplied and then forgot to remove it. Removed.

**Review by ddaspit — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/545)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
