### PR TITLE
Mark corpus endpoints obsolete

### LINKED ISSUE #515: Add "obsolete" property to corpora
On the Serval endpoints for all types of corpora.

### PR DESCRIPTION
**Pull request by johnml1135**
* ignore CS0612 obsolete endpoint warnings in E2E and integration tests

Resolves #515

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/535)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
We should also mark obsolete properties in the relevant DTOs.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/535#-:-OAdmAk06RM7OwlrmCfr:b-xoxkn3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/535)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/Serval.ApiServer.IntegrationTests.csproj` line 16 at r2](https://reviewable.io/reviews/sillsdev/serval/535#-OAt2gTxAtDRMBioN3E3:-OAt2gTxAtDRMBioN3E4:b85q8fs) ([raw file](https://github.com/sillsdev/serval/blob/bfc1214ccf2397970ca4013898e0a17ee7133765/src/Serval/test/Serval.ApiServer.IntegrationTests/Serval.ApiServer.IntegrationTests.csproj#L16)):*
> ```XML
> 		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
> 		<GenerateDocumentationFile>true</GenerateDocumentationFile>
> 		<NoWarn>$(NoWarn);CS1591;CS1573;CS0612</NoWarn>
> ```

We should use `#pragma warning disable CS0612` like you did in the controller.

**Comment by johnml1135** [comment]
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/Serval.ApiServer.IntegrationTests.csproj` line 16 at r2](https://reviewable.io/reviews/sillsdev/serval/535#-OAt2gTxAtDRMBioN3E3:-OAxUjgt4mRMNDwiGWPo:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/bfc1214ccf2397970ca4013898e0a17ee7133765/src/Serval/test/Serval.ApiServer.IntegrationTests/Serval.ApiServer.IntegrationTests.csproj#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should use `#pragma warning disable CS0612` like you did in the controller.
</blockquote></details>

done

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/535#-:-OAxVIO8CZJLyE7AN3gy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
