### PR TITLE
Add open telemetry

### LINKED ISSUE #58: Transaction ID per API call
For traceability and logging.

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes #58

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/137)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/137)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.ApiServer/Startup.cs` line 163 at r1](https://reviewable.io/reviews/sillsdev/serval/137#-Neok7AW9S643V2JMVhO:-Neok7AW9S643V2JMVhP:b-k9t96o) ([raw file](https://github.com/sillsdev/serval/blob/d7d80e863b3bc9c274f65890b35582439f0d420a/src/Serval.ApiServer/Startup.cs#L163)):*
> ```Smalltalk
>         services
>             .AddOpenTelemetry()
>             .WithTracing(builder =>
> ```

We also want [gRPC instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.GrpcNetClient).
___
*[`src/Serval.ApiServer/Startup.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/137#-Neok98V8ulol3jDoAdF:-Neok98V8ulol3jDoAdG:bgnyzx1) ([raw file](https://github.com/sillsdev/serval/blob/d7d80e863b3bc9c274f65890b35582439f0d420a/src/Serval.ApiServer/Startup.cs#L165)):*
> ```Smalltalk
>             .WithTracing(builder =>
>             {
>                 builder.AddAspNetCoreInstrumentation().AddConsoleExporter();
> ```

You only need to call `AddConsoleExporter()` once. The convention in ASP.NET Core is to return the builder instance on each method that adds a service, this allows you to chain the methods:
```
builder
    .AddAspNetCoreInstrumentation()
    .AddHttpClientInstrumentation()
    .AddSource("MongoDB.Driver.Core.Extensions.DiagnosticSources")
    .AddConsoleExporter();
```

**Comment by johnml1135** [comment]
*[`src/Serval.ApiServer/Serval.ApiServer.csproj` line 27 at r1](https://reviewable.io/reviews/sillsdev/serval/137#-NerqfIoBECXovuIOXAI:-NerqfIoBECXovuIOXAJ:b-kz66df) ([raw file](https://github.com/sillsdev/serval/blob/d7d80e863b3bc9c274f65890b35582439f0d420a/src/Serval.ApiServer/Serval.ApiServer.csproj#L27)):*
> ```XML
> 		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
> 		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.1-beta.1" />
> 		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.5.1-beta.1" />
> ```

Why are we adding package references instead of installing it in the docker images as in here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/examples/demo?  There could be great reasons - I just don't know them.

**Comment by Enkidu93** [comment]
*[`src/Serval.ApiServer/Serval.ApiServer.csproj` line 27 at r1](https://reviewable.io/reviews/sillsdev/serval/137#-NerqfIoBECXovuIOXAI:-NeruQTK2bgw3CGG47OG:b-ur1o6g) ([raw file](https://github.com/sillsdev/serval/blob/d7d80e863b3bc9c274f65890b35582439f0d420a/src/Serval.ApiServer/Serval.ApiServer.csproj#L27)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why are we adding package references instead of installing it in the docker images as in here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/examples/demo?  There could be great reasons - I just don't know them.
</blockquote></details>

I'm not sure I understand the question entirely, but I think you're referencing the use of the OpenTelemetry Collector (?). These imports are for the automatic instrumentation. Right now we're exporting to the console (not a good long-term solution probably). If we wanted to add a collector, that's doable but a separate issue I think. See [this](https://opentelemetry.io/docs/collector/#when-to-use-a-collector) for more information.

**Comment by Enkidu93** [comment]
*[`src/Serval.ApiServer/Startup.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/137#-Neok98V8ulol3jDoAdF:-NervNI4C1PNCFbUChoS:bx6wylg) ([raw file](https://github.com/sillsdev/serval/blob/d7d80e863b3bc9c274f65890b35582439f0d420a/src/Serval.ApiServer/Startup.cs#L165)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You only need to call `AddConsoleExporter()` once. The convention in ASP.NET Core is to return the builder instance on each method that adds a service, this allows you to chain the methods:
```
builder
    .AddAspNetCoreInstrumentation()
    .AddHttpClientInstrumentation()
    .AddSource("MongoDB.Driver.Core.Extensions.DiagnosticSources")
    .AddConsoleExporter();
```
</blockquote></details>

Yes, I apologize. The example I followed made that mistake, and although it didn't make sense to me, I sheeped along. I'll fix that.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/137#-:-NesSLwL-7D6ol5-nbLK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
@johnml1135 Do you want this to be merged or would you rather I put the console exporter behind a development flag first?

**Review by Enkidu93 — COMMENTED** [review]
> Dismissed @johnml1135 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/137)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.ApiServer/Startup.cs` line 163 at r1](https://reviewable.io/reviews/sillsdev/serval/137#-Neok7AW9S643V2JMVhO:-NervLhbBJ9lK4PMjczJ:bh1md71) ([raw file](https://github.com/sillsdev/serval/blob/d7d80e863b3bc9c274f65890b35582439f0d420a/src/Serval.ApiServer/Startup.cs#L163)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We also want [gRPC instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.GrpcNetClient).
</blockquote></details>

Oh, good catch - sorry!

**Comment by johnml1135** [comment]
*[`src/Serval.ApiServer/Serval.ApiServer.csproj` line 27 at r1](https://reviewable.io/reviews/sillsdev/serval/137#-NerqfIoBECXovuIOXAI:-NeyMO9a9dpFU13cSpdA:b-y5n81m) ([raw file](https://github.com/sillsdev/serval/blob/d7d80e863b3bc9c274f65890b35582439f0d420a/src/Serval.ApiServer/Serval.ApiServer.csproj#L27)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm not sure I understand the question entirely, but I think you're referencing the use of the OpenTelemetry Collector (?). These imports are for the automatic instrumentation. Right now we're exporting to the console (not a good long-term solution probably). If we wanted to add a collector, that's doable but a separate issue I think. See [this](https://opentelemetry.io/docs/collector/#when-to-use-a-collector) for more information.
</blockquote></details>

Let's kick the can - here is the issue: https://github.com/sillsdev/serval/issues/138

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/137)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
