### PR TITLE
Incorporate accidentally removed logic from https://github.com/sillsdev/machine/pull/207

### PR DESCRIPTION
**Pull request by Enkidu93**
Not sure how this logic got removed. I think I was away for all of this, so if I'm missing something, let me know.

Fixes: https://github.com/sillsdev/serval/issues/460

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)

### CODE REVIEW

**Comment by Enkidu93** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 379 at r1](https://reviewable.io/reviews/sillsdev/serval/467#-O5EURcL7a_ls8AHnIxO:-O5EURcL7a_ls8AHnIxP:b-y17o5r) ([raw file](https://github.com/sillsdev/serval/blob/a642f72436ffd24ea5a0a49ec70f8a23368092e7/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L379)):*
> ```Smalltalk
>     private static IEnumerable<Row> AlignPretranslateCorpus(Corpus corpus, ITextCorpus srcCorpus, ITextCorpus trgCorpus)
>     {
>         IEnumerable<string>? textIds = corpus.PretranslateChapters is not null
> ```

I can move this logic out of the method if you'd prefer to avoid passing `corpus` along, but I thought I'd try to be as consistent as possible with how it previously was for an initial pass. Lmk.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 263 at r1](https://reviewable.io/reviews/sillsdev/serval/467#-O5EZ5q36Bv1546oSo2m:-O5EZ5q36Bv1546oSo2n:bondng8) ([raw file](https://github.com/sillsdev/serval/blob/a642f72436ffd24ea5a0a49ec70f8a23368092e7/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L263)):*
> ```Smalltalk
> 
>     private static IEnumerable<Row?[]> AlignTrainCorpus(IReadOnlyList<ITextCorpus> srcCorpora, ITextCorpus trgCorpus)
>     {
> ```

Does it need this code as well:
```
        IEnumerable<string>? textIds = corpus.TrainOnChapters is not null
            ? corpus.TrainOnChapters.Keys
            : corpus.TrainOnTextIds;
        srcCorpora = srcCorpora.Select(sc => sc.FilterTexts(textIds)).ToArray();
        trgCorpus = trgCorpus.FilterTexts(textIds);
```
removed from the same SMT job fix (that I did)?

**Comment by johnml1135** [comment]
We also need a test to make sure that this doesn't happen again.  One way could be to stub out the parsing routine with just throwing an error and have the textIds filter out all text.  Make sure that the error is not thrown.  This would need to be both for training and pretranslating alignments.

**Review by ddaspit — CHANGES_REQUESTED** [review]
Yeah, I'm not sure how the logic got removed. It looks like it happened when we moved SMT to ClearML.

Texts should also be filtered out in `AlignTrainCorpus` as well. Check out the code in the original PR.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467#-:-O5EXczR-CLatZ-xd7hj:b-85f9qr)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 379 at r1](https://reviewable.io/reviews/sillsdev/serval/467#-O5EURcL7a_ls8AHnIxO:-O5EYMZx8dnthk6_RwCZ:bfeicbv) ([raw file](https://github.com/sillsdev/serval/blob/a642f72436ffd24ea5a0a49ec70f8a23368092e7/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L379)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I can move this logic out of the method if you'd prefer to avoid passing `corpus` along, but I thought I'd try to be as consistent as possible with how it previously was for an initial pass. Lmk.
</blockquote></details>

This looks fine.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 379 at r1](https://reviewable.io/reviews/sillsdev/serval/467#-O5EURcL7a_ls8AHnIxO:-O5EZiIi9zOZTPy_GJSj:b7vjnf8) ([raw file](https://github.com/sillsdev/serval/blob/a642f72436ffd24ea5a0a49ec70f8a23368092e7/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L379)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This looks fine.
</blockquote></details>

If you can think of a better way to do that, more power to you.  It would also need to be replicated in `AlignTrainCorpus` whichever way you decide.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
:Ahem: I think it was my fault :-(.

**Review by Enkidu93 — COMMENTED** [review]
Oh, right, yes, I forgot - thanks, Damien. And yes, John, I'll try and find a way to test this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467#-:-O5EZv8O1MvjMO0CrW_B:bn3vi1o)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
And yeah, I think it happened when we move stuff from `Nmt...` to just plain old `PreprocessBuildJob` - easy mistake.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467#-:-O5E_G27EY3dkBRHf3sx:bwkjk6k)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 263 at r1](https://reviewable.io/reviews/sillsdev/serval/467#-O5EZ5q36Bv1546oSo2m:-O5E_rdi62qqon3RI94u:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a642f72436ffd24ea5a0a49ec70f8a23368092e7/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L263)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Does it need this code as well:
```
        IEnumerable<string>? textIds = corpus.TrainOnChapters is not null
            ? corpus.TrainOnChapters.Keys
            : corpus.TrainOnTextIds;
        srcCorpora = srcCorpora.Select(sc => sc.FilterTexts(textIds)).ToArray();
        trgCorpus = trgCorpus.FilterTexts(textIds);
```
removed from the same SMT job fix (that I did)?
</blockquote></details>

Done.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
Tests have been added.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467#-:-O5J_8ZZAyug9S9NO5Bs:b-6leefm)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ddaspit and @johnml1135)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 1 at r3](https://reviewable.io/reviews/sillsdev/serval/467#-O5JaXaf736bEvcSvPfn:-O5JaXaf736bEvcSvPfo:b-gech7g) ([raw file](https://github.com/sillsdev/serval/blob/6d11ca1b7e1b2e0964a67b028480da9e858fea58/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L1)):*
> ```Smalltalk
> using System.Collections;
> ```

These should be added to the global usings.
___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 266 at r3](https://reviewable.io/reviews/sillsdev/serval/467#-O5JbAGqEJIp50SS24d_:-O5JbAGqEJIp50SS24da:b-v0vsl2) ([raw file](https://github.com/sillsdev/serval/blob/6d11ca1b7e1b2e0964a67b028480da9e858fea58/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L266)):*
> ```Smalltalk
>                 }
>             );
>         await env.RunBuildJobAsync(corpus);
> ```

You should assert that the call does not throw an exception, so it is explicit what is being tested.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 1 at r3](https://reviewable.io/reviews/sillsdev/serval/467#-O5JaXaf736bEvcSvPfn:-O5JzZ9W3QDu2vytGnfL:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/6d11ca1b7e1b2e0964a67b028480da9e858fea58/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These should be added to the global usings.
</blockquote></details>

Done.
___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 266 at r3](https://reviewable.io/reviews/sillsdev/serval/467#-O5JbAGqEJIp50SS24d_:-O5JzZZy9BD_LfLk_1h1:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/6d11ca1b7e1b2e0964a67b028480da9e858fea58/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L266)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should assert that the call does not throw an exception, so it is explicit what is being tested.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467#-:-O5K4TI39gQXZgeoQajO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/467)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
