### PR TITLE
Update dependencies with vulnerabilities

### LINKED ISSUE #544: Bugsnag.AspNet.Core has dependencies on deprecated/vulnerable packages
`Bugsnag.AspNet.Core` hasn't been updated in a couple of years. I don't know if we can expect Bugsnag to fix the issues any time soon. We should consider removing the dependency and providing our own implementation that uses the `Bugsnag` library directly.

### PR DESCRIPTION
**Pull request by ddaspit**
- update OpenTelemetry
- update MassTransit
- remove Bugsnag.AspNet.Core, implement natively
- fixes #544

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/549)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/BugsnagMiddleware.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/549#-OD6YIO17w0vKLkfi8yO:-OD6YIO17w0vKLkfi8yP:blh8tu3) ([raw file](https://github.com/sillsdev/serval/blob/05489aa5e5783c1190b6092008b7bba153892d5e/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/BugsnagMiddleware.cs#L6)):*
> ```Smalltalk
> /// The Bugsnag AspNetCore middleware.
> /// </summary>
> public class BugsnagMiddleware(RequestDelegate requestDelegate)
> ```

Is this just a copy-paste from the Bugsnag implementation?  If it is, can you reference the source of it in a comment?  In 3 years, Bugsnag may update some of it and it would be nice to know what is the same and different, and when it was forked.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 13 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/549)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

**Review by Enkidu93 — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/549)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/549)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/BugsnagMiddleware.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/549#-OD6YIO17w0vKLkfi8yO:-ODCh6laB51wr9P0szS6:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/05489aa5e5783c1190b6092008b7bba153892d5e/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/BugsnagMiddleware.cs#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is this just a copy-paste from the Bugsnag implementation?  If it is, can you reference the source of it in a comment?  In 3 years, Bugsnag may update some of it and it would be nice to know what is the same and different, and when it was forked.
</blockquote></details>

Done.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/549)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
