### PR TITLE
retry clearml calls on 429 responses.

### PR DESCRIPTION
**Pull request by johnml1135**
https://github.com/sillsdev/serval/issues/524

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/531)

### CODE REVIEW

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/531#-:-OAYs3og3sagHBUXKMs8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
Thank you for doing this, John! Have we figured out with ClearML if we're actually over-requesting because of an error in our code? Also, might it be wise to see if them upping the limit fixes things before introducing another change like this (i.e., this might increase the number of requests even while they're upping our limit)?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/531#-:-OAYrrdp6W9QnqIzgckb:b-ryikkn)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
They just removed the limit entirely.  The issue may be that all of our servers present themselves as the same IP address.  Also, each agent calls out to ClearML every 2 seconds.  It's a number of things together.

**Comment by johnml1135** [comment]
Moreover, we were intending the code to handle the 429 case and it was a mistake that it didn't.  That is why I am ok going forward with this change.

**Pull request merged**
