### PR TITLE
Percent complete

### PR DESCRIPTION
**Pull request by Enkidu93**
Note that this should be merged in parallel with matching PR in machine: https://github.com/sillsdev/machine/pull/52

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/78)

### CODE REVIEW

**Comment by johnml1135** [comment]
This implements https://github.com/sillsdev/serval/issues/44.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 236 at r2](https://reviewable.io/reviews/sillsdev/serval/78#-NbW37L06FY2fjAdtRvk:-NbW37L06FY2fjAdtRvl:bfi7hoo) ([raw file](https://github.com/sillsdev/serval/blob/d5d82f0f95b2999904aa5470a7d9387303903424/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L236)):*
> ```Smalltalk
>     {
>         await _builds.UpdateAsync(
>             b => b.Id == request.BuildId && (b.State == JobState.Active || b.State == JobState.Pending),
> ```

What was the reason for this change?  What are the implications of updating build status when queued?  It looks to fix a bug when in Serval the MongoDB has the item as queued while in fact it is active.  Am I correct?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/78)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> _[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 236 at r2](https://reviewable.io/reviews/sillsdev/serval/78#-NbW37L06FY2fjAdtRvk:-NbW37L06FY2fjAdtRvl:bfi7hoo) ([raw file](https://github.com/sillsdev/serval/blob/d5d82f0f95b2999904aa5470a7d9387303903424/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L236)):_
> 
> > ```smalltalk
> >     {
> >         await _builds.UpdateAsync(
> >             b => b.Id == request.BuildId && (b.State == JobState.Active || b.State == JobState.Pending),
> > ```
> 
> What was the reason for this change? What are the implications of updating build status when queued? It looks to fix a bug when in Serval the MongoDB has the item as queued while in fact it is active. Am I correct?

Almost - this is to allow status updates while the build is queued/pending. What this accomplishes is this: In the message field of the `ProgressStatus`, we can record how many jobs are ahead of the build in the queue. Is that alright? Do you see that causing issues elsewhere?

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 236 at r2](https://reviewable.io/reviews/sillsdev/serval/78#-NbW37L06FY2fjAdtRvk:-NbZYh2K4z4Y5N6QUeOX:b98fudl) ([raw file](https://github.com/sillsdev/serval/blob/d5d82f0f95b2999904aa5470a7d9387303903424/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L236)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Almost - this is to allow status updates while the build is queued/pending. What this accomplishes is this: In the message field of the `ProgressStatus`, we can record how many jobs are ahead of the build in the queue. Is that alright? Do you see that causing issues elsewhere?
</blockquote></details>

Great - that makes sense.

**Comment by johnml1135** [comment]
Also per @ddaspit's comment - it appears that only some of the items on the hangfire queue are put onto the ClearML queue - we need to make a decision what to do about this.  Should we put them all on the ClearML queue?  How many can it handle?  Should the be in both queues?  What is the best mechanism for this?  If we have 50 items in the ClearML queue, can we make one call to see everything in the queue instead of 50 calls?  What about multiple instances of Serval using the same ClearML instance (QA, prod)?  Should they have different project names such as `Serval-<random 6 digit Hex ID>` or, have them all in the same project but have the experiment name be <instance ID>-<build ID>?  Note that machine does not know what instance it is actually in...

**Comment by johnml1135** [comment]
One potential solution could be to query ClearML every 5 seconds once for all queued items that match a specific pattern (that corresponds with the specific instance of Serval) and query MongoDB once for all current builds - and if there is an update to make in MongoDB, make it.  If any jobs have been cancelled, aborted or failed in one (ClearML or MongoDB), update the other.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
@ddaspit @johnml1135 Just to verify, I should complete implementing the percent complete functionality (using the lastiteration, 90/10, log metric strategy)? #44 I have stashed local changes with that implementation just about finished. But I just wanted to verify that other developments in the ideas about refactoring to accommodate a queue depth endpoint and avoid polling hadn't changed anything here.

**Comment by johnml1135** [comment]
Eli, please connect with Damien to verify. Whatever he says is fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ddaspit** [comment]
@Enkidu93 Yes, let's go ahead and get the percent completed work in. We will handle queue depth and avoid polling in other issues.

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
