### PR TITLE
Remove action delegates for configuration

### PR DESCRIPTION
**Pull request by johnml1135**
This addresses #518.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/537)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/537)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IServiceCollectionExtensions.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/537#-OAxaWBiEKbnFHjyXZkg:-OAxaWBiEKbnFHjyXZkh:bh1dbkz) ([raw file](https://github.com/sillsdev/serval/blob/9039920803ed4cd64de28cd262c34eb8779c25a1/src/Machine/src/Serval.Machine.Shared/Configuration/IServiceCollectionExtensions.cs#L5)):*
> ```Smalltalk
> public static class IServiceCollectionExtensions
> {
>     public static IMachineBuilder AddMachine(this IServiceCollection services, IConfiguration? configuration = null)
> ```

`configuration` no longer needs to be optional. Then you won't need to check if `configuration` is `null`. You should do the same for the `AddServal` method as well.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IServiceCollectionExtensions.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/537#-OAxaWBiEKbnFHjyXZkg:-OAxmSl-Bw_Ari33_pw0:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/9039920803ed4cd64de28cd262c34eb8779c25a1/src/Machine/src/Serval.Machine.Shared/Configuration/IServiceCollectionExtensions.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`configuration` no longer needs to be optional. Then you won't need to check if `configuration` is `null`. You should do the same for the `AddServal` method as well.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/537)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Assessment/Configuration/IServalBuilderExtensions.cs` line 18 at r2](https://reviewable.io/reviews/sillsdev/serval/537#-OAyVXrxB5ARGSzpqpUw:-OAyVXrxB5ARGSzpqpUx:b-9abd7f) ([raw file](https://github.com/sillsdev/serval/blob/5e61336c8099cd9006ea1fafe905e4ef9c1d979b/src/Serval/src/Serval.Assessment/Configuration/IServalBuilderExtensions.cs#L18)):*
> ```Smalltalk
> 
>         var assessmentOptions = new AssessmentOptions();
>         builder.Configuration?.GetSection(AssessmentOptions.Key).Bind(assessmentOptions);
> ```

We don't need the null-conditional operator anymore.
___
*[`src/Serval/src/Serval.Translation/Configuration/IServalBuilderExtensions.cs` line 18 at r2](https://reviewable.io/reviews/sillsdev/serval/537#-OAyVxdT1pQPnFSUqjku:-OAyVxdT1pQPnFSUqjkv:b-9abd7f) ([raw file](https://github.com/sillsdev/serval/blob/5e61336c8099cd9006ea1fafe905e4ef9c1d979b/src/Serval/src/Serval.Translation/Configuration/IServalBuilderExtensions.cs#L18)):*
> ```Smalltalk
> 
>         var translationOptions = new TranslationOptions();
>         builder.Configuration?.GetSection(TranslationOptions.Key).Bind(translationOptions);
> ```

We don't need the null-conditional operator anymore.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Configuration/IServalBuilderExtensions.cs` line 18 at r2](https://reviewable.io/reviews/sillsdev/serval/537#-OAyVxdT1pQPnFSUqjku:-OAz14NA9xQ_za9mmVEL:b-yc4hfm) ([raw file](https://github.com/sillsdev/serval/blob/5e61336c8099cd9006ea1fafe905e4ef9c1d979b/src/Serval/src/Serval.Translation/Configuration/IServalBuilderExtensions.cs#L18)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't need the null-conditional operator anymore.
</blockquote></details>

Fixed all.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Configuration/IServalBuilderExtensions.cs` line 18 at r2](https://reviewable.io/reviews/sillsdev/serval/537#-OAyVXrxB5ARGSzpqpUw:-OAz1ghd1fN8TzldtFgd:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/5e61336c8099cd9006ea1fafe905e4ef9c1d979b/src/Serval/src/Serval.Assessment/Configuration/IServalBuilderExtensions.cs#L18)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't need the null-conditional operator anymore.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/537#-:-OB0sKXUAo_Kyt2MXv8P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
