### PR TITLE
Add bugsnag

### PR DESCRIPTION
**Pull request by johnml1135**
Initial Implementation for all controller exceptions.

https://github.com/sillsdev/serval/issues/485

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/488)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 16 of 19 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/488)* status: all files reviewed, 5 unresolved discussions (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.EngineServer/Program.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6XiR_M5b5UhUUKglv0:-O6XiR_NDaxeSjwTtYSO:bnknh7j) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/Machine/src/Serval.Machine.EngineServer/Program.cs#L32)):*
> ```Smalltalk
> }
> 
> builder.Services.AddBugSnag(builder.Configuration);
> ```

We don't need our own `AddBugSnag` method. We can just call:

``` cs
builder.Services.Configure<Bugsnag.Configuration>(builder.Configuration.GetSection("Bugsnag"));
builder.Services.AddBugSnag();
```
___
*[`src/Serval/src/Serval.Shared/Controllers/BugsnagExceptionFilter.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6XheUPA8gW7uN6dXHM:-O6XheUQ5sqBGwbZG0CV:b-qqs926) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/Serval/src/Serval.Shared/Controllers/BugsnagExceptionFilter.cs#L5)):*
> ```Smalltalk
> namespace Serval.Shared.Controllers;
> 
> public class BugsnagExceptionFilter : ExceptionFilterAttribute
> ```

We don't need this. Bugsnag [automatically reports unhandled exceptions](https://docs.bugsnag.com/platforms/dotnet/asp-net-core/#reporting-unhandled-exceptions).
___
*[`src/Serval/src/Serval.Shared/Controllers/ServalControllerBase.cs` line 14 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6Xitk39HRU6RGgTsu2:-O6Xitk39HRU6RGgTsu3:b-i96x2y) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/Serval/src/Serval.Shared/Controllers/ServalControllerBase.cs#L14)):*
> ```Smalltalk
> [TypeFilter(typeof(ForbiddenExceptionFilter))]
> [TypeFilter(typeof(BadRequestExceptionFilter))]
> public abstract class ServalControllerBase(IAuthorizationService authService, Bugsnag.IClient bugsnagClient)
> ```

There is no need to inject the BugSnag client into every controller. We can just inject it where needed.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Configuration/BugsnagOptions.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6Xhyzt8kJUKfEGTF5w:-O6Xhyzt8kJUKfEGTF5x:btbb8jj) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/ServiceToolkit/src/SIL.ServiceToolkit/Configuration/BugsnagOptions.cs#L3)):*
> ```Smalltalk
> namespace SIL.ServiceToolkit.Services;
> 
> public class BugsnagOptions
> ```

Bugsnag already has a configuration options class.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Configuration/IServiceCollectionExtensions.cs` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6XiCDa5d-StsHiEFFk:-O6XiCDa5d-StsHiEFFl:b9pfi4c) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/ServiceToolkit/src/SIL.ServiceToolkit/Configuration/IServiceCollectionExtensions.cs#L9)):*
> ```Smalltalk
> public static class IServiceCollectionExtensions
> {
>     public static IServiceCollection AddBugSnag(this IServiceCollection services, IConfiguration? configuration = null)
> ```

We don't need this. See my comment above.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.EngineServer/Program.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6XiR_M5b5UhUUKglv0:-O6aOk2E8wg7wHv3ZRkq:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/Machine/src/Serval.Machine.EngineServer/Program.cs#L32)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't need our own `AddBugSnag` method. We can just call:

``` cs
builder.Services.Configure<Bugsnag.Configuration>(builder.Configuration.GetSection("Bugsnag"));
builder.Services.AddBugSnag();
```
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Shared/Controllers/BugsnagExceptionFilter.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6XheUPA8gW7uN6dXHM:-O6aOmJA8ThNi5GPyVC9:b-9mmsjl) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/Serval/src/Serval.Shared/Controllers/BugsnagExceptionFilter.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't need this. Bugsnag [automatically reports unhandled exceptions](https://docs.bugsnag.com/platforms/dotnet/asp-net-core/#reporting-unhandled-exceptions).
</blockquote></details>

I was thinking about the exceptions we handled that I still wanted to log them, but then I released that they are normally bad user behavior (looking for a file that doesn't exist) rather than code error.  Updated.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Shared/Controllers/ServalControllerBase.cs` line 14 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6Xitk39HRU6RGgTsu2:-O6aPu_M3AN1idxMFW-E:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/Serval/src/Serval.Shared/Controllers/ServalControllerBase.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is no need to inject the BugSnag client into every controller. We can just inject it where needed.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Configuration/IServiceCollectionExtensions.cs` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/488#-O6XiCDa5d-StsHiEFFk:-O6aPx0Q3brki8mDA6y4:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/d3f83c70d03b7ab9e68848f86fb5b69b52f132e1/src/ServiceToolkit/src/SIL.ServiceToolkit/Configuration/IServiceCollectionExtensions.cs#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't need this. See my comment above.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/488#-:-O6abJHK75-gLSvBgjGx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
