### PR TITLE
Queue depth endpoint and status message

### PR DESCRIPTION
**Pull request by Enkidu93**
See [here](https://github.com/sillsdev/machine/pull/110) for parallel PR in machine.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/177)

### CODE REVIEW

**Comment by Enkidu93** [comment]
This addresses #79 and #89.

**Review by ddaspit — COMMENTED** [review]
I know we didn't discuss a design for this feature, but I was expecting this to be a property on the build model and not a separate endpoint.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177#-:-NgV3uRdAJQ95yQ_9FYj:b-dua4oz)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
Just to make it clear, this addresses two separate issues: 1) Build statuses now include a message about how many builds are ahead of them in the queue. And 2) there is an API endpoint to query overall build job queue depth per engine type. I made this second feature universal as per John's suggestion in the issue (given I understood correctly). It's easy enough, however, to move it under a specific engine, but I don't think it would make sense to only have it has a build property when the point is to query the overall queue depth for 'intelligent job throttling'.

**Review by ddaspit — COMMENTED** [review]
Ah, ok. I scanned through the PR quickly. I didn't realize that you were reporting the queue depth in the Build message property.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177#-:-NgV4UgB5HouhqMvtyME:b-x8yvds)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — COMMENTED** [review]
It does make we wonder if this should be separate property in the Build model. An application might want to decide how they are going to display the queue depth.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177#-:-NgVSl1J6q_xa4OaA9CS:bc03rhv)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
Yeah, I wondered about that myself. It would certainly be cleaner. I'm happy to add such a property if I have the go-ahead.

**Comment by johnml1135** [comment]
I agree - adding a queue depth to the build status (as well as a separate endpoint for general depth) was my expectation.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177#-:-NgZX4J378TU1ejsVSCs:b-896fix)* status: 9 of 16 files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval.Translation/Contracts/QueueDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_-_a-8Crq2oQFsEzC:-Ng_-_a02V0fdMc3RZ2r:b-65g980) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Contracts/QueueDto.cs#L5)):*
> ```Smalltalk
> public class QueueDto
> {
>     public int Depth { get; set; } = default;
> ```

I think `Count` or `Size` would be better. I also think you should include the engine type.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 200 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_-lBVBP2UYElm87Pq:-Ng_-lBVBP2UYElm87Pr:b-gmuc6g) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L200)):*
> ```Smalltalk
>     [ProducesResponseType(typeof(void), StatusCodes.Status403Forbidden)]
>     [ProducesResponseType(typeof(void), StatusCodes.Status503ServiceUnavailable)]
>     public async Task<ActionResult<QueueDto>> GetQueueDepth(
> ```

This endpoint seems to get information about a queue, so I would prefer to call it `GetQueueAsync`.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 207 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_1Erc6poJakw3mOLf:-Ng_1Erc6poJakw3mOLg:bo5mk7i) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L207)):*
> ```Smalltalk
>         try
>         {
>             return Map(await _engineService.GetQueueDepthAsync(engineType, cancellationToken));
> ```

URLs are often treated as case insensitive. In this case, just the engine type part of the URL will be case sensitive. Unfortunately, we never expected to use the engine types in a URL, so they can't easily be converted to Pascal case. We have a couple of options:
1. Change the engine type values to kebab case on all endpoints (breaking change).  We convert to Pascal case for internal use or switch to using kebab case everywhere.
2. Change the engine type values to kebab case only on this endpoint. We convert to Pascal case for internal use.
3. Pass the engine type in the body or query string.
4. Require that engine types are case insensitive everywhere.
___
*[`src/Serval.Translation/Services/EngineService.cs` line 301 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_0wm54y3eVWsUmSJu:-Ng_0wm54y3eVWsUmSJv:ba3jcrp) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Services/EngineService.cs#L301)):*
> ```Smalltalk
>     }
> 
>     public async Task<Queue> GetQueueDepthAsync(string engineType, CancellationToken cancellationToken = default)
> ```

Change to `GetQueueAsync`

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 207 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_1Erc6poJakw3mOLf:-Ng_HRWp6SrnWIOZfrpH:b-mzg5hu) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L207)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

URLs are often treated as case insensitive. In this case, just the engine type part of the URL will be case sensitive. Unfortunately, we never expected to use the engine types in a URL, so they can't easily be converted to Pascal case. We have a couple of options:
1. Change the engine type values to kebab case on all endpoints (breaking change).  We convert to Pascal case for internal use or switch to using kebab case everywhere.
2. Change the engine type values to kebab case only on this endpoint. We convert to Pascal case for internal use.
3. Pass the engine type in the body or query string.
4. Require that engine types are case insensitive everywhere.
</blockquote></details>

Number 4 seemed the simplest, and it's consistent with how the engine type is passed elsewhere. If you'd rather a different solution, let me know.

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 200 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_-lBVBP2UYElm87Pq:-Ng_HQqF7xSOVHfJD51Z:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L200)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This endpoint seems to get information about a queue, so I would prefer to call it `GetQueueAsync`.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 15 at r3](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_OAs8CcUPpLhrDUSK:-Ng_OAs8CcUPpLhrDUSL:b-jfvn8i) ([raw file](https://github.com/sillsdev/serval/blob/f8f7c3b93974a9a5054dbdaa991a32f216cfbb3d/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L15)):*
> ```proto
>     rpc StartBuild(StartBuildRequest) returns (google.protobuf.Empty);
>     rpc CancelBuild(CancelBuildRequest) returns (google.protobuf.Empty);
>     rpc GetQueueDepth(GetQueueDepthRequest) returns (GetQueueDepthResponse);
> ```

This should be changed to `GetQueueSize`.
___
*[`src/Serval.Translation/Models/Queue.cs` line 6 at r3](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_McMV7HtCYJzZqv_H:-Ng_McMV7HtCYJzZqv_I:b-50n3u9) ([raw file](https://github.com/sillsdev/serval/blob/f8f7c3b93974a9a5054dbdaa991a32f216cfbb3d/src/Serval.Translation/Models/Queue.cs#L6)):*
> ```Smalltalk
> {
>     public int Size { get; set; } = default;
>     public string? EngineType {get; set;}
> ```

You should make this non-nullable and set it to `default!`. I know this is a little weird, but we expect `EngineType` to never be null. Once we move to .NET 8, we can use records and make this a `required` property, which will be clearer.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177)* status: 9 of 16 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 15 at r3](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_OAs8CcUPpLhrDUSK:-Ng_YbC20Ga3dBn1X3G9:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f8f7c3b93974a9a5054dbdaa991a32f216cfbb3d/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be changed to `GetQueueSize`.
</blockquote></details>

Done.
___
*[`src/Serval.Translation/Contracts/QueueDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_-_a-8Crq2oQFsEzC:-Ng_HPX97b1-IOqh2m1B:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Contracts/QueueDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think `Count` or `Size` would be better. I also think you should include the engine type.
</blockquote></details>

Done.
___
*[`src/Serval.Translation/Services/EngineService.cs` line 301 at r2](https://reviewable.io/reviews/sillsdev/serval/177#-Ng_0wm54y3eVWsUmSJu:-Ng_Hmpv4JiC5orl3gCj:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/b7f61e7a3b5d84580fa786e473e1058af100b64c/src/Serval.Translation/Services/EngineService.cs#L301)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Change to `GetQueueAsync`
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177#-:-Ng_imsW-F_BOBnV_xwQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
@johnml1135 Is there anything left you wanted addressed?

**Review by ddaspit — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
*[`src/Serval.Grpc/Protos/serval/translation/v1/platform.proto` line 24 at r5](https://reviewable.io/reviews/sillsdev/serval/177#-NgdNnLv3oFfhLU42Csf:-NgdNnLw0dvOZBPHUAVe:b-vjguln) ([raw file](https://github.com/sillsdev/serval/blob/7276e7ef4d05713bd1c8326d86958d9b0356fdfc/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto#L24)):*
> ```proto
>     optional double percent_completed = 3;
>     optional string message = 4;
>     optional int32 queue_depth = 5;
> ```

Size vs depth?  How are we sing these terms?

**Comment by Enkidu93** [comment]
*[`src/Serval.Grpc/Protos/serval/translation/v1/platform.proto` line 24 at r5](https://reviewable.io/reviews/sillsdev/serval/177#-NgdNnLv3oFfhLU42Csf:-NgdPlSY5OB26UwHyIn0:bpdm4j2) ([raw file](https://github.com/sillsdev/serval/blob/7276e7ef4d05713bd1c8326d86958d9b0356fdfc/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto#L24)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Size vs depth?  How are we sing these terms?
</blockquote></details>

'Depth' refers to an individual build's position within the queue whereas 'Size' refers to the overall queue size.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 2 of 7 files at r3, 6 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/177)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
:lgtm:

**Pull request merged**
