### PR TITLE
Ignore ellipses

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes https://github.com/sillsdev/serval/issues/458

Replacement for https://github.com/sillsdev/machine/pull/235.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/serval/469#-O5KnP9pCgXe60oJyL4e:-O5KnP9pCgXe60oJyL4f:b-679xrm) ([raw file](https://github.com/sillsdev/serval/blob/91a13dc822146681d63fd103480d3c328b046fe5/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L294)):*
> ```Smalltalk
>             // filter out every list that only contains completely empty rows
>             .Where(rows =>
>                 rows.Any(r =>
> ```

We also want to transform the ellipses to an empty string, so that there aren't any ellipses in the training corpus.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/serval/469#-O5KnP9pCgXe60oJyL4e:-O5NukQGABY-PEgg76mO:bs1oqc0) ([raw file](https://github.com/sillsdev/serval/blob/91a13dc822146681d63fd103480d3c328b046fe5/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L294)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We also want to transform the ellipses to an empty string, so that there aren't any ellipses in the training corpus.
</blockquote></details>

And add a test.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Comment by Enkidu93** [comment]
Sorry for the delay here. Really lost as to why one test passed locally but failed in CI :thinking:.

**Comment by johnml1135** [comment]
Do you believe there is sufficient testing?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 294 at r1](https://reviewable.io/reviews/sillsdev/serval/469#-O5KnP9pCgXe60oJyL4e:-O5PVdNO1F7kJQ8eGx6r:b-1xd986) ([raw file](https://github.com/sillsdev/serval/blob/91a13dc822146681d63fd103480d3c328b046fe5/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L294)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

And add a test.
</blockquote></details>

I believe this is sufficiently tested. I'm not sure why the test was failing previously - now it's passing.

**Review by Enkidu93 — COMMENTED** [review]
Yes. I'm happy to add more though if you have something in mind that I'm missing.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469#-:-O5PXWCm6zvr5aZXLSof:b81s770)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
The current code will only remove ellipses from text file corpora and not Paratext corpora. If you actually look at the generated corpus files in the `RunAsync_MixedSource_Paratext` test, you will find that it still contains ellipses. I added a commit that uses the `Transform` operation to clean ellipsis segments. It uses a `CleanSegment` function, which will give us someplace to do any further cleaning of segments.

We will need better unit tests, since the current unit test didn't catch the error. It would probably be good to have a specific unit test to test stripping ellipsis segments.

Also, if your branch falls behind the master branch, you can just rebase the branch on top of master. This will keep the history graph a lot cleaner.

> Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469#-:-O5Q-WkH8wrewaS94Wu3:b22yqbw)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — COMMENTED** [review]
You could use your `DummyCorpus` class to create specific unit tests for this issue. Also, I would recommend updating the `DummyCorpus` to extend `DictionaryTextCorpus` that way you don't have to have implement all of the methods.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469#-:-O5Q54X3CrBW2uJWQ3gp:bfj1d8j)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
OK! I see: `GetTrainCountAsync()` wasn't behaving as I expected - that makes sense.

Yep, OK. The way things are being tested seems a little odd. Is there a reason we can't just compare to the extracted text itself instead of relying on these counts? Or at least make that an option? I get that for some of the terms tests, the expected string would be too large, but for these toy examples, it seems like that would be more fool proof.

I'm sorry. I hit rebase in the web gui, but then when I went to the source control gui in vscode, it listed a whole bunch of outgoing commits - not sure what happened - anyways, once again, I should probably just use the command line as convenient as the guis seem haha. I apologize - I did *mean* to rebase :saluting_face:.

OK.

**Review by Enkidu93 — COMMENTED** [review]
Hmm, revisiting your idea of having the `DummyCorpus` inherit from `DictionaryTextCorpus`: I would need to override some of those methods. Can I use the `new` keyword and just hide `DictionaryTextCorpus`'s implementations? Or what did you have in mind? (Just making sure I'm following).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469#-:-O5THQHs6qAgLwBFPGZJ:b-58hifh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
For now, I've added a test using the existing file-based strategy. I still need to extend it at least a bit to cover the pretranslation filtering, but is this kind of test acceptable for now? Having more unit-test-style tests would be preferable, but the I'm concerned about using the `DummyCorpus` both for that and for the fails on/exception throwing testing. Certainly doable though, @ddaspit, if you'd prefer. Lmk.

**Comment by johnml1135** [comment]
My recommendation is to finish this quickly (this morning) to get it to QA for SF and then prioritize a refactoring of the relevant tests.

**Comment by Enkidu93** [comment]
There are now tests although like you say, refactoring at some point might be beneficial - that way, we can easily and more quickly get better coverage.

**Review by ddaspit — APPROVED** [review]
The tests are perfectly fine for now. We can always refactor things later.

> Reviewed 1 of 2 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469#-:-O5TdIgy1T8_pJ808RtG:br0795q)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/469)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
