### PR TITLE
Log trace on 400 and 500 codes

### PR DESCRIPTION
**Pull request by Enkidu93**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/102)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`src/Serval.Shared/Controllers/HttpResultFilter.cs` line 16 at r1](https://reviewable.io/reviews/sillsdev/serval/102#-Nd5qE1FB8hW_rLeKxA-:-Nd5qE1FB8hW_rLeKxA0:b-4kji3g) ([raw file](https://github.com/sillsdev/serval/blob/2298858bbb4448e8608a2e48fea2bb74adb30db3/src/Serval.Shared/Controllers/HttpResultFilter.cs#L16)):*
> ```Smalltalk
>         public override Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
>         {
>             if (context.Result is ObjectResult r && r.StatusCode / 100 > 3)
> ```

PEMDAS makes my head spin - and is it int or float math?  How about:
`if ((context.Result is ObjectResult r) && (r.StatusCode >= 400))`?

**Comment by Enkidu93** [comment]
> _[`src/Serval.Shared/Controllers/HttpResultFilter.cs` line 16 at r1](https://reviewable.io/reviews/sillsdev/serval/102#-Nd5qE1FB8hW_rLeKxA-:-Nd5qE1FB8hW_rLeKxA0:b-4kji3g) ([raw file](https://github.com/sillsdev/serval/blob/2298858bbb4448e8608a2e48fea2bb74adb30db3/src/Serval.Shared/Controllers/HttpResultFilter.cs#L16)):_
> 
> > ```smalltalk
> >         public override Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
> >         {
> >             if (context.Result is ObjectResult r && r.StatusCode / 100 > 3)
> > ```
> 
> PEMDAS makes my head spin - and is it int or float math? How about: `if ((context.Result is ObjectResult r) && (r.StatusCode >= 400))`?

Haha, sure. I can do that. I think I even switched it to a ">= 400" but must have control-z-ed.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
