### PR TITLE
Fix pretranslation filtering

### PR DESCRIPTION
**Pull request by johnml1135**
Don't train/pretranslate on other corpora if one is already defined.
Test for pretranslation filtering
This resolves https://github.com/sillsdev/serval/issues/516

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/520)

### CODE REVIEW

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
@ddaspit, I think John is hoping we can get this through today in his absence, so if you could review this ASAP + confirm or reject my review comments, I can follow up with any changes and move forward with deploying everything to QA.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/520#-:-OA2wwW2AKMZfTn3euxj:b-ul62zm)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 709 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2vQK5-To0bBhNaJDj:-OA2vQK5-To0bBhNaJDk:b-8cwx18) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/src/Serval.Translation/Services/EngineService.cs#L709)):*
> ```Smalltalk
>             }
>         }
>         return new V1.ParallelCorpus
> ```

Won't this result in corpora that have no specified filters? Would it be simpler or more readable to filter the corpora before the map function is called to include only the parallel corpora that are specified in a trainOn/pretranslate, but if there are none, just use all? Then we wouldn't have to pass new arguments either. But this works too, so either way is fine by me.
___
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 125 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2wrnrBQ61XinT7yZq:-OA2wrnrBQ61XinT7yZr:b5qrsn1) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L125)):*
> ```Smalltalk
>             true
>         );
>         _helperClient.TranslationBuildConfig.Pretranslate = [new() { CorpusId = cId2, TextIds = ["2JN.txt"] }];
> ```

Can't this be tested at the unit test level?

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/520)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 709 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2vQK5-To0bBhNaJDj:-OA3ZdhEDHo_kdEjslya:b-lifiwh) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/src/Serval.Translation/Services/EngineService.cs#L709)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Won't this result in corpora that have no specified filters? Would it be simpler or more readable to filter the corpora before the map function is called to include only the parallel corpora that are specified in a trainOn/pretranslate, but if there are none, just use all? Then we wouldn't have to pass new arguments either. But this works too, so either way is fine by me.
</blockquote></details>

Can you try implementing your approach? It sounds cleaner.
___
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 125 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2wrnrBQ61XinT7yZq:-OA3Zpo8AFjVuaSwsWp3:b-cp666x) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L125)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Can't this be tested at the unit test level?
</blockquote></details>

I agree. We should test this at the unit test level.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 709 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2vQK5-To0bBhNaJDj:-OA3miSmDu0wqOliwoBM:b-nx3hn5) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/src/Serval.Translation/Services/EngineService.cs#L709)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Can you try implementing your approach? It sounds cleaner.
</blockquote></details>

If you can make it cleaner, go for it. I was just trying to get down to logic as quickly as I could.

**Comment by johnml1135** [comment]
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 125 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2wrnrBQ61XinT7yZq:-OA3mrHd5sewmwYlBnku:b-9jvui7) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L125)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I agree. We should test this at the unit test level.
</blockquote></details>

I agree, a unit test would be great.  I would still keep this end-to-end function though, just to confirm is that the filter is actually applied IRL.

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/520)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 709 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2vQK5-To0bBhNaJDj:-OA3sjMN-r-ZC0V9uttn:bcjyedv) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/src/Serval.Translation/Services/EngineService.cs#L709)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If you can make it cleaner, go for it. I was just trying to get down to logic as quickly as I could.
</blockquote></details>

Done. This seems cleaner to me. Also, the unit tests are now passing with this implementation.
___
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 125 at r1](https://reviewable.io/reviews/sillsdev/serval/520#-OA2wrnrBQ61XinT7yZq:-OA3ssrp8p70NIpI6HS8:b-y5w5p7) ([raw file](https://github.com/sillsdev/serval/blob/af1aa56afb64c3f319ff2be659f9d6b72365713e/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L125)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I agree, a unit test would be great.  I would still keep this end-to-end function though, just to confirm is that the filter is actually applied IRL.
</blockquote></details>

Done. Yep, I agree, John. Done.

**Review by ddaspit — COMMENTED** [review]
Can we revert the temporary fix? Should we do it in this PR or a separate one?

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/520#-:-OA3t_P66Zq-Q1Zm4dAg:brd96z7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/520#-:-OA3uyUz4hsfE9wf0jp3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by Enkidu93 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/520)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
