### PR TITLE
Fix documentation 

### PR DESCRIPTION
**Pull request by johnml1135**
#327 and #321

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/331)

### CODE REVIEW

**Review by Enkidu93 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/331)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/331)* status: all files reviewed, 1 unresolved discussion

___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 915 at r1](https://reviewable.io/reviews/sillsdev/serval/331#-Nrb7i2W2JJLG5NY7KRg:-Nrb7i2W2JJLG5NY7KRh:b-wtqe16) ([raw file](https://github.com/sillsdev/serval/blob/2d71dab5fa30cf00204bd1c9bd9954e685cececb/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L915)):*
> ```Smalltalk
>     /// The download itself is created by g-zipping together the folder containing the fine tuned model
>     /// with all necessary supporting files.  This zipped folder is then named by the pattern:
>     ///  * &lt;engine_id&gt;_&lt;build_revision&gt;.tar.gz
> ```

I believe it is referred to as `model_revision` in the Serval context.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 915 at r1](https://reviewable.io/reviews/sillsdev/serval/331#-Nrb7i2W2JJLG5NY7KRg:-Nrb9EPJ6YQnUeZW0mXI:b-uh65qp) ([raw file](https://github.com/sillsdev/serval/blob/2d71dab5fa30cf00204bd1c9bd9954e685cececb/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L915)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I believe it is referred to as `model_revision` in the Serval context.
</blockquote></details>

Didn't see this until after.  Pushed fix to master.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/331)* status: all files reviewed, 1 unresolved discussion

___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 915 at r1](https://reviewable.io/reviews/sillsdev/serval/331#-Nrb7i2W2JJLG5NY7KRg:-Nrb9xiy8KrxdNoPtOJU:buomreq) ([raw file](https://github.com/sillsdev/serval/blob/2d71dab5fa30cf00204bd1c9bd9954e685cececb/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L915)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Didn't see this until after.  Pushed fix to master.
</blockquote></details>

We should fix it at some point. We want to use consistent terminology.

**Pull request merged**
