### PR TITLE
Train on everything if train_on is unspecified; add line in docs

### PR DESCRIPTION
**Pull request by Enkidu93**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 220 at r1](https://reviewable.io/reviews/sillsdev/serval/219#-Nikf6yR0P0StmYBy9eT:-Nikf6ySECHDPJQbFPIy:bfcuzyb) ([raw file](https://github.com/sillsdev/serval/blob/ffa3206b71e8425456f5d3fcc6fc383cd1722cb9/src/Serval.Translation/Services/EngineService.cs#L220)):*
> ```Smalltalk
>                                 corpus.TrainOnTextIds.Add(trainingCorpus.TextIds);
>                         }
>                         else if (trainOn?.Count == 0)
> ```

We need to check if `trainOn` is `null` here.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 220 at r1](https://reviewable.io/reviews/sillsdev/serval/219#-Nikf6yR0P0StmYBy9eT:-NikheE3ColUwoSK5bzN:b56a12d) ([raw file](https://github.com/sillsdev/serval/blob/ffa3206b71e8425456f5d3fcc6fc383cd1722cb9/src/Serval.Translation/Services/EngineService.cs#L220)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We need to check if `trainOn` is `null` here.
</blockquote></details>

If `train_on` is specified but empty, then I don't think we should train on anything. This could be a way to indicate that fine tuning is not desired.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 220 at r1](https://reviewable.io/reviews/sillsdev/serval/219#-Nikf6yR0P0StmYBy9eT:-NikkkI_41mmnyqcC-Y8:b-x9ba83) ([raw file](https://github.com/sillsdev/serval/blob/ffa3206b71e8425456f5d3fcc6fc383cd1722cb9/src/Serval.Translation/Services/EngineService.cs#L220)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If `train_on` is specified but empty, then I don't think we should train on anything. This could be a way to indicate that fine tuning is not desired.
</blockquote></details>

Like this?

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 220 at r1](https://reviewable.io/reviews/sillsdev/serval/219#-Nikf6yR0P0StmYBy9eT:-Nimcdvl7a4CKHZDzS1w:bgdrubc) ([raw file](https://github.com/sillsdev/serval/blob/ffa3206b71e8425456f5d3fcc6fc383cd1722cb9/src/Serval.Translation/Services/EngineService.cs#L220)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Like this?
</blockquote></details>

We only want to train on everything if `train_on` is not specified, so it should be:

```
else if (trainOn is null)
{
    corpus.TrainOnAll = true;
}
```

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 220 at r1](https://reviewable.io/reviews/sillsdev/serval/219#-Nikf6yR0P0StmYBy9eT:-Nio7cYe-7wEaQ1YQzkm:br1if59) ([raw file](https://github.com/sillsdev/serval/blob/ffa3206b71e8425456f5d3fcc6fc383cd1722cb9/src/Serval.Translation/Services/EngineService.cs#L220)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We only want to train on everything if `train_on` is not specified, so it should be:

```
else if (trainOn is null)
{
    corpus.TrainOnAll = true;
}
```
</blockquote></details>

Oh, yes, I misread. Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219#-:-Nio_oIY0y0uVv0s3Phl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> Has this been tested at least once?

Yes, it has. But I'm glad you asked because I reran the e2e tests and had to fix a small set-up element in the helper to make them all pass given the change to training on all when null not when empty - thank you.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
Is the comment clear then?  If the field train_on is not present, all will be used but if it is present but empty, none will be used.  Is that correct?  That appears to be what the code says.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> Is the comment clear then? If the field train_on is not present, all will be used but if it is present but empty, none will be used. Is that correct? That appears to be what the code says.

I think it's clear. If folks have issues, we can flesh it out. Strictly, the comment is correct.

**Pull request merged**
