### PR TITLE
Echo engine endpoint coverage

### PR DESCRIPTION
**Pull request by Enkidu93**
Echo engine now properly handles pretranslations.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/70)

### CODE REVIEW

**Comment by Enkidu93** [comment]
This requires one more small tweak Peter would like before merging.

**Comment by johnml1135** [comment]
Lets merge in the integration branch first, and then this one should be a piece of cake.

**Comment by Enkidu93** [comment]
I'm nearly done here. It just took a bit of back and forth to verify what the SF team wanted.

**Comment by Enkidu93** [comment]
I believe this is now functioning correctly.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
