### PR TITLE
Fix error message regarding too many builds

### PR DESCRIPTION
**Pull request by Enkidu93**
(Continuation of Jonathan Hudlow's request)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/430)

### CODE REVIEW

**Comment by johnml1135** [comment]
:lgtm:

**Comment by johnml1135** [comment]
@Enkidu93  - can you resolve the conflicting files?

**Comment by Enkidu93** [comment]
> @Enkidu93 - can you resolve the conflicting files?

Done.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
:lgtm:

**Pull request merged**
