### PR TITLE
Flag for deleting files when deleting corpus

### LINKED ISSUE #342: delete engine - and then all files
Often the files are only associated with one engine.  A client may want to auto-delete all files associated with an engine with one command.

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes #342

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 497 at r1](https://reviewable.io/reviews/sillsdev/serval/441#-O2RFNH50Ng1IReket6B:-O2RFNH50Ng1IReket6C:b6b89yb) ([raw file](https://github.com/sillsdev/serval/blob/fb7ffd6dba24ffd6414d9ba671a4ea9ccfbd4182/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L497)):*
> ```Smalltalk
>         [NotNull] string id,
>         [NotNull] string corpusId,
>         [FromQuery] bool? deleteFiles,
> ```

We want to use kebab case for query parameters. There are some older parameters that are incorrect that we need to fix, but for all new parameters we want to make sure they use kebab case.  You can explicitly specify the name using the `FromQuery` attribute, i.e. `[FromQuery(Name = "delete-files")]`.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/serval/441#-O2RBJro8avQAjXXEVP6:-O2RBJro8avQAjXXEVP7:bf2ott3) ([raw file](https://github.com/sillsdev/serval/blob/fb7ffd6dba24ffd6414d9ba671a4ea9ccfbd4182/src/Serval/src/Serval.Translation/Services/EngineService.cs#L9)):*
> ```Smalltalk
>     IRepository<Build> builds,
>     IRepository<Pretranslation> pretranslations,
>     IDataFileService dataFileService,
> ```

We want to keep the different domains (translation, data files, webhooks, etc.) loosely coupled. We have achieved this by publishing messages to a mediator that different domains can subscribe to. For an example, you can see how a translation engine corpus is updated when a data file is deleted. The `DataFileService.DeleteAsync` publishes a `DataFileDeleted` message to the mediator. The translation domain subscribes to the message by adding a consumer, i.e. `DataFileDeletedConsumer`.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 497 at r1](https://reviewable.io/reviews/sillsdev/serval/441#-O2RFNH50Ng1IReket6B:-O2RqDjs-gyKPnAs1Jxm:b-4qzamw) ([raw file](https://github.com/sillsdev/serval/blob/fb7ffd6dba24ffd6414d9ba671a4ea9ccfbd4182/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L497)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We want to use kebab case for query parameters. There are some older parameters that are incorrect that we need to fix, but for all new parameters we want to make sure they use kebab case.  You can explicitly specify the name using the `FromQuery` attribute, i.e. `[FromQuery(Name = "delete-files")]`.
</blockquote></details>

Ok, I'm on it.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/serval/441#-O2RBJro8avQAjXXEVP6:-O2RqG10ACnLF6QMTq7t:b2i0d02) ([raw file](https://github.com/sillsdev/serval/blob/fb7ffd6dba24ffd6414d9ba671a4ea9ccfbd4182/src/Serval/src/Serval.Translation/Services/EngineService.cs#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We want to keep the different domains (translation, data files, webhooks, etc.) loosely coupled. We have achieved this by publishing messages to a mediator that different domains can subscribe to. For an example, you can see how a translation engine corpus is updated when a data file is deleted. The `DataFileService.DeleteAsync` publishes a `DataFileDeleted` message to the mediator. The translation domain subscribes to the message by adding a consumer, i.e. `DataFileDeletedConsumer`.
</blockquote></details>

Yeah, I wondered about this, but I figured it was easier to just push what I had and wait for the critique 😄. Thank you for pointing me in the right direction.

**Review by Enkidu93 — COMMENTED** [review]
I think I've properly addressed the issues you mentioned, @ddaspit.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441#-:-O2VDLiT0Tnr0Q8hwCGt:b-unm4cn)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 497 at r1](https://reviewable.io/reviews/sillsdev/serval/441#-O2RFNH50Ng1IReket6B:-O2VDFsR4DaG-5jKk9qf:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/fb7ffd6dba24ffd6414d9ba671a4ea9ccfbd4182/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L497)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Ok, I'm on it.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/serval/441#-O2RBJro8avQAjXXEVP6:-O2VDHAW3MhTR8sjy7oN:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/fb7ffd6dba24ffd6414d9ba671a4ea9ccfbd4182/src/Serval/src/Serval.Translation/Services/EngineService.cs#L9)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Yeah, I wondered about this, but I figured it was easier to just push what I had and wait for the critique 😄. Thank you for pointing me in the right direction.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 466 at r2](https://reviewable.io/reviews/sillsdev/serval/441#-O2VsX-L5T-0b7vsYYmK:-O2VsX-L5T-0b7vsYYmL:b-5zczec) ([raw file](https://github.com/sillsdev/serval/blob/cfa2d14dc4c388b5ccb3bf736d18e4a82bb2d35c/src/Serval/src/Serval.Translation/Services/EngineService.cs#L466)):*
> ```Smalltalk
>             )
>             {
>                 await _mediator.Publish<DeleteDataFile>(new { DataFileId = id }, cancellationToken);
> ```

This should be `Send` instead of `Publish`, since this is an operation and not an event.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 497 at r2](https://reviewable.io/reviews/sillsdev/serval/441#-O2WE7HC1P2mcAe-zX9d:-O2WE7HC1P2mcAe-zX9e:b1r7jxp) ([raw file](https://github.com/sillsdev/serval/blob/cfa2d14dc4c388b5ccb3bf736d18e4a82bb2d35c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L497)):*
> ```Smalltalk
>         [NotNull] string id,
>         [NotNull] string corpusId,
>         [FromQuery(Name = "delete-files")] bool? deleteFiles,
> ```

You need some documentation on how this works - specifically it will delete all files associated with the engine, even if the files are associated with other engines (I assume).

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 497 at r2](https://reviewable.io/reviews/sillsdev/serval/441#-O2WE7HC1P2mcAe-zX9d:-O2WWnnOEFfXVszY6Dzk:bb3yx3y) ([raw file](https://github.com/sillsdev/serval/blob/cfa2d14dc4c388b5ccb3bf736d18e4a82bb2d35c/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L497)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

You need some documentation on how this works - specifically it will delete all files associated with the engine, even if the files are associated with other engines (I assume).
</blockquote></details>

Is that sufficient? Or would you rather put something in the remark as well?
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 466 at r2](https://reviewable.io/reviews/sillsdev/serval/441#-O2VsX-L5T-0b7vsYYmK:-O2WWv61BQAEVN6y2LDP:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/cfa2d14dc4c388b5ccb3bf736d18e4a82bb2d35c/src/Serval/src/Serval.Translation/Services/EngineService.cs#L466)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `Send` instead of `Publish`, since this is an operation and not an event.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441#-:-O2_PUsG9GaSRIRc7VH8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

**Comment by Enkidu93** [comment]
@johnml1135 , are you satisfied with the updates?

**Comment by johnml1135** [comment]
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 785 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ivgqV0qi3S_xuiP9V:-O2ivgqW3M9C6ItbXAW9:brrnh53) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L785)):*
> ```Smalltalk
>         ICollection<TranslationCorpus> resultsAfterDelete = await client.GetAllCorporaAsync(ECHO_ENGINE1_ID);
>         Assert.That(resultsAfterDelete, Has.Count.EqualTo(0));
>         Assert.That(await _env.DataFiles.GetAllAsync(), Has.Count.EqualTo(2)); //Paratext files still exist
> ```

it would be great to have a few files that were added that were not deleted.  I don't want this deleting all files, just the ones in the database.  Also, if you don't say "delete", I want to make sure that It doesn't delete them.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 6 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2ixGVW3FUs5EvjFLww:bkzovn2) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
> ```Smalltalk
>             {
>                 await _mediator.Send<DeleteDataFile>(new { DataFileId = id }, cancellationToken);
>             }
> ```

If multiple corpses have the same files, what will happen?

**Comment by Enkidu93** [comment]
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 785 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ivgqV0qi3S_xuiP9V:-O2jNANz9sAcSHi6D-Ib:b-oi1ocx) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L785)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

it would be great to have a few files that were added that were not deleted.  I don't want this deleting all files, just the ones in the database.  Also, if you don't say "delete", I want to make sure that It doesn't delete them.
</blockquote></details>

Sure, OK, I can do that! What kind of files do you mean for me to add and have not deleted? There are already Paratext files that are not deleted but have been added (see the comment in line 785). You mean Text format files?

I think the not deleting is implicitly tested elsewhere, but I'll make it explicit.

**Comment by Enkidu93** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2jMtT67l1hvTGGSklC:bs3jziu) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If multiple corpses have the same files, what will happen?
</blockquote></details>

Currently, it will remove those files from other corpora via the `DeleteAllCorpusFilesAsync` function.

**Comment by johnml1135** [comment]
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 785 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ivgqV0qi3S_xuiP9V:-O2jRJLy7-K5xQVQXVDQ:bh88x86) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L785)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sure, OK, I can do that! What kind of files do you mean for me to add and have not deleted? There are already Paratext files that are not deleted but have been added (see the comment in line 785). You mean Text format files?

I think the not deleting is implicitly tested elsewhere, but I'll make it explicit.
</blockquote></details>

Ah I see the other files now....

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 785 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ivgqV0qi3S_xuiP9V:-O2jRptdEmKuOn4emr3I:b-11uwyk) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L785)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ah I see the other files now....
</blockquote></details>

Done. Added a test.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2jzZu76hLQYAj-kozL:bkfnr3i) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Currently, it will remove those files from other corpora via the `DeleteAllCorpusFilesAsync` function.
</blockquote></details>

Specifically imagine that two corporas on the same engine each have the same file.  I believe that two "delete file 123" commands would be sent out.  This is fine, I just probably want handling that if a file is deleted even if it doesn't exist anymore, that it just silently continues on rather than crashing and not deleting the other files that are in the queue.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2k73o_24-jduWgSv0b:bbg8twj) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Specifically imagine that two corporas on the same engine each have the same file.  I believe that two "delete file 123" commands would be sent out.  This is fine, I just probably want handling that if a file is deleted even if it doesn't exist anymore, that it just silently continues on rather than crashing and not deleting the other files that are in the queue.
</blockquote></details>

Further, what about two different engines that use the same file? Right now, it will silently delete the file from the corpus in the other engine, which might be an unintended side effect for the calling application. Maybe we should only delete the file if this is the last engine that is referencing the file. This seems to be getting pretty complicated. I don't want to add something that creates more problems than it solves. What is the motivation for this feature? Did the SF team specifically request it?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.DataFiles/Consumers/DeleteDataFileConsumer.cs` line 9 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ix7VkD0MdDz69iTf0:-O2kIKp8-qcJft_v2s7P:bgwy5es) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.DataFiles/Consumers/DeleteDataFileConsumer.cs#L9)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm not sure how that could happen. Once the corpus is deleted and all the files have been deleted (and removed from other corpora), there wouldn't be a way to get at this code and delete those files. If that were to happen, it would throw an error (I believe) which would appear in the logs but not bubble up and break any code publishing to this consumer.
</blockquote></details>

https://masstransit.io/documentation/concepts/exceptions - are we handling this exception properly?  If there is no file, we want to just stop trying.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2kQPg_9ET9LJxNTOgQ:beqrfok) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Further, what about two different engines that use the same file? Right now, it will silently delete the file from the corpus in the other engine, which might be an unintended side effect for the calling application. Maybe we should only delete the file if this is the last engine that is referencing the file. This seems to be getting pretty complicated. I don't want to add something that creates more problems than it solves. What is the motivation for this feature? Did the SF team specifically request it?
</blockquote></details>

Right. It is a little sketchy. I don't know that SF reuses file ids across engines like that though, do they? The flag does default to false, so it shouldn't change any behavior for now. But I could see the utility when wanting to quickly remove all corpus-related data (i.e., not end up with lots of orphaned data files). I don't know about the requirement though, no. @johnml1135 would have to answer.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.DataFiles/Consumers/DeleteDataFileConsumer.cs` line 9 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ix7VkD0MdDz69iTf0:-O2kQFjm7PVN-S5IZPcY:b76477u) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.DataFiles/Consumers/DeleteDataFileConsumer.cs#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

https://masstransit.io/documentation/concepts/exceptions - are we handling this exception properly?  If there is no file, we want to just stop trying.
</blockquote></details>

Yes, I was looking in the same place. I don't think that retries are configured by default, so we should be fine.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2krdq6Dmar1FyPUKHY:bjjurii) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Right. It is a little sketchy. I don't know that SF reuses file ids across engines like that though, do they? The flag does default to false, so it shouldn't change any behavior for now. But I could see the utility when wanting to quickly remove all corpus-related data (i.e., not end up with lots of orphaned data files). I don't know about the requirement though, no. @johnml1135 would have to answer.
</blockquote></details>

It was more relevant (and requested) when Peter was uploading a file per chapter and there were thousands of files.  It still has value, but less so now.  Is there a mapping from files to engines?  Can we easily do the logic "delete if it is the last engine holding it"?

**Comment by Enkidu93** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2y_znU8vGZQ-OYVfMe:b-x4g8f4) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It was more relevant (and requested) when Peter was uploading a file per chapter and there were thousands of files.  It still has value, but less so now.  Is there a mapping from files to engines?  Can we easily do the logic "delete if it is the last engine holding it"?
</blockquote></details>

I see. One simple thing we could do (for now anyways) would be to only delete files that are not associated with other corpora.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2zHQWJDRECweim3oMD:b4309q7) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I see. One simple thing we could do (for now anyways) would be to only delete files that are not associated with other corpora.
</blockquote></details>

Will SF use this feature if we add it? If not, I think we should defer this feature until we have clearer requirements.

**Comment by Enkidu93** [comment]
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)_ status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)
> 
> _[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2zHQWJDRECweim3oMD:b4309q7) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):_
> Previously, Enkidu93 (Eli C. Lowry) wrote…
> 
> Will SF use this feature if we add it? If not, I think we should defer this feature until we have clearer requirements.

Who should we ask? Peter?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2zQl-w93LLBDEGqvnC:b-oge4ud) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Who should we ask? Peter?
</blockquote></details>

Yes, Peter would be right person to ask.

**Comment by Enkidu93** [comment]
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 467 at r3](https://reviewable.io/reviews/sillsdev/serval/441#-O2ixGVW3FUs5EvjFLwv:-O2zxZXr4AslfcoNkiYX:b33lybq) ([raw file](https://github.com/sillsdev/serval/blob/90ab232b488c2b20d68efe1a9a433fbd03385ef0/src/Serval/src/Serval.Translation/Services/EngineService.cs#L467)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, Peter would be right person to ask.
</blockquote></details>

OK, so the word is that: 1. This would still be helpful/convenient and 2. SF never uses the same data file across engines (not to say some other user of Serval couldn't).

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
@johnml1135 Was it worth changing it so it only deletes not-shared-between-engines files? I guess it's at least safe since it's not the default behavior to delete files anyways.

**Comment by johnml1135** [comment]
It's not the default behavior and it documents what it actually does.

**Review by ddaspit — COMMENTED** [review]
I agree with @johnml1135. We document the behavior clearly and it meets SF's current requirements. If the requirements change in the future, we can re-evaluate.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/441#-:-O33cG1BAlI1zkWqsqCn:b-wskhne)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
