### PR TITLE
Update machine to 3.5.1 and small bug

### PR DESCRIPTION
**Pull request by johnml1135**
* Fix Async stream write bug for S3 buckets

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)

### CODE REVIEW

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/serval/546#-OCeWSTF3dzOTdiureLy:-OCeWSTF3dzOTdiureLz:b8ylgey) ([raw file](https://github.com/sillsdev/serval/blob/0e96e573746318b4e9374c9a21debbca2977b3be/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L97)):*
> ```Smalltalk
>             buildOptionsObject = JsonSerializer.Deserialize<JsonObject>(buildOptions);
> 
>         using MemoryStream sourceStream = new();
> ```

What exactly is prompting this change?

**Review by Enkidu93 — COMMENTED** [review]
This is only needed for `train` and not for `pretranslate`?

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546#-:-OCeXy_DAjWmoHEehg2z:b59ear2)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/serval/546#-OCeWSTF3dzOTdiureLy:-OCeamUSDio2UBbwBxs1:b-s9g8su) ([raw file](https://github.com/sillsdev/serval/blob/0e96e573746318b4e9374c9a21debbca2977b3be/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L97)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

What exactly is prompting this change?
</blockquote></details>

Much crashing - it's trying to call Write on the S3StreamWriter (NotImplementedException).

**Review by johnml1135 — COMMENTED** [review]
This brings it back to what it was before.  For some reason, the Json writer works async.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546#-:-OCeae4a-XpoJdKncOMt:bi1gx8h)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Enkidu93)

**Review by Enkidu93 — APPROVED** [review]
OK

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546#-:-OCed3r2-Om7dMbg3Vwz:b32w0x)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 116 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCeeNubADDNP04bTARS:-OCeeNubADDNP04bTART:b-46g8ju) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L116)):*
> ```Smalltalk
>                 if (row.SourceSegment.Length > 0 || row.TargetSegment.Length > 0)
>                 {
>                     await sourceTrainWriter.WriteLineAsync(row.SourceSegment);
> ```

`WriteLineAsync` uses the OS-specific newline characters. I would prefer that we revert to the previous behavior where it always uses `\n`, so that the behavior is consistent across platforms.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCedYNm0DZLNM7arAEw:b-qlmgdv) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
> ```Smalltalk
>                 if (row.SourceSegment.Length > 0 && row.TargetSegment.Length == 0)
>                 {
>                     pretranslateWriter.WriteStartObject();
> ```

I spent a bit of time trying to understand how to properly use `Utf8JsonWriter` in an async context. This class is intended for low-level, optimized use cases. It does not automatically flush the buffer to the underlying stream. It only writes when the class is disposed or `FlushAsync` is explicitly called. In order to avoid writing all pretranslations to memory before flushing, we should periodically call `FlushAsync`. We can use the `BytesPending` property to flush after "x" amount of data is in the buffer.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCegp3ZEUkwIwHdGg-W:brvqa2r) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I spent a bit of time trying to understand how to properly use `Utf8JsonWriter` in an async context. This class is intended for low-level, optimized use cases. It does not automatically flush the buffer to the underlying stream. It only writes when the class is disposed or `FlushAsync` is explicitly called. In order to avoid writing all pretranslations to memory before flushing, we should periodically call `FlushAsync`. We can use the `BytesPending` property to flush after "x" amount of data is in the buffer.
</blockquote></details>

We could flush every time 4096 (or something like that) bytes are pending.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 116 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCeeNubADDNP04bTARS:-OCekCS73aK9l3b9vNa2:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L116)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`WriteLineAsync` uses the OS-specific newline characters. I would prefer that we revert to the previous behavior where it always uses `\n`, so that the behavior is consistent across platforms.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCeogwh-98go5fy0bSs:bo5atv3) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We could flush every time 4096 (or something like that) bytes are pending.
</blockquote></details>

No we can't - the S3Writer itself breaks up the parts and has to upload everything in one go - otherwise we get a:

Amazon.S3.AmazonS3Exception: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCetsFkEBCRrrOW68xS:b-3xeldt) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

No we can't - the S3Writer itself breaks up the parts and has to upload everything in one go - otherwise we get a:

Amazon.S3.AmazonS3Exception: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
</blockquote></details>

I'm confused. The `S3WriteStream` is specifically designed to upload in chunks. If we are receiving an exception from writing to the stream multiple times, then it sounds like a bug. @Enkidu93 Do you have any idea what is going on here?

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCez-l01GJ9UrDV9TKM:b-lj2wvn) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm confused. The `S3WriteStream` is specifically designed to upload in chunks. If we are receiving an exception from writing to the stream multiple times, then it sounds like a bug. @Enkidu93 Do you have any idea what is going on here?
</blockquote></details>

I remember working on this about 6 months ago. The S3 bucket interface was finicky. They really want you to have the whole file ready before you start writing anything. You can break it into pieces, but all of the pieces need to be the predefined size. We could implement double buffering, but that would add more complexity.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCezwPs7pWeuKwLTb9_:b-gkekxd) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I remember working on this about 6 months ago. The S3 bucket interface was finicky. They really want you to have the whole file ready before you start writing anything. You can break it into pieces, but all of the pieces need to be the predefined size. We could implement double buffering, but that would add more complexity.
</blockquote></details>

I think I know how I would do it. I will implement the double buffering in the S3 writer.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCf-V8L1tGZnRlsz7gz:b-4ys6xz) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I think I know how I would do it. I will implement the double buffering in the S3 writer.
</blockquote></details>

You mentioned getting an `AmazonS3Exception`: What line is throwing that? Or could you point me to a failed E2E?

OK, seems like you have a plan - what precisely do you think is going wrong that having two buffers would fix?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OChxJzh0FgAlA6HRqVk:b-q59pzw) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

You mentioned getting an `AmazonS3Exception`: What line is throwing that? Or could you point me to a failed E2E?

OK, seems like you have a plan - what precisely do you think is going wrong that having two buffers would fix?
</blockquote></details>

Can you give more details about what is happening? I don't understand what "have the whole file ready" means. It doesn't sound like double buffering is the right solution.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OChygXfAIopDLm3W-_q:bv1e47t) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Can you give more details about what is happening? I don't understand what "have the whole file ready" means. It doesn't sound like double buffering is the right solution.
</blockquote></details>

It is more likely that we are simply calling the S3 API incorrectly.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OChuhKw8I15cKwXWSy5:b-ne4nq) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is more likely that we are simply calling the S3 API incorrectly.
</blockquote></details>

I updated S3Writer - now it will break any stream written to it into parts of MaxUploadSize, while keeping the internal stream size also capped.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCi0AWM0xx7Wx3Xwovb:b-7zo709) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I updated S3Writer - now it will break any stream written to it into parts of MaxUploadSize, while keeping the internal stream size also capped.
</blockquote></details>

I think I understand what is going on. S3 has a minimum part size of 5MB, unless it is the last part of the file, so we need to buffer the stream until we have 5MB of data to send a part. Is that correct?

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 126 at r3](https://reviewable.io/reviews/sillsdev/serval/546#-OCedYNm0DZLNM7arAEv:-OCi0xxt-R3posll8UbW:bhdnk50) ([raw file](https://github.com/sillsdev/serval/blob/688607800f86461ee86e7b95e148c54f03cecf94/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think I understand what is going on. S3 has a minimum part size of 5MB, unless it is the last part of the file, so we need to buffer the stream until we have 5MB of data to send a part. Is that correct?
</blockquote></details>

Yes - https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/546#-:-OCi5LMr9jxN8WSIjn5-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Pull request merged**
