### PR TITLE
Expand documentation on valid text files

### PR DESCRIPTION
**Pull request by Enkidu93**
Note: This was part of earlier work done when addressing the issue of strict parsing before it was decided that Serval should not validate files. It would still be beneficial to incorporate.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/176)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/176)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/serval/176#-NgPkqznDvXlmGmEJAKP:-NgPkqznDvXlmGmEJAKQ:b-c3zpnh) ([raw file](https://github.com/sillsdev/serval/blob/ef2d43f5d6f0cfe31ffe1f70c81e519e85a2a277/src/Serval.DataFiles/Controllers/DataFilesController.cs#L97)):*
> ```Smalltalk
>     ///     > verse_001_006	(tab) Ἀγγέλους τε τοὺς μὴ τηρήσαντας τὴν ἑαυτῶν ἀρχήν , ἀλλὰ (tab) ss
>     ///     > verse_001_007 (tab) Ὡς Σόδομα καὶ Γόμορρα , καὶ αἱ περὶ αὐτὰς πόλεις (tab) ss
>     ///   * Otherwise, *no tabs* should be used in the file and a unique identifier will generated for each translation unit based on the linenumber.
> ```

I think you missed a space in `linenumber`.

**Comment by Enkidu93** [comment]
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/serval/176#-NgPkqznDvXlmGmEJAKP:-NgPm8a492sWVaiyuCI4:b-wgyldc) ([raw file](https://github.com/sillsdev/serval/blob/ef2d43f5d6f0cfe31ffe1f70c81e519e85a2a277/src/Serval.DataFiles/Controllers/DataFilesController.cs#L97)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think you missed a space in `linenumber`.
</blockquote></details>

Oh, thank you! Weirdly spellcheck did not catch that.

**Comment by Enkidu93** [comment]
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/serval/176#-NgPkqznDvXlmGmEJAKP:-NgPmCKHCroCsvLGp_Ks:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ef2d43f5d6f0cfe31ffe1f70c81e519e85a2a277/src/Serval.DataFiles/Controllers/DataFilesController.cs#L97)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Oh, thank you! Weirdly spellcheck did not catch that.
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 95 at r2](https://reviewable.io/reviews/sillsdev/serval/176#-NgPmnlNDkZs2YIJoh7p:-NgPmnlNDkZs2YIJoh7q:b-masls0) ([raw file](https://github.com/sillsdev/serval/blob/63c0d3d34c28f9dbc2d2790211f6a9c2b0c70e9b/src/Serval.DataFiles/Controllers/DataFilesController.cs#L95)):*
> ```Smalltalk
>     ///   * If a line contains a tab, characters before the tab are used as a unique identifier for the line, characters after the tab are understood as the content of the verse, and if there is another tab following the verse content, characters after this second tab are assumed to be column codes like "ss" etc. for sectioning and other formatting. See this example of a tab-delimited text file:
>     ///     > verse_001_005 (tab) Ὑπομνῆσαι δὲ ὑμᾶς βούλομαι , εἰδότας ὑμᾶς ἅπαξ τοῦτο
>     ///     > verse_001_006	(tab) Ἀγγέλους τε τοὺς μὴ τηρήσαντας τὴν ἑαυτῶν ἀρχήν , ἀλλὰ (tab) ss
> ```

there actually is a tab in "verse_001_006	(tab)".  that should be replaced with a space.

**Comment by Enkidu93** [comment]
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 95 at r2](https://reviewable.io/reviews/sillsdev/serval/176#-NgPmnlNDkZs2YIJoh7p:-NgPo90KBlAOm10uMJI_:be7qhbd) ([raw file](https://github.com/sillsdev/serval/blob/63c0d3d34c28f9dbc2d2790211f6a9c2b0c70e9b/src/Serval.DataFiles/Controllers/DataFilesController.cs#L95)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

there actually is a tab in "verse_001_006	(tab)".  that should be replaced with a space.
</blockquote></details>

Thank you! Done.

**Comment by johnml1135** [comment]
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 98 at r2](https://reviewable.io/reviews/sillsdev/serval/176#-NgPoZKO4nsmyLdYFkb_:-NgPoZKO4nsmyLdYFkba:bim08t) ([raw file](https://github.com/sillsdev/serval/blob/63c0d3d34c28f9dbc2d2790211f6a9c2b0c70e9b/src/Serval.DataFiles/Controllers/DataFilesController.cs#L98)):*
> ```Smalltalk
>     ///     > verse_001_007 (tab) Ὡς Σόδομα καὶ Γόμορρα , καὶ αἱ περὶ αὐτὰς πόλεις (tab) ss
>     ///   * Otherwise, *no tabs* should be used in the file and a unique identifier will generated for each translation unit based on the line number.
>     /// * **Paratext**: A complete, zipped Paratext project
> ```

There is little to no documentation online as to how to backup and restore a paratext project - apart from a few old pdf's made of older versions.  All the advice is to not use backup/restore but rather use the paratext send/receive server.  I would be inclined to either leave the enhanced documentation here, or refer to a specific url (if we can find one).

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/176)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/176)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/176)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/176)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/176#-:-NgQGmnZ-s4wSP_ejFNY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
