### PR TITLE
Do not train/pretranslate all if textIds is an empty array

### LINKED ISSUE #383: Already written text is not pretranslated if no trainOn books are specified
#370 added the ability to pre-translate text that was previously translated. This works perfectly, if a user specifies the books to train on.

However, if no books are specified in `trainOn`, then the old behavior where only blank segments in the target are translated occurs.

For example the following build:
```json
{
    "id": "663935b2d3673074e65b4cbf",
    "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb/builds/663935b2d3673074e65b4cbf",
    "revision": 9,
    "engine": {
      "id": "663935afd3673074e65b4cbb",
      "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb"
    },
    "trainOn": [
      {
        "corpus": {
          "id": "663935b2d3673074e65b4cbe",
          "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb/corpora/663935b2d3673074e65b4cbe"
        },
        "textIds": []
      }
    ],
    "pretranslate": [
      {
        "corpus": {
          "id": "663935b2d3673074e65b4cbe",
          "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb/corpora/663935b2d3673074e65b4cbe"
        },
        "textIds": [
          "PHM"
        ]
      }
    ],
    "step": 0,
    "percentCompleted": 1,
    "message": "Completed",
    "queueDepth": 0,
    "state": "Completed",
    "dateFinished": "2024-05-06T20:08:56.786Z",
    "options": {
      "max_steps": 20
    }
  }
```

Returns the following USFM for https://qa.serval-api.org/api/v1/translation/engines/663935afd3673074e65b4cbb/corpora/663935b2d3673074e65b4cbe/pretranslations/PHM/usfm?text-origin=OnlyPretranslated:
```
\id PHM - Paipera Tapu Back Translation
\c 1
\v 1 Paul, a prisoner of Christ Jesus, and Timothy our brother,
\v 2
\v 3
\v 4
\v 5
\v 6
\v 7
\v 8
\v 9
\v 10
\v 11
\v 12
\v 13
\v 14
\v 15
\v 16
\v 17
\v 18
\v 19
\v 20
\v 21
\v 22
\v 23
\v 24
\v 25
```

### PR DESCRIPTION
**Pull request by ddaspit**
- only train/pretranslate all if both textIds and scriptureRange are not specified
- fixes #383

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/390)

### CODE REVIEW

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/390)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 235 at r1](https://reviewable.io/reviews/sillsdev/serval/390#-Ny3Q1WMC4rwYK-TdkOF:-Ny3Q1WMC4rwYK-TdkOG:b8w044k) ([raw file](https://github.com/sillsdev/serval/blob/7d6f2bea421b4547cb36763a5fab96eb7f45bf96/src/Serval.Translation/Services/EngineService.cs#L235)):*
> ```Smalltalk
>                         {
>                             corpus.PretranslateAll =
>                                 pretranslateCorpus.TextIds is null && pretranslateCorpus.ScriptureRange is null;
> ```

This looks great - should there be a test confirming that it works like this?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/390)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 235 at r1](https://reviewable.io/reviews/sillsdev/serval/390#-Ny3Q1WMC4rwYK-TdkOF:-Ny6fQ5f86IESHF1046D:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/7d6f2bea421b4547cb36763a5fab96eb7f45bf96/src/Serval.Translation/Services/EngineService.cs#L235)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This looks great - should there be a test confirming that it works like this?
</blockquote></details>

Done.

**Comment by johnml1135** [comment]
This should also resolve #385 - to pretranslate on all, both textId and ScriptureRange need to be null, not just textId.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/390)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
