### PR TITLE
Key terms support

### PR DESCRIPTION
**Pull request by Enkidu93**
Minor fixes to support changes in the Machine PR. In general, if you could leave the parallel PRs open until both are approved, that might be helpful.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/Serval.E2ETests/data/TestProject.zip` line 0 at r1](https://reviewable.io/reviews/sillsdev/serval/229#-Nkb7eP6Cfmc5C69Va4x:-Nkb7eP6Cfmc5C69Va4y:b-xoiaa6) ([raw file](https://github.com/sillsdev/serval/blob/32749758261fe0b3ced63efbcf826543b523d37b/tests/Serval.E2ETests/data/TestProject.zip#L0)):*
We don't want to check in binary files. Can you check in the contents, and create the zip file in the test?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/Serval.E2ETests/data/TestProject.zip` line  at r1](https://reviewable.io/reviews/sillsdev/serval/229#-Nkb7eP6Cfmc5C69Va4x:-Nkb9tKW8oC2-bpZVUkO:b4ponv7) ([raw file](https://github.com/sillsdev/serval/blob/32749758261fe0b3ced63efbcf826543b523d37b/tests/Serval.E2ETests/data/TestProject.zip#L)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, there was already a zip, but I can do that if you like.
</blockquote></details>

I should have caught it on the PR that added this file. Unfortunately, every time we make changes to this file it adds 2MB to our repo size. I would like to correct that sooner rather than later.

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 365 at r2](https://reviewable.io/reviews/sillsdev/serval/229#-Nkp4ACx9xoeeVsdQzw1:-Nkp4GnI2LkPvaXaLU5d:bw10qew) ([raw file](https://github.com/sillsdev/serval/blob/8e170361c1ff2a2763c05905ad832d92e5772ea5/tests/Serval.E2ETests/ServalApiTests.cs#L365)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I like how you zip up the files so that changes to USFM can be tracked in git!
</blockquote></details>

That is, zip them up during the test and leave them uncompressed in the repo.

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 400 at r2](https://reviewable.io/reviews/sillsdev/serval/229#-Nkp4Q1uA5OD7_EJGdaD:-Nkp4Q1uA5OD7_EJGdaE:b-o06sci) ([raw file](https://github.com/sillsdev/serval/blob/8e170361c1ff2a2763c05905ad832d92e5772ea5/tests/Serval.E2ETests/ServalApiTests.cs#L400)):*
> ```Smalltalk
>             new PretranslateCorpusConfig { CorpusId = corpus.Id, TextIds = new string[] { "JHN", "REV" } }
>         );
>         _helperClient.TranslationBuildConfig.Options = "{\"max_steps\":10, \"use_key_terms\":true}";
> ```

If it is added by default, why include it here?  How can you test that it is actually being used?

**Comment by johnml1135** [comment]
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 400 at r2](https://reviewable.io/reviews/sillsdev/serval/229#-Nkp4Q1uA5OD7_EJGdaD:-Nkq3Rvk75rcSH9SZDmR:b-r9sz8) ([raw file](https://github.com/sillsdev/serval/blob/8e170361c1ff2a2763c05905ad832d92e5772ea5/tests/Serval.E2ETests/ServalApiTests.cs#L400)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I can remove it if you like - it shouldn't make a difference. The purpose of this test isn't really to capture that functionality/logic - that's covered in the `NmtPreprocessBuildJobTests`. I figured leaving it explicit might be beneficial, and it's also more robust if we were to change the defaults.
</blockquote></details>

That's fine.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 24 of 25 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 780 at r2](https://reviewable.io/reviews/sillsdev/serval/229#-Nkp2_599KjdptX58Zo7:-Nkq5739-BIUCBkhSYaA:bfj4c0m) ([raw file](https://github.com/sillsdev/serval/blob/8e170361c1ff2a2763c05905ad832d92e5772ea5/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L780)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done. Also updated the Wiki.
</blockquote></details>

It would probably be good to mention that we only include proper names.
___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 359 at r3](https://reviewable.io/reviews/sillsdev/serval/229#-Nkq3szD680fijWEhEVe:-Nkq3szD680fijWEhEVf:b-wdg6za) ([raw file](https://github.com/sillsdev/serval/blob/faaf0a3ba343dfb8237c4d196cda1096e88edd82/tests/Serval.E2ETests/ServalApiTests.cs#L359)):*
> ```Smalltalk
>     {
>         await _helperClient!.ClearEngines();
>         ZipFile.CreateFromDirectory("../../../data/TestProject", "TestProject.zip");
> ```

We should wrap all of this in a `try/finally` so that we ensure that the zip files are deleted.

```
try
{
    ZipFile.CreateFromDirectory("../../../data/TestProject", "TestProject.zip");
    ZipFile.CreateFromDirectory("../../../data/TestProjectTarget", "TestProjectTarget.zip");
    // upload files
    ...
}
finally
{
    if (File.Exists("TestProject.zip"))
        File.Delete("TestProject.zip");
    if (File.Exists("TestProjectTarget.zip"))
        File.Delete("TestProjectTarget.zip");
}
```
It would also be good to create these files in a temp directory.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 780 at r2](https://reviewable.io/reviews/sillsdev/serval/229#-Nkp2_599KjdptX58Zo7:-Nkq8OWL5ThGnu17Jra-:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/8e170361c1ff2a2763c05905ad832d92e5772ea5/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L780)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would probably be good to mention that we only include proper names.
</blockquote></details>

Done.
___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 359 at r3](https://reviewable.io/reviews/sillsdev/serval/229#-Nkq3szD680fijWEhEVe:-Nkq8Nct4YcK2Igqw04x:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/faaf0a3ba343dfb8237c4d196cda1096e88edd82/tests/Serval.E2ETests/ServalApiTests.cs#L359)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should wrap all of this in a `try/finally` so that we ensure that the zip files are deleted.

```
try
{
    ZipFile.CreateFromDirectory("../../../data/TestProject", "TestProject.zip");
    ZipFile.CreateFromDirectory("../../../data/TestProjectTarget", "TestProjectTarget.zip");
    // upload files
    ...
}
finally
{
    if (File.Exists("TestProject.zip"))
        File.Delete("TestProject.zip");
    if (File.Exists("TestProjectTarget.zip"))
        File.Delete("TestProjectTarget.zip");
}
```
It would also be good to create these files in a temp directory.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 359 at r3](https://reviewable.io/reviews/sillsdev/serval/229#-Nkq3szD680fijWEhEVe:-NkqLD-E6rfKyKxSIQ2u:b-v0dus6) ([raw file](https://github.com/sillsdev/serval/blob/faaf0a3ba343dfb8237c4d196cda1096e88edd82/tests/Serval.E2ETests/ServalApiTests.cs#L359)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I should have been more clear. I mean in the operating systems' temp folder. You can get it using [`Path.GetTempPath`](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-8.0&tabs=windows).

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 364 at r5](https://reviewable.io/reviews/sillsdev/serval/229#-NkqRhSHEadCuR3mTeWv:-NkqRhSHEadCuR3mTeWw:b-h8g6w8) ([raw file](https://github.com/sillsdev/serval/blob/d5aa07c776eeb3b2757c5e698bb0663f8f5d06e8/tests/Serval.E2ETests/ServalApiTests.cs#L364)):*
> ```Smalltalk
>         try
>         {
>             ZipFile.CreateFromDirectory("../../../data/TestProject", $"{tempDirectory}/TestProject.zip");
> ```

You should use `Path.Combine` to construct paths.

**Comment by Enkidu93** [comment]
> > Reviewed 1 of 1 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)_ status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)
> 
> _[`tests/Serval.E2ETests/ServalApiTests.cs` line 364 at r5](https://reviewable.io/reviews/sillsdev/serval/229#-NkqRhSHEadCuR3mTeWv:-NkqRhSHEadCuR3mTeWw:b-h8g6w8) ([raw file](https://github.com/sillsdev/serval/blob/d5aa07c776eeb3b2757c5e698bb0663f8f5d06e8/tests/Serval.E2ETests/ServalApiTests.cs#L364)):_
> 
> > ```smalltalk
> >         try
> >         {
> >             ZipFile.CreateFromDirectory("../../../data/TestProject", $"{tempDirectory}/TestProject.zip");
> > ```
> 
> You should use `Path.Combine` to construct paths.

For all paths? E.g., including "../../somedir/somefile.ext"? Or in regards to the `tempDirectory`? If you want it everywhere, I should change it a few other places as well.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 364 at r5](https://reviewable.io/reviews/sillsdev/serval/229#-NkqRhSHEadCuR3mTeWv:-Nkr46uR0QRwHKtB7kwd:b-je9mf4) ([raw file](https://github.com/sillsdev/serval/blob/d5aa07c776eeb3b2757c5e698bb0663f8f5d06e8/tests/Serval.E2ETests/ServalApiTests.cs#L364)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, you should use it everywhere.
</blockquote></details>

OK, done. In Machine, I've also changed it except in the uses of shared service `OpenRead` following your usage of `OpenWrite` in the build job.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/229#-:-NkuxrxF82oumNdc-MGT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
