### PR TITLE
Config passing

### LINKED ISSUE #45: Configure builds for saving models, inference only and custom starting points
Without building - just direct.  How do we choose between these different models, etc?  How do we configure?  A new engine type?  A new "NmtInference" type?

### PR DESCRIPTION
**Pull request by Enkidu93**
Fixes #45 .

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng-_FEP4QTECmsX3KDD:bnbsygj) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
> ```Smalltalk
> global using Microsoft.Extensions.Configuration;
> global using Microsoft.Extensions.Options;
> global using Newtonsoft.Json;
> ```

Are we using JSON.NET? I would prefer to use System.Text.Json for everything.
___
*[`src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_Txb7Oqdym9Cwxp_:-Ng-_Txb7Oqdym9Cwxpa:b-gejtan) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs#L1)):*
> ```Smalltalk
> using System.Text.Json.Nodes;
> ```

I don't think this using is necessary.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_ZahBKSj8KvJ6O5j:-Ng-_ZahBKSj8KvJ6O5k:b-6pw56w) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1)):*
> ```Smalltalk
> using System.Text.Json;
> ```

Add this to the global usings.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng0FM4D031myPzTNNl6:bub675k) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Are we using JSON.NET? I would prefer to use System.Text.Json for everything.
</blockquote></details>

I was using it. `JsonConvert.(De)SerializeObject` has slightly different behavior that makes it convenient to use here. I can try and find a workaround if you like though.

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng0FbRO0RheQU_q7kQK:b-c28m67) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I was using it. `JsonConvert.(De)SerializeObject` has slightly different behavior that makes it convenient to use here. I can try and find a workaround if you like though.
</blockquote></details>

...than `JsonSerializer.(De)Serialize` that is.

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng0_WZfAKFp_dqlauQI:b78z65) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

...than `JsonSerializer.(De)Serialize` that is.
</blockquote></details>

So do you want me to do so? A workaround is not evident to me, but I'm happy to dig.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng0vtdx49hAU6c2J50H:bame057) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

So do you want me to do so? A workaround is not evident to me, but I'm happy to dig.
</blockquote></details>

What does JSON.NET do that System.Text.Json can't?

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng4eVJR3X91-F1Hq2of:b-l5c507) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What does JSON.NET do that System.Text.Json can't?
</blockquote></details>

Sorry for the delay: For security reasons (ostensibly), it doesn't serialize values in a way that preserves their types (everything becomes JsonElement) which MongoDB can't handle. We are already using JSON.NET in MemoryRepo and ServalClientHelper. I did find and official workaround though.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng4jL-B9uuQhwI9K-Kj:b-wqaoef) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sorry for the delay: For security reasons (ostensibly), it doesn't serialize values in a way that preserves their types (everything becomes JsonElement) which MongoDB can't handle. We are already using JSON.NET in MemoryRepo and ServalClientHelper. I did find and official workaround though.
</blockquote></details>

That's fine. I just wanted to understand the reasoning. My hope is that System.Text.Json would someday get to the point where we wouldn't need JSON.NET anymore. I am trying to avoid adding any more dependencies on it, but in this case, it sounds like it is warranted.

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Usings.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_FEP4QTECmsX3KDC:-Ng4oCcz8ZrkHNryPtCp:blz0h4a) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Usings.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

That's fine. I just wanted to understand the reasoning. My hope is that System.Text.Json would someday get to the point where we wouldn't need JSON.NET anymore. I am trying to avoid adding any more dependencies on it, but in this case, it sounds like it is warranted.
</blockquote></details>

OK, well, I just pushed a solution that avoids JSON.NET. But if you'd prefer the simpler solution with System.Text.Json, let me know and I can revert it.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_Txb7Oqdym9Cwxp_:-Ng59gtu55JEhb2DK6qA:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Contracts/TranslationBuildConfigDto.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this using is necessary.
</blockquote></details>

Done.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/152#-Ng-_ZahBKSj8KvJ6O5j:-Ng59hf80Y_Tl-LX8lnY:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/5337e8aebd7e750f6a867c51196f1d03c18fb9df/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Add this to the global usings.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval.Shared/Utils/ObjectToInferredTypesConverter.cs` line 1 at r3](https://reviewable.io/reviews/sillsdev/serval/152#-Ng5DTTo1_zTDxM81Asw:-Ng5DTTp2wL39pSkwrzo:b-747dtt) ([raw file](https://github.com/sillsdev/serval/blob/ab748363b769db0ff54f4cde78ac110eb62de082/src/Serval.Shared/Utils/ObjectToInferredTypesConverter.cs#L1)):*
> ```Smalltalk
> public class ObjectToInferredTypesConverter : JsonConverter<object>
> ```

You forgot to specify a namespace.
___
*[`src/Serval.Translation/Usings.cs` line 26 at r3](https://reviewable.io/reviews/sillsdev/serval/152#-Ng5D_-S2gsSNYtiqYCD:-Ng5D_-S2gsSNYtiqYCE:b-d48z4x) ([raw file](https://github.com/sillsdev/serval/blob/ab748363b769db0ff54f4cde78ac110eb62de082/src/Serval.Translation/Usings.cs#L26)):*
> ```Smalltalk
> global using Serval.Translation.Services;
> global using SIL.DataAccess;
> global using System.Text.Json;
> ```

Please sort the usings.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.Shared/Utils/ObjectToInferredTypesConverter.cs` line 1 at r3](https://reviewable.io/reviews/sillsdev/serval/152#-Ng5DTTo1_zTDxM81Asw:-Ng5IvAo9dROSNS3x0Bp:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ab748363b769db0ff54f4cde78ac110eb62de082/src/Serval.Shared/Utils/ObjectToInferredTypesConverter.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to specify a namespace.
</blockquote></details>

Done.
___
*[`src/Serval.Translation/Usings.cs` line 26 at r3](https://reviewable.io/reviews/sillsdev/serval/152#-Ng5D_-S2gsSNYtiqYCD:-Ng5Ivwd0M9U4Oa8J3XV:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ab748363b769db0ff54f4cde78ac110eb62de082/src/Serval.Translation/Usings.cs#L26)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please sort the usings.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152#-:-Ng5Z0Vz4I6o-2OGW23d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
