### PR TITLE
Update MemoryUpdateBuilder to work with read-only collections

### PR DESCRIPTION
**Pull request by ddaspit**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/324)

### CODE REVIEW

**Comment by johnml1135** [comment]
* The if conditions for removing and adding items look a little squirly - can they be condensed into a single set of logic?  Why the subtle differences?
* The SetOnInsert and Unset functions are untested
* Collection type removals are not tested (not covered)

**Review by ddaspit — COMMENTED** [review]
I added the requested unit tests. Although each of the collection methods share a similar structure, they each perform a different operation. It would be a bit goofy to pull the shared structure into a separate method.  I would have to pass in delegates to inject the correct code into the structure.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/324#-:-Nr7nf9_EQO2igwc7vHm:b-nt3fq8)* status: 0 of 5 files reviewed, all discussions resolved

**Comment by johnml1135** [comment]
*[`src/SIL.DataAccess/MemoryUpdateBuilder.cs` line 88 at r2](https://reviewable.io/reviews/sillsdev/serval/324#-NrAvV-83fhx1IRbOObv:-NrAvV-83fhx1IRbOObw:bnd1t9g) ([raw file](https://github.com/sillsdev/serval/blob/70652fa6848e1663e04360eaf46b77626b143c77/src/SIL.DataAccess/MemoryUpdateBuilder.cs#L88)):*
> ```Smalltalk
>                     // the collection type is an array or interface, so construct a new array and set property
>                     TItem[] newValue = collection.Where(i => !predicateFunc(i)).ToArray();
>                     prop.SetValue(owner, newValue, indices);
> ```

This structure is a bit confusing to me.  Let's see if I understand it:
* This class is to provide Mongo-like behavior to the memory repository
* Owners are the entities in the Memory repository
* Fields are the fields (such as corpora in engines)
* Here, you are adding or removing fields in the entities, now some of which are immutable (records).

**Comment by johnml1135** [comment]
For some reason the code coverage report is not loading up.  It now makes sense what you are doing.  :lgtm:

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/324)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/324)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
