### PR TITLE
Ietf tag doc update #134

### PR DESCRIPTION
**Pull request by Enkidu93**
Finish updates as per @ddaspit 's comment.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/136)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/136)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 91 at r2](https://reviewable.io/reviews/sillsdev/serval/136#-NengZvr1ZgXw9d83ygd:-NengZvr1ZgXw9d83yge:b-bk0sp) ([raw file](https://github.com/sillsdev/serval/blob/c8f709f2192437bc992e272d6459f5f065135290/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L91)):*
> ```Smalltalk
>     ///   * The name does not have to be unique, as the engine is uniquely identified by the auto-generated id
>     /// * **sourceLanguage**: The source language code
>     ///   * Note that for Nmt, if the source or target language code matches a [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag), the source IETF language tag will be converted to an [NLLB-200 code](https://github.com/facebookresearch/flores/tree/main/flores200#languages-in-flores-200) and use the language as-is. If possible, provide a valid IETF language tag.
> ```

This should be the recommendation for all engines. This sounds like it only applies to NMT engines. Maybe something like "**sourceLanguage**: The source language code (a valid IETF language tag is recommended)". And the same for `targetLanguage`.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/136)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 91 at r2](https://reviewable.io/reviews/sillsdev/serval/136#-NengZvr1ZgXw9d83ygd:-Neo--3J3gGYK8s5534h:b-58tlfd) ([raw file](https://github.com/sillsdev/serval/blob/c8f709f2192437bc992e272d6459f5f065135290/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L91)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be the recommendation for all engines. This sounds like it only applies to NMT engines. Maybe something like "**sourceLanguage**: The source language code (a valid IETF language tag is recommended)". And the same for `targetLanguage`.
</blockquote></details>

Is that better?

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/136#-:-NeoJVR35H2KfIfpvh8W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by johnml1135 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
