### PR TITLE
Move logic from entity base to MongoRepo

### PR DESCRIPTION
**Pull request by Enkidu93**
Continuation of https://github.com/sillsdev/serval/pull/459

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/466)

### CODE REVIEW

**Review by johnml1135 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Comment by johnml1135** [comment]
Can you add tests to verify the "entity not found" behavior for webhooks, translation engines and assessment engines?

**Comment by johnml1135** [comment]
So we can make sure all of Mike Pelley's tests pass.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by Enkidu93 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/466#-:-O5F49Rr4rEQ3IzU6ooL:b-896fix)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/466)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/DataAccess/src/SIL.DataAccess/MongoRepository.cs` line 22 at r2](https://reviewable.io/reviews/sillsdev/serval/466#-O5F5JEWEd0Pvu991ay6:-O5F5JEWEd0Pvu991ay7:b-e5y16j) ([raw file](https://github.com/sillsdev/serval/blob/d9689fd7660fee328eaffec7d44e54b32b136878/src/DataAccess/src/SIL.DataAccess/MongoRepository.cs#L22)):*
> ```Smalltalk
>             return await _collection.AsQueryable().FirstOrDefaultAsync(filter, cancellationToken).ConfigureAwait(false);
>         }
>         catch (FormatException)
> ```

I would guess that this same exception can occur on other methods as well, i.e. `ExistsAsync`, `UpdateAsync`, `DeleteAsync`, etc.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/466)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/DataAccess/src/SIL.DataAccess/MongoRepository.cs` line 22 at r2](https://reviewable.io/reviews/sillsdev/serval/466#-O5F5JEWEd0Pvu991ay6:-O5FxUmHDBBAGQOpYegr:bhkjmd2) ([raw file](https://github.com/sillsdev/serval/blob/d9689fd7660fee328eaffec7d44e54b32b136878/src/DataAccess/src/SIL.DataAccess/MongoRepository.cs#L22)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would guess that this same exception can occur on other methods as well, i.e. `ExistsAsync`, `UpdateAsync`, `DeleteAsync`, etc.
</blockquote></details>

Done. I think I put them wherever appropriate. I'm not sure that all of errors are reachable via the API, but since the `DataAccess` is modular, I guess it makes sense. Which reminds me: We'll need to release a new version for these to take effect then, right?

**Comment by johnml1135** [comment]
*[`src/DataAccess/src/SIL.DataAccess/MongoRepository.cs` line 205 at r3](https://reviewable.io/reviews/sillsdev/serval/466#-O5IhgXaE8S0lCrnqhf1:-O5IhgXaE8S0lCrnqhf2:b-a2lmma) ([raw file](https://github.com/sillsdev/serval/blob/5e5364ad26d605f3f23dca695721f77f56a2af4b/src/DataAccess/src/SIL.DataAccess/MongoRepository.cs#L205)):*
> ```Smalltalk
>             return default;
>         }
>     }
> ```

If there are 6? try-catches added and only 3 test cases, why?

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/466#-:-O5Jc_UM7o2x6F_fro7M:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/DataAccess/src/SIL.DataAccess/MongoRepository.cs` line 22 at r2](https://reviewable.io/reviews/sillsdev/serval/466#-O5F5JEWEd0Pvu991ay6:-O5Jcarw1DFAjsJXQeQ0:bpstgqu) ([raw file](https://github.com/sillsdev/serval/blob/d9689fd7660fee328eaffec7d44e54b32b136878/src/DataAccess/src/SIL.DataAccess/MongoRepository.cs#L22)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done. I think I put them wherever appropriate. I'm not sure that all of errors are reachable via the API, but since the `DataAccess` is modular, I guess it makes sense. Which reminds me: We'll need to release a new version for these to take effect then, right?
</blockquote></details>

We actually don't have to release it anymore, since all of the assemblies that use SIL.DataAccess are in the same repo and no longer have to get the package from NuGet. We can still release it just to keep it up-to-date on NuGet. 
___
*[`src/DataAccess/src/SIL.DataAccess/MongoRepository.cs` line 205 at r3](https://reviewable.io/reviews/sillsdev/serval/466#-O5IhgXaE8S0lCrnqhf1:-O5JdEoaA1EI-WzHHwb_:bn9fru9) ([raw file](https://github.com/sillsdev/serval/blob/5e5364ad26d605f3f23dca695721f77f56a2af4b/src/DataAccess/src/SIL.DataAccess/MongoRepository.cs#L205)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If there are 6? try-catches added and only 3 test cases, why?
</blockquote></details>

The integration tests are expensive. I think the tests that Eli added are probably sufficient.

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
