### PR TITLE
What about 6 retries and not 3?

### PR DESCRIPTION
**Pull request by johnml1135**
#524 There are some failures from ClearML erroring out.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/526)

### CODE REVIEW

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/526)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/526#-OATUmeMBr2ly-JibBZA:-OATUmeMBr2ly-JibBZB:b-c8qpv4) ([raw file](https://github.com/sillsdev/serval/blob/3c140c3b4f5bcb066deccb7da66b1141f9cc0065/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L165)):*
> ```Smalltalk
>                 b.WaitAndRetryAsync(
>                     6,
>                     retryAttempt => TimeSpan.FromSeconds(Math.Pow(1.5, retryAttempt)),
> ```

If we're getting hit with `TooManyRequests` as it is, will this really improve the issue? I understand the hope, but is this the best change? We've definitely seen fewer of these errors lately than we were before. Would maybe upping the timespan rather than upping the number of attempts be a good idea? @ddaspit, thoughts?

**Review by ddaspit — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/526)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/526#-OATUmeMBr2ly-JibBZA:-OATW7Vb2CARFNBz9h8b:bffciut) ([raw file](https://github.com/sillsdev/serval/blob/3c140c3b4f5bcb066deccb7da66b1141f9cc0065/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L165)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

If we're getting hit with `TooManyRequests` as it is, will this really improve the issue? I understand the hope, but is this the best change? We've definitely seen fewer of these errors lately than we were before. Would maybe upping the timespan rather than upping the number of attempts be a good idea? @ddaspit, thoughts?
</blockquote></details>

I agree with Eli. If we are still encountering this issue occasionally, we probably want to tweak the polling timeout.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/526#-OATUmeMBr2ly-JibBZA:-OATZBkxCe33HDDxEpcx:bfkgg99) ([raw file](https://github.com/sillsdev/serval/blob/3c140c3b4f5bcb066deccb7da66b1141f9cc0065/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L165)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I agree with Eli. If we are still encountering this issue occasionally, we probably want to tweak the polling timeout.
</blockquote></details>

I have seen errors on E2E tests - It caused 10 "TooManyRequests" errors on QA in the past day.
I reverted to the first few having the same timing and upped the overall timing to 56 seconds.

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/526)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/526#-OATUmeMBr2ly-JibBZA:-OATarhVAXPCUywOnvLm:b-lyn5wj) ([raw file](https://github.com/sillsdev/serval/blob/3c140c3b4f5bcb066deccb7da66b1141f9cc0065/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L165)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I have seen errors on E2E tests - It caused 10 "TooManyRequests" errors on QA in the past day.
I reverted to the first few having the same timing and upped the overall timing to 56 seconds.
</blockquote></details>

@johnml1135, I was think more like increasing the rate of backoff. What about 3, 9, 27  (sum 39)? Or 2.25^1, 2.25^2, 2.25^3, 2.25^4 (still under 1 minute)?
___
*[`src/Serval/src/Serval.Webhooks/Configuration/IServalBuilderExtensions.cs` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/526#-OATaoGk8TmG02SbF3S_:-OATaoGk8TmG02SbF3Sa:bopwetx) ([raw file](https://github.com/sillsdev/serval/blob/9b5d2c9f7eddcd41b178a3adc9974da3a39e1061/src/Serval/src/Serval.Webhooks/Configuration/IServalBuilderExtensions.cs#L9)):*
> ```Smalltalk
>         builder
>             .Services.AddHttpClient<WebhookJob>()
>             // Add retry policy; fail after approx. 1.5 + 2.25 ... 1.5^6 ~= 31 seconds
> ```

Is this meant to be here?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Webhooks/Configuration/IServalBuilderExtensions.cs` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/526#-OATaoGk8TmG02SbF3S_:-OATc7Eo6rYn9nAftBwP:bmykhvv) ([raw file](https://github.com/sillsdev/serval/blob/9b5d2c9f7eddcd41b178a3adc9974da3a39e1061/src/Serval/src/Serval.Webhooks/Configuration/IServalBuilderExtensions.cs#L9)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is this meant to be here?
</blockquote></details>

Should have been removed before.

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/526#-OATUmeMBr2ly-JibBZA:-OATcEx0-qu8DhvOeXHP:b-uast4b) ([raw file](https://github.com/sillsdev/serval/blob/3c140c3b4f5bcb066deccb7da66b1141f9cc0065/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L165)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

@johnml1135, I was think more like increasing the rate of backoff. What about 3, 9, 27  (sum 39)? Or 2.25^1, 2.25^2, 2.25^3, 2.25^4 (still under 1 minute)?
</blockquote></details>

For high workload, a linear back off is often recommended.  Updated to linear back off.

**Review by Enkidu93 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/526)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/526#-OATUmeMBr2ly-JibBZA:-OATfMdB3D2zsxud9w8x:b32w1t) ([raw file](https://github.com/sillsdev/serval/blob/3c140c3b4f5bcb066deccb7da66b1141f9cc0065/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L165)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

For high workload, a linear back off is often recommended.  Updated to linear back off.
</blockquote></details>

Ok

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 165 at r1](https://reviewable.io/reviews/sillsdev/serval/526#-OATUmeMBr2ly-JibBZA:-OATgHbk9jk8HRlGxvkX:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/3c140c3b4f5bcb066deccb7da66b1141f9cc0065/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L165)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

Done.

**Pull request merged**
