### PR TITLE
Fix usfm parsing bugs

### PR DESCRIPTION
**Pull request by Enkidu93**
Update Serval to use `ParatextProjectTextUpdater`

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/447)

### CODE REVIEW

**Comment by Enkidu93** [comment]
Parallel PR: https://github.com/sillsdev/machine/pull/229

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/447)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Shared/Services/IScriptureDataFileService.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/447#-O3JXVh-05A3_YGMm1ko:-O3JXVh-05A3_YGMm1kp:b-5takwx) ([raw file](https://github.com/sillsdev/serval/blob/9f41969e65aab04f1cea745f8bbbdcfce3b1b3eb/src/Serval/src/Serval.Shared/Services/IScriptureDataFileService.cs#L6)):*
> ```Smalltalk
> {
>     ParatextProjectSettings GetParatextProjectSettings(string filename);
>     public ZipParatextProjectTextUpdater GetZipParatextProjectTextUpdater(string filename);
> ```

The `public` keyword shouldn't be needed in an interface.
___
*[`src/Serval/src/Serval.Translation/Services/PretranslationService.cs` line 122 at r1](https://reviewable.io/reviews/sillsdev/serval/447#-O3JmAHE092_8YFsK4gl:-O3JmAHE092_8YFsK4gm:b-xym34t) ([raw file](https://github.com/sillsdev/serval/blob/9f41969e65aab04f1cea745f8bbbdcfce3b1b3eb/src/Serval/src/Serval.Translation/Services/PretranslationService.cs#L122)):*
> ```Smalltalk
>             }
>             // In order to support PretranslationUsfmTemplate.Auto
>             if (usfm != "")
> ```

I think we need to check if the usfm is `null`.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/447)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Shared/Services/IScriptureDataFileService.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/447#-O3JXVh-05A3_YGMm1ko:-O3YgX2PAYmKVrPgr2Xx:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/9f41969e65aab04f1cea745f8bbbdcfce3b1b3eb/src/Serval/src/Serval.Shared/Services/IScriptureDataFileService.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `public` keyword shouldn't be needed in an interface.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/PretranslationService.cs` line 122 at r1](https://reviewable.io/reviews/sillsdev/serval/447#-O3JmAHE092_8YFsK4gl:-O3YgXvJ3i1-45bv7vYX:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/9f41969e65aab04f1cea745f8bbbdcfce3b1b3eb/src/Serval/src/Serval.Translation/Services/PretranslationService.cs#L122)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think we need to check if the usfm is `null`.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/447#-:-O3Z526x-RW52wgCW_VL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Review by Enkidu93 — COMMENTED** [review]
Sorry, @ddaspit , few more changes: I realized that I was disposing of the `ZipContainer` prematurely. Also, if a book is totally empty, you do end up with `usfm = ""` at that check, so a test fails if we just have `if(usfm!=null)...` - switched to `IsNullOrEmpty`.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/447#-:-O3ZHwwYAbpWBVCy3dL8:bcmjzg0)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @ddaspit and @johnml1135)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/447)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Shared/Services/ZipParatextProjectTextUpdater.cs` line 3 at r3](https://reviewable.io/reviews/sillsdev/serval/447#-O3c9JJb3QcvIRMJHrYf:-O3c9JJb3QcvIRMJHrYg:bcmbz4b) ([raw file](https://github.com/sillsdev/serval/blob/176c8efce4081ab45ba418cfb0daca85c317d9e2/src/Serval/src/Serval.Shared/Services/ZipParatextProjectTextUpdater.cs#L3)):*
> ```Smalltalk
> namespace Serval.Shared.Services;
> 
> public class ZipParatextProjectTextUpdater : ParatextProjectTextUpdaterBase, IDisposable
> ```

You should follow the [dispose pattern](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern) when implementing `IDisposable`.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/447)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Shared/Services/ZipParatextProjectTextUpdater.cs` line 3 at r3](https://reviewable.io/reviews/sillsdev/serval/447#-O3c9JJb3QcvIRMJHrYf:-O3c_jfV9g_mC-5YOKYD:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/176c8efce4081ab45ba418cfb0daca85c317d9e2/src/Serval/src/Serval.Shared/Services/ZipParatextProjectTextUpdater.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should follow the [dispose pattern](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern) when implementing `IDisposable`.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/447)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
