### PR TITLE
Fixes missed from previous PR

### PR DESCRIPTION
**Pull request by johnml1135**
I believe these are the fixes that didn't make it in (and were stored in the stash).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/367)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/367)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/PretranslationService.cs` line 73 at r1](https://reviewable.io/reviews/sillsdev/serval/367#-Nvcl1xo2vB8KDtT9Vox:-Nvcl1xo2vB8KDtT9Voy:b-a7n55m) ([raw file](https://github.com/sillsdev/serval/blob/d255c1cbf82e18b12e04ea8033b77f7971f75eeb/src/Serval.Translation/Services/PretranslationService.cs#L73)):*
> ```Smalltalk
>         string? usfm = await _scriptureDataFileService.ReadParatextProjectBookAsync(targetFile.Filename, textId);
>         if (usfm is not null)
>             return UpdateUsfm(targetSettings, usfm, pretranslations);
> ```

We should use relaxed comparison when updating the target book.
___
*[`src/Serval.Translation/Services/PretranslationService.cs` line 78 at r1](https://reviewable.io/reviews/sillsdev/serval/367#-NvckjaU4URZTTBhJJFj:-NvckjaV5A2dvD4F5LQ8:bu6gmgf) ([raw file](https://github.com/sillsdev/serval/blob/d255c1cbf82e18b12e04ea8033b77f7971f75eeb/src/Serval.Translation/Services/PretranslationService.cs#L78)):*
> ```Smalltalk
>         usfm = await _scriptureDataFileService.ReadParatextProjectBookAsync(sourceFile.Filename, textId);
>         if (usfm is not null)
>             return UpdateUsfm(sourceSettings, usfm, pretranslations, targetSettings.FullName, stripAllText: true);
> ```

We should use strict comparison when copying the source book.

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/PretranslationService.cs` line 73 at r1](https://reviewable.io/reviews/sillsdev/serval/367#-Nvcl1xo2vB8KDtT9Vox:-NvgV-YaACbmINsKMBl2:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/d255c1cbf82e18b12e04ea8033b77f7971f75eeb/src/Serval.Translation/Services/PretranslationService.cs#L73)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should use relaxed comparison when updating the target book.
</blockquote></details>

done

**Comment by johnml1135** [comment]
*[`src/Serval.Translation/Services/PretranslationService.cs` line 78 at r1](https://reviewable.io/reviews/sillsdev/serval/367#-NvckjaU4URZTTBhJJFj:-NvgV0gmAdBr4lplHDJz:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/d255c1cbf82e18b12e04ea8033b77f7971f75eeb/src/Serval.Translation/Services/PretranslationService.cs#L78)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should use strict comparison when copying the source book.
</blockquote></details>

done

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/367#-:-NvgZLcO93g0Uz4GLEEt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Pull request merged**
