### PR TITLE
Add assessment API

### PR DESCRIPTION
**Pull request by ddaspit**
- add assessment API
- add AQuA engine
- restructure directories in preparation for moving Machine

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/389)

### CODE REVIEW

**Review by ddaspit — COMMENTED** [review]
Currently, the assessment API is turned off using a feature flag. I took a stab at updating the docker image to work with the directory structure change.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/389#-:-Ny2S4Nr7BrW-NsJnwGM:b-gogd6v)* status: 0 of 403 files reviewed, all discussions resolved

**Comment by johnml1135** [comment]
Do you want to do this one before my SMT work or after?

**Comment by johnml1135** [comment]
*[`.vscode/launch.json` line 31 at r1](https://reviewable.io/reviews/sillsdev/serval/389#-Ny3QuRF-3GdFy7yZlb1:-Ny3QuRF-3GdFy7yZlb2:b-9rdegu) ([raw file](https://github.com/sillsdev/serval/blob/9d19ed416bfc0a0a7533104ddd8a4304a0ce43c4/.vscode/launch.json#L31)):*
> ```JSON
>             "request": "launch",
>             "preLaunchTask": "build",
>             "program": "${workspaceFolder}/src/Serval/src/Serval.ApiServer/bin/Debug/net8.0/Serval.ApiServer.dll",
> ```

So, why the double nested of /src/Serva/src/Serval.Api....?  Different READMEs?  Are there now 3 different solutions?  Is there a specific logic you are following?

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Configuration/IAquaBuilderExtensions.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/389#-Ny3SxCSEp3VBsO4L9-w:-Ny3SxCSEp3VBsO4L9-x:b8x41od) ([raw file](https://github.com/sillsdev/serval/blob/9d19ed416bfc0a0a7533104ddd8a4304a0ce43c4/src/Aqua/src/Serval.Aqua.Shared/Configuration/IAquaBuilderExtensions.cs#L5)):*
> ```Smalltalk
> namespace Microsoft.Extensions.DependencyInjection;
> 
> public static class IAquaBuilderExtensions
> ```

Should an interface have actual functionality?  Should this be part of a normal class?

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Models/Corpus.cs` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7dEro4qmmPw37GaBn:-O-7dEro4qmmPw37GaBo:b-ajkwbn) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Aqua/src/Serval.Aqua.Shared/Models/Corpus.cs#L11)):*
> ```Smalltalk
>     public required int DataRevision { get; init; }
>     public int? VersionId { get; init; }
>     public int? RevisionId { get; init; }
> ```

Can we rename these Version and Revision - or at least put a comment in.  They are very confusing naming.  PublishedVersion?  DatabaseVersion?  I forget the exact semantic meaning.  Also, are we sure that we really care about it at this level?

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Models/CorpusFile.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7dhSY124DuMW9eLNC:-O-7dhSY124DuMW9eLND:baox73u) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Aqua/src/Serval.Aqua.Shared/Models/CorpusFile.cs#L6)):*
> ```Smalltalk
> {
>     Text = 0,
>     Paratext = 1
> ```

Would we want a unified FileFormat and Corpus, etc., or distinct ones?  Why would we want one or the other?

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Models/JobData.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7kkfuDrrzeNVI-0Sh:-O-7kkfuDrrzeNVI-0Si:b-nilk5j) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Aqua/src/Serval.Aqua.Shared/Models/JobData.cs#L6)):*
> ```Smalltalk
> {
>     public required CorpusData CorpusData { get; init; }
>     public CorpusData? ReferenceCorpusData { get; init; }
> ```

There probably should also be an array of other references.  How should we distinguish them?  BaselineCorpusData[]? ReferenceSetCorpusData[]?

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Models/Result.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7lJy8-IfksDaKS8gf:-O-7lJy8-IfksDaKS8gg:b-rpp9tx) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Aqua/src/Serval.Aqua.Shared/Models/Result.cs#L3)):*
> ```Smalltalk
> namespace Serval.Aqua.Shared.Models;
> 
> public record Result
> ```

There may be many types of results - should this be a NumericResult?  Should there be a potential of having it be associated with a word or position?  Possible StartPosition and EndPosition that are defaulted to -1 (the whole verse) but could specify a range?  Should there be a ResultBase that has these parameters that is inherited by NumericResult, TextResult, MessageResult, etc.?

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Services/PostprocessJobStage.cs` line 83 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7oC4Q9BhRg6qhv4P9:-O-7oC4Q9BhRg6qhv4PA:b6pqvds) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Aqua/src/Serval.Aqua.Shared/Services/PostprocessJobStage.cs#L83)):*
> ```Smalltalk
>     }
> 
>     private static bool IsInChapters(IReadOnlyDictionary<string, HashSet<int>> bookChapters, VerseRef vref)
> ```

IsInChapters is in Postprocessing?   That appears odd-wouldn't it be needed in more places?

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Services/ServalPlatformService.cs` line 10 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7ojVt9D-DmX0Rw3Jv:-O-7ojVt9D-DmX0Rw3Jw:bmavvf0) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Aqua/src/Serval.Aqua.Shared/Services/ServalPlatformService.cs#L10)):*
> ```Smalltalk
>     private readonly AssessmentPlatformApi.AssessmentPlatformApiClient _client = client;
> 
>     public async Task JobStartedAsync(string jobId, CancellationToken cancellationToken = default)
> ```

No JobUpdateStatus?  Just "started" and then "completed?

**Comment by johnml1135** [comment]
*[`src/AspNetCore/src/SIL.AspNetCore/Services/HangfireHealthCheck.cs` line 23 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7pNyO3hYC4oYenpJP:-O-7pNyO3hYC4oYenpJQ:b-ocq6ln) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/AspNetCore/src/SIL.AspNetCore/Services/HangfireHealthCheck.cs#L23)):*
> ```Smalltalk
>         }
> 
>         return Task.FromResult(HealthCheckResult.Unhealthy("There are no Hangfire servers running."));
> ```

Are we also checking that the AQUA server is reachable?

**Comment by johnml1135** [comment]
*[`src/AspNetCore/src/SIL.AspNetCore/Services/RecurrentTask.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7pUUX4TbJXG85wFEt:-O-7pUUX4TbJXG85wFEu:b-g0ona1) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/AspNetCore/src/SIL.AspNetCore/Services/RecurrentTask.cs#L3)):*
> ```Smalltalk
> namespace SIL.AspNetCore.Services;
> 
> public abstract class RecurrentTask(
> ```

When Machine is brought over, can we combine some of these classes?  There is likely unnessesary duplication.

**Comment by johnml1135** [comment]
*[`src/AspNetCore/src/SIL.AspNetCore/Utils/LanguageTagParser.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7pdYW5-PB5cktjwQB:-O-7pdYW5-PB5cktjwQC:b-bjhawt) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/AspNetCore/src/SIL.AspNetCore/Utils/LanguageTagParser.cs#L3)):*
> ```Smalltalk
> namespace SIL.AspNetCore.Utils;
> 
> public partial class LanguageTagParser
> ```

Duplicate from Machine.

**Comment by johnml1135** [comment]
*[`src/DataAccess/src/SIL.DataAccess/ObjectRefConvention.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7qFf069S3YNZGbfRz:-O-7qFf069S3YNZGbfS-:bz7tg7p) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/DataAccess/src/SIL.DataAccess/ObjectRefConvention.cs#L7)):*
> ```Smalltalk
>     public void Apply(BsonMemberMap memberMap)
>     {
>         if (memberMap.MemberName.EndsWith("Ref") && memberMap.MemberName.Length > 3)
> ```

What is this actually looking for?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Configuration/AssessmentOptions.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-GX3BtCR7bRHsW1y_W:-O-GX3BtCR7bRHsW1y_X:base0ja) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Configuration/AssessmentOptions.cs#L7)):*
> ```Smalltalk
>     public const string Key = "Assessment";
> 
>     public List<EngineInfo> Engines { get; set; } = new List<EngineInfo>();
> ```

The assessments reference other engines?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs` line 10 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-GXMNn8_SYthgOcqOp:-O-GXMNn8_SYthgOcqOq:bsu4cmo) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs#L10)):*
> ```Smalltalk
>     {
>         configurator.AddConsumer<DataFileDeletedConsumer>();
>         configurator.AddConsumer<DataFileUpdatedConsumer>();
> ```

it appears that you are wanting a more dynamic way of interacting with the rest of Serval (files and engines). Can we discuss what this will mean?  Specifically, it appears as if you want assessments to dynamically depend on files and engines.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 46 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-GYZNiCSjZ2ij1BgiV:-O-GYZNiCSjZ2ij1BgiW:bb40e0h) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L46)):*
> ```Smalltalk
>                 );
>                 await c.Indexes.CreateOrUpdateAsync(
>                     new CreateIndexModel<Result>(Builders<Result>.IndexKeys.Ascending(pt => pt.TextId))
> ```

Will this handle Greek room results as well?  Would we consider making some results files?  Would we want to group them by a combination of engine ID and verse reference - having all the assessments for one verse in one engine (one corpora or text ID?) be one document?  ... give me the assessments for John chapter 1 verse 4...

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Consumers/DataFileDeletedConsumer.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-Gv_ZT65Z4FPeg7wyO:-O-Gv_ZT65Z4FPeg7wyP:b-gvc4zr) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Consumers/DataFileDeletedConsumer.cs#L3)):*
> ```Smalltalk
> namespace Serval.Assessment.Consumers;
> 
> public class DataFileDeletedConsumer(ICorpusService corpusService) : IConsumer<DataFileDeleted>
> ```

Why do we need consumers for deleted files?  Will we take a specific action if a file is deleted?  With the new "self-hosted AQUA" paradigm, will it be needed?  Are we wanting assessments in general to "auto-run" if there has been an update to one of it's constituent parts (possibly a good idea... possibly not)?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Contracts/AssessmentEngineConfigDto.cs` line 23 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-GycWD3D6vaqfjVT4g:-O-GycWD3D6vaqfjVT4h:b-qmovfa) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Contracts/AssessmentEngineConfigDto.cs#L23)):*
> ```Smalltalk
>     /// The assessment engine reference corpus.
>     /// </summary>
>     public string? ReferenceCorpusId { get; init; }
> ```

If we are going to flip this, we would be referencing other engines instead.  Would we also want the "z standard" reference engine?  Of is this that - the corpus already being bi-lingual?  If so, it should be a list of referenceCorpusId's as the reference will likely be a group of other corpses/engines.

**Comment by johnml1135** [comment]
*[`src/Aqua/src/Serval.Aqua.Shared/Services/AquaAccessTokenHandler.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-7m5oi8DfBVhTACcxs:-O-7m5oi8DfBVhTACcxt:br9or6r) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Aqua/src/Serval.Aqua.Shared/Services/AquaAccessTokenHandler.cs#L3)):*
> ```Smalltalk
> namespace Serval.Aqua.Shared.Services;
> 
> public class AquaAccessTokenHandler(IAquaAuthService aquaAuthService) : DelegatingHandler
> ```

This is if we have to access AQUA instead of re-implementing.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Contracts/AssessmentResultDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-GzfGw2oG6KKv7ieja:-O-GzfGw2oG6KKv7iejb:b-t9mfbs) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Contracts/AssessmentResultDto.cs#L7)):*
> ```Smalltalk
>     public required string TextId { get; init; }
>     public required string Ref { get; init; }
>     public double? Score { get; init; }
> ```

Again - this should likely be LSP's diagnostic more than just a double.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Controllers/AssessmentCorporaController.cs` line 1 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-GzvEl72GmlqSNZczx:-O-GzvEl72GmlqSNZczy:bqbynfk) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Controllers/AssessmentCorporaController.cs#L1)):*
> ```Smalltalk
> namespace Serval.Assessment.Controllers;
> ```

If we don't need to work with the AQUA server, we should kill the separate corpora/engine differentiation.  It provides no value.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Models/Corpus.cs` line 9 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-H-Wqa37-yZmZYu1ws:-O-H-WqbC84zJXScnif-:b-bp74yg) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Models/Corpus.cs#L9)):*
> ```Smalltalk
>     public required string Owner { get; init; }
>     public string? Name { get; init; }
>     public required string Language { get; init; }
> ```

So, a corpus will not be parallel languages, but merely one?  Without the AQUA server, should it be this way?  Yes, there is no longer a source and target... I can see why it may be better to have a "corpus under assessment" and then a "reference corpus" and then possibly a "assessment standard" to compare against, such as for z-score or missing words.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Services/AssessmentPlatformServiceV1.cs` line 34 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-H2k0h3z4NZ_2PW7tc:-O-H2k0h3z4NZ_2PW7td:bcc2m2x) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Services/AssessmentPlatformServiceV1.cs#L34)):*
> ```Smalltalk
>                 );
>                 if (job is null)
>                     throw new RpcException(new Status(StatusCode.NotFound, "The job does not exist."));
> ```

We have to create the job before we run it?  Why?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Services/AssessmentPlatformServiceV1.cs` line 34 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-H2k0h3z4NZ_2PW7tc:-O-H33od5s1ikZZe_8aB:bke0ag1) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Services/AssessmentPlatformServiceV1.cs#L34)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

We have to create the job before we run it?  Why?
</blockquote></details>

Ah - this is run in hangfire after the job has been queued?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Services/CorpusService.cs` line 21 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-H3cl48xD2X1LPJ0Ly:-O-H3cl48xD2X1LPJ0Lz:bzdue6f) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Services/CorpusService.cs#L21)):*
> ```Smalltalk
>     }
> 
>     public Task DataFileUpdated(string dataFileId, CancellationToken cancellationToken = default)
> ```

So, without the AQUA server, these "data file updated/deleted" routines will not be needed, as there will only be one truth of files that exist...

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Services/EngineService.cs` line 124 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-H4SpK34TXj6IqT3Pa:-O-H4SpK34TXj6IqT3Pb:b-w0vh9x) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Services/EngineService.cs#L124)):*
> ```Smalltalk
>             if (job.ScriptureRange is not null)
>             {
>                 if (corpus.Files.Count > 1 || corpus.Files[0].Format != Shared.Contracts.FileFormat.Paratext)
> ```

corpus.Files.Count > 0.  What if there is only 1 zip file?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Services/ICorpusService.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-H6Ihf0RZcfumcM9iM:-O-H6Ihf0RZcfumcM9iN:b3bz6kx) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Services/ICorpusService.cs#L5)):*
> ```Smalltalk
> public interface ICorpusService
> {
>     Task<IEnumerable<Corpus>> GetAllAsync(string owner, CancellationToken cancellationToken = default);
> ```

Again - assuming that this gets rolled into engine service - and we don't need to propagate changes.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Assessment/Services/JobService.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-M0nds-x0bEqYzMvt5:-O-M0ndt2xig7IUesRd6:b-68ay1f) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Assessment/Services/JobService.cs#L6)):*
> ```Smalltalk
>     : EntityServiceBase<Job>(jobs),
>         IJobService
> {
> ```

Assuming it will be merged with machine job service.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Shared/Contracts/DataFileUpdated.cs` line 4 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-M4wXdAnrUd2MfQXeh:-O-M4wXdAnrUd2MfQXei:b-3xt45) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Shared/Contracts/DataFileUpdated.cs#L4)):*
> ```Smalltalk
> 
> public record DataFileUpdated
> {
> ```

We may not need this.

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Shared/Services/OwnedEntityServiceBase.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-M5McX9bpOE9ATxcKJ:-O-M5McX9bpOE9ATxcKK:bfskpn) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Shared/Services/OwnedEntityServiceBase.cs#L3)):*
> ```Smalltalk
> namespace Serval.Shared.Services;
> 
> public abstract class OwnedEntityServiceBase<T>(IRepository<T> entities) : EntityServiceBase<T>(entities)
> ```

How is owned entity used?  Is it used for files as well as other engines?  Is this the parent/child relationship I was thinking of?  Owned/owner?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Webhooks/Consumers/AssessmentJobFinishedConsumer.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-M6B9c6wIsk9hsZDa9:-O-M6B9c6wIsk9hsZDaA:b-t1y3u4) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Webhooks/Consumers/AssessmentJobFinishedConsumer.cs#L3)):*
> ```Smalltalk
> namespace Serval.Webhooks.Consumers;
> 
> public class AssessmentJobFinishedConsumer(IWebhookService webhookService, IUrlService urlService)
> ```

Do these consumers/producers interact with MassTransit?  Is it only internal to a single docker image or is it over gRPC or similar?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Webhooks/Consumers/AssessmentJobFinishedConsumer.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-M6B9c6wIsk9hsZDa9:-O-M6SJvAMGQ_XSMu4Xh:bq2sxvr) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Webhooks/Consumers/AssessmentJobFinishedConsumer.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Do these consumers/producers interact with MassTransit?  Is it only internal to a single docker image or is it over gRPC or similar?
</blockquote></details>

It's webhooks - but what exactly does that mean and why is this paradigm chosen?  Why is it needed here but not for Machine?  Is it specific to the external AQUA instance and will be removed?

**Comment by johnml1135** [comment]
*[`src/Serval/src/Serval.Webhooks/Consumers/AssessmentJobFinishedConsumer.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/389#-O-M6B9c6wIsk9hsZDa9:-O-MNSwoEjDWgwQZw00t:b-ulj2ig) ([raw file](https://github.com/sillsdev/serval/blob/aae7570c6933050c362a205129b986702929f136/src/Serval/src/Serval.Webhooks/Consumers/AssessmentJobFinishedConsumer.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It's webhooks - but what exactly does that mean and why is this paradigm chosen?  Why is it needed here but not for Machine?  Is it specific to the external AQUA instance and will be removed?
</blockquote></details>

Correction - this is a mirror of translationBuildStarted.  Can/should it share more with it?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 397 of 403 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/389)* status: all files reviewed, 30 unresolved discussions (waiting on @ddaspit)

**Comment by ddaspit** [comment]
I will submit separate PRs to restructure the repo into a monorepo, move the Machine engine to the repo, and add the assessment API.

**Pull request closed without merging**
