### PR TITLE
make sure parallel corpora exist before updating

### PR DESCRIPTION
**Pull request by johnml1135**
Fix for #564

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/565)

### CODE REVIEW

**Comment by johnml1135** [comment]
When a DataFile is being updated, it syncs the filename to the corpora and parallelCorpora.  The old records in the database don't have parallel-corpora, and when the update is pushed, it cannot filter because the field (parallelCorpora) does not exist.  This adds it on startup (migration) ensuring that the update operation can work.

**Review by ddaspit — APPROVED** [review]
At some point, we probably want to store a model version in the DB, so that we only run the migration if we need to.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/565#-:-ODqEu5K5lDauO6-JH4B:bsistvo)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by ddaspit** [comment]
@Enkidu93 We did not mark the new `ParallelCorpora` property as optional in the model in the mixed source PR.

**Review by Enkidu93 — APPROVED** [review]
OK, yep, that's a good point.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/565#-:-ODqVZ00D7ve_LNbgsCK:b-wv807c)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

**Comment by johnml1135** [comment]
This is remove the migration scripts: https://github.com/sillsdev/serval/issues/567

**Pull request merged**
