### PR TITLE
Add SIL.ServiceToolkit library

### PR DESCRIPTION
**Pull request by ddaspit**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/456)

### CODE REVIEW

**Comment by johnml1135** [comment]
Do you have a preference to reviewing this or the AQUA API first?

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/LanguageTagService.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/456#-O4elro4En0SW1XnfnD7:-O4elro4En0SW1XnfnD8:bvqtc3o) ([raw file](https://github.com/sillsdev/serval/blob/0cbf32e44a9ec107b303ad3bd7be173dd99463b2/src/Machine/src/Serval.Machine.Shared/Services/LanguageTagService.cs#L5)):*
> ```Smalltalk
> public class LanguageTagService : ILanguageTagService
> {
>     private static readonly Dictionary<string, string> StandardLanguages =
> ```

Was all of this code really able to be removed because of the updated SIL writing systems?

**Comment by johnml1135** [comment]
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/LanguageTagServiceTests.cs` line 66 at r1](https://reviewable.io/reviews/sillsdev/serval/456#-O4em8jED7nNv24BSk9D:-O4em8jED7nNv24BSk9E:b7dhxms) ([raw file](https://github.com/sillsdev/serval/blob/0cbf32e44a9ec107b303ad3bd7be173dd99463b2/src/Machine/test/Serval.Machine.Shared.Tests/Services/LanguageTagServiceTests.cs#L66)):*
> ```Smalltalk
>             Sldr.Initialize();
>         var service = new TestLanguageTagService();
>         service.ConvertToFlores200Code("en", out string internalCode);
> ```

Why are these tests removed?

**Comment by johnml1135** [comment]
*[`src/Machine/src/Serval.Machine.Shared/Services/LanguageTagService.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/456#-O4elro4En0SW1XnfnD7:-O4en8HdC1P9CAqk-jRn:b5j1awx) ([raw file](https://github.com/sillsdev/serval/blob/0cbf32e44a9ec107b303ad3bd7be173dd99463b2/src/Machine/src/Serval.Machine.Shared/Services/LanguageTagService.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Was all of this code really able to be removed because of the updated SIL writing systems?
</blockquote></details>

I see now.

**Comment by johnml1135** [comment]
:lgtm:

**Review by johnml1135 — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/456)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)

**Comment by johnml1135** [comment]
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/LanguageTagServiceTests.cs` line 66 at r1](https://reviewable.io/reviews/sillsdev/serval/456#-O4em8jED7nNv24BSk9D:-O4enVcr2jN6hQmFwt7o:b-1nj92r) ([raw file](https://github.com/sillsdev/serval/blob/0cbf32e44a9ec107b303ad3bd7be173dd99463b2/src/Machine/test/Serval.Machine.Shared.Tests/Services/LanguageTagServiceTests.cs#L66)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why are these tests removed?
</blockquote></details>

I don't see where they were moved to.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/456)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Review by Enkidu93 — COMMENTED** [review]
:lgtm: What's the scope meant to be of this library? 

> Reviewed 4 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/456#-:-O4exsUz1CZXGZFHCpQv:b-9ebrmq)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Comment by johnml1135** [comment]
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/LanguageTagServiceTests.cs` line 66 at r1](https://reviewable.io/reviews/sillsdev/serval/456#-O4em8jED7nNv24BSk9D:-O4ftsOf5kaduKYq7L6N:b-9nbaxq) ([raw file](https://github.com/sillsdev/serval/blob/0cbf32e44a9ec107b303ad3bd7be173dd99463b2/src/Machine/test/Serval.Machine.Shared.Tests/Services/LanguageTagServiceTests.cs#L66)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The purpose of the unit test was to retrieve a file from Github. I was concerned about accessing Github in an automated test, because Github places limits on how much an unauthenticated client can access its API. We have had issues with this in the past. I can refactor the class, so that the HTTP request can be mocked. That would allow us to perform the test without making an actual network request.
</blockquote></details>

I'm ok with it being pulled out - as long as it was intentional.

**Review by johnml1135 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
