### PR TITLE
Fix Filename sync issue

### PR DESCRIPTION
**Pull request by johnml1135**
Resolves https://github.com/sillsdev/serval/issues/547
Sync corpora and data files in translation engine
Make DataFile Corpuses only have a link to the DataFile
Fix ParallelCorpus Delete CorpusFile
Use mongoDB strings directly for Mongo array filtering (hacky solution - need to fix later https://github.com/sillsdev/serval/issues/553).
Broken implementation for MemoryRepository - https://github.com/sillsdev/serval/issues/554

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/serval/555)

### CODE REVIEW

**Review by Enkidu93 — COMMENTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 16 of 25 files at r1, 11 of 13 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/555)* status: all files reviewed, 5 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.DataFiles/Services/CorpusService.cs` line 6 at r4](https://reviewable.io/reviews/sillsdev/serval/555#-ODNTEly5UtyAysH2zPh:-ODNTElz7t8dqbcMq-J3:b-lx8vr6) ([raw file](https://github.com/sillsdev/serval/blob/ef0a47a9571c617fc520244b02d792cd9aefff4d/src/Serval/src/Serval.DataFiles/Services/CorpusService.cs#L6)):*
> ```Smalltalk
>     IRepository<Corpus> corpora,
>     IDataAccessContext dataAccessContext,
>     IDataFileService dataFileService,
> ```

We usually just use the repositories directly in entity services.
___
*[`src/Serval/src/Serval.DataFiles/Services/CorpusService.cs` line 47 at r4](https://reviewable.io/reviews/sillsdev/serval/555#-ODNTXs4-RRiMPFN3FQM:-ODNTXs4-RRiMPFN3FQN:bi2wtrs) ([raw file](https://github.com/sillsdev/serval/blob/ef0a47a9571c617fc520244b02d792cd9aefff4d/src/Serval/src/Serval.DataFiles/Services/CorpusService.cs#L47)):*
> ```Smalltalk
>                             {
>                                 TextId = f.TextId!,
>                                 File = Map(await _dataFileService.GetAsync(f.FileId))
> ```

You can retrieve all of the data files in a single query.
___
*[`src/Serval/src/Serval.DataFiles/Models/CorpusFile.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/555#-ODNQefW6MQcfec5uL-b:-ODNQefW6MQcfec5uL-c:b-cbhrmy) ([raw file](https://github.com/sillsdev/serval/blob/ef0a47a9571c617fc520244b02d792cd9aefff4d/src/Serval/src/Serval.DataFiles/Models/CorpusFile.cs#L5)):*
> ```Smalltalk
> public record CorpusFile
> {
>     public required string FileId { get; init; }
> ```

The convention when a property is a foreign key reference is to suffix with `Ref` instead of `Id`, i.e. `FileRef`.
___
*[`src/Serval/src/Serval.DataFiles/Consumers/GetCorpusConsumer.cs` line 27 at r4](https://reviewable.io/reviews/sillsdev/serval/555#-ODNRLDn35Hsu14Jz-Yj:-ODNRLDn35Hsu14Jz-Yk:bi2wtrs) ([raw file](https://github.com/sillsdev/serval/blob/ef0a47a9571c617fc520244b02d792cd9aefff4d/src/Serval/src/Serval.DataFiles/Consumers/GetCorpusConsumer.cs#L27)):*
> ```Smalltalk
>                         {
>                             TextId = f.TextId!,
>                             File = Map(await _dataFileService.GetAsync(f.FileId))
> ```

You can retrieve all of the data files in a single query.
___
*[`src/Serval/src/Serval.DataFiles/Contracts/CorpusFileDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/555#-ODNRZgyAixIw4ULqKxQ:-ODNRZgyAixIw4ULqKxR:b-cvec4y) ([raw file](https://github.com/sillsdev/serval/blob/ef0a47a9571c617fc520244b02d792cd9aefff4d/src/Serval/src/Serval.DataFiles/Contracts/CorpusFileDto.cs#L5)):*
> ```Smalltalk
> public record CorpusFileDto
> {
>     public required string FileId { get; init; }
> ```

This should be called `File` and be a `ResourceLinkDto`.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 11 of 13 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/555)* status: all files reviewed, 5 unresolved discussions (waiting on @johnml1135)

**Comment by johnml1135** [comment]
Damien made updates to address the concerns he had.

**Pull request merged**
